In [14]:
import pandas as pd
import json

In [15]:
# load fgo json data
try:
    # 2. Open the file using the 'with' statement
    with open('./fantasyGO_data.json', 'r') as f:
        # 3. Load the JSON data from the file
        fgo_23_24 = json.load(f)

    # The 'data' variable now holds your JSON content
    # In Jupyter, placing the variable at the end of the cell will display it
    print("✅ JSON file loaded successfully!")

except FileNotFoundError:
    print(f"❌ Error: The file ./fantasyGO_data.json was not found. Please check the path.")
except json.JSONDecodeError:
    print(f"❌ Error: The file ./fantasyGO_data.json is not a valid JSON file. Please check its contents.")

✅ JSON file loaded successfully!

In [16]:
fgo_picks = []

# Loop through each league in the top-level list
for gameweek_data in fgo_23_24:
    gameweek_info = {
        'gameweek': gameweek_data.get('contest').split(' ')[1],
        'contestant_no': gameweek_data.get('contestant_no'),
        'prize_pool': gameweek_data.get('prize_pool')
    }

    # Loop through each page within the league (e.g., "page_1", "page_2")
    for i in range(1, 1000): # Assuming a max of 999 pages
        page_key = f'page_{i}'
        if page_key in gameweek_data:
            # Loop through each manager's entry on the page
            for entry_data in gameweek_data[page_key]:
                entry_info = {
                    'manager': entry_data.get('manager'),
                    'entry_num': entry_data.get('entry'),
                    'total_points': entry_data.get('points'),
                    'prize': entry_data.get('prize')
                }

                # Loop through each player pick in the entry
                for pick_data in entry_data.get('pick', []):
                    # Combine all the info into a single record
                    full_record = {
                        **gameweek_info,
                        **entry_info,
                        **pick_data
                    }
                fgo_picks.append({**gameweek_info, **entry_data})
        else:
            break # Stop if the next page doesn't exist

pd.DataFrame(fgo_picks).to_csv('./fgo_managers.csv', index=False)

In [17]:
fgo_picks

[{'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'Radynster',
  'entry': '1',
  'points': '81.5 Points',
  'prize': 'R 5,596.88',
  'pick': [{'player_name': 'Sanchez',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Veltman',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Wan-Bissaka',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Mitoma',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Souček',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Ndombele',
    'points': '0',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Eze',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'João Pedro',
    'points': '10.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'Nketiah',
    'points': '8',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'paradise-prince',
  'entry': '2',
  'points': '79.5 Points',
  'prize': 'R 1,721.93',
  'pick': [{'player_name': 'Steele',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Holgate',
    'points': '0',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Wan-Bissaka',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Botman',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rodrigo',
    'points': '13',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Garnacho',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Mount',
    'points': '4.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Enzo',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'J.Alvarez',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Nketiah',
    'points': '8',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'KloppinSquad 2.0',
  'entry': '1',
  'points': '77.5 Points',
  'prize': 'R 430.69',
  'pick': [{'player_name': 'Steele',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Wan-Bissaka',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gabriel',
    'points': '1.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Akanji',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rodrigo',
    'points': '13',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Enciso',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Chukwuemeka',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Martinelli',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Kovačić',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'zbongo',
  'entry': '1',
  'points': '77.5 Points',
  'prize': 'R 430.69',
  'pick': [{'player_name': 'Forster',
    'points': '0',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Dunk',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Veltman',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Guéhi',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Wan-Bissaka',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Bowen',
    'points': '13.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Mitoma',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Casemiro',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rice',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Souček',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'jacquesmieny',
  'entry': '1',
  'points': '76 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Onana',
    'points': '9',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Walker',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gabriel',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Stones',
    'points': '0',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Baldock',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saka',
    'points': '15',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Nakamba',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Chukwuemeka',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'João Pedro',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'imokstopasking',
  'entry': '1',
  'points': '73.5 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Leno',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Mings',
    'points': '0',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Tarkowski',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Guéhi',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Botman',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Antony',
    'points': '4.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'March',
    'points': '9',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Reed',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rice',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Andreas',
    'points': '4',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'MRS T',
  'entry': '1',
  'points': '73 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Steele',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Pinnock',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saliba',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saka',
    'points': '20',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'Tonali',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Bowen',
    'points': '9',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Luis Díaz',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Enciso',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Ferguson',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Watkins',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'swaghettiyolognese14',
  'entry': '1',
  'points': '72.5 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Leno',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Beyer',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Botman',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Baldock',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saliba',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Mitoma',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Douglas Luiz',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Martinelli',
    'points': '7.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Anderson',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'João Pedro',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'fpljonnas',
  'entry': '1',
  'points': '72 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Johnstone',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Walker',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saliba',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Mbeumo',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Richarlison',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Garnacho',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saka',
    'points': '20',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'Eze',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'João Pedro',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Watkins',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'maxreich',
  'entry': '1',
  'points': '70.5 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Johnstone',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gabriel',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Wan-Bissaka',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'B.Fernandes',
    'points': '4.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Garnacho',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rice',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Chukwuemeka',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Anderson',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Edouard',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Haaland',
    'points': '26',
    'position': '',
    'is_captin': True,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'frankyza',
  'entry': '1',
  'points': '69 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Leno',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Botman',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Veltman',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Wan-Bissaka',
    'points': '12',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rashford',
    'points': '6',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'Saka',
    'points': '15',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Bernardo',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gross',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Barnes',
    'points': '11',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Welbeck',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Vinícius',
    'points': '0',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'Nico Celento',
  'entry': '4',
  'points': '66.5 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Johnstone',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Chilwell',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gabriel',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saka',
    'points': '20',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'Martinelli',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Souček',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rashford',
    'points': '4.5',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Ings',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'João Pedro',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Ogbene',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'fpl_chad',
  'entry': '1',
  'points': '66 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Johnstone',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Estupiñan',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gabriel',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Shaw',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rashford',
    'points': '6',
    'position': '',
    'is_captin': True,
    'is_vice': False},
   {'player_name': 'Saka',
    'points': '15',
    'position': '',
    'is_captin': False,
    'is_vice': True},
   {'player_name': 'Garnacho',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Mitoma',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Eze',
    'points': '3',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'João Pedro',
    'points': '7',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Nketiah',
    'points': '8',
    'position': '',
    'is_captin': False,
    'is_vice': False}]},
 {'gameweek': '1',
  'contestant_no': '175',
  'prize_pool': 'R 8,180.18',
  'manager': 'eksteenvd@yahoo.com',
  'entry': '1',
  'points': '65.5 Points',
  'prize': 'R 25.00',
  'pick': [{'player_name': 'Ederson M.',
    'points': '6',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Botman',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Gabriel',
    'points': '1',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Saliba',
    'points': '5',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Van Hecke',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Baldock',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Richarlison',
    'points': '2',
    'position': '',
    'is_captin': False,
    'is_vice': False},
   {'player_name': 'Rodrigo',
    'points': '13',

In [ ]:
# 2. Flatten the nested fgo_23_24
all_picks = []

# Loop through each league in the top-level list
for gameweek_data in fgo_23_24:
    gameweek_info = {
        'gameweek': gameweek_data.get('contest').split(' ')[1],
        'contestant_no': gameweek_data.get('contestant_no'),
        'prize_pool': gameweek_data.get('prize_pool')
    }
    # Loop through each page within the league (e.g., "page_1", "page_2")
    for i in range(1, 100): # Assuming a max of 99 pages
        page_key = f'page_{i}'
        if page_key in gameweek_data:
            # Loop through each manager's entry on the page
            for entry_data in gameweek_data[page_key]:
                entry_info = {
                    'manager': entry_data.get('manager'),
                    'entry_num': entry_data.get('entry'),
                    'total_points': entry_data.get('points'),
                    'prize': entry_data.get('prize')
                }

                # Loop through each player pick in the entry
                for pick_data in entry_data.get('pick', []):
                    # Combine all the info into a single record
                    full_record = {
                        **gameweek_info,
                        **entry_info,
                        **pick_data
                    }
                    all_picks.append(full_record)
        else:
            break # Stop if the next page doesn't exist

# 3. Create the DataFrame
fgo_df = pd.DataFrame(all_picks)

# Optional: Clean up the 'points' and 'total_points' columns
fgo_df['points'] = pd.to_numeric(fgo_df['points'])
fgo_df['total_points'] = fgo_df['total_points'].str.replace(' Points', '', regex=False).astype(float)

# --- Display the Result ---
print("✅ DataFrame created successfully!")
print(f"Total rows: {len(fgo_df)}")
print("\n--- Sample of the final DataFrame ---")

fgo_df

✅ DataFrame created successfully!
Total rows: 110088

--- Sample of the final DataFrame ---

,gameweek,contestant_no,prize_pool,manager,entry_num,total_points,prize,player_name,points,position,is_captin,is_vice
0,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Sanchez,2.0,,False,False
1,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Veltman,1.0,,False,False
2,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Wan-Bissaka,12.0,,False,False
3,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Estupiñan,7.0,,False,False
4,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Mitoma,5.0,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
110083,38,256,"R 9,500.00",MJ23,2,26.0,,B.Fernandes,0.0,,True,False
110084,38,256,"R 9,500.00",MJ23,2,26.0,,Bailey,0.0,,False,False
110085,38,256,"R 9,500.00",MJ23,2,26.0,,Haaland,3.0,,False,True
110086,38,256,"R 9,500.00",MJ23,2,26.0,,Darwin,1.0,,False,False
110087,38,256,"R 9,500.00",MJ23,2,26.0,,Højlund,7.0,,False,False

In [19]:
fpl_players_df = pd.read_csv('../with new features/data/vaastav/data/2023-24/players_raw.csv')
fgo_names = fgo_df['player_name'].unique().tolist()
fpl_web_names = fpl_players_df['web_name'].unique().tolist()

In [20]:
fpl_cleaned = pd.read_csv('../with new features/data/joint/23-24/merged_player_data.csv')
# fpl_cleaned.columns

In [21]:
# confirm names in fgo match those in fpl_web_names
match_df =[]
for name in fgo_names:
    if name in fpl_web_names:
        match_df.append({'name': name, 'has_match': True})
    else:
        match_df.append({'name': name, 'has_match': False})
match_df = pd.DataFrame(match_df)

match_df[~match_df['has_match']]['name'].to_list()

['Vinicius', 'Mitooma', 'Bradely', 'N.Semendo', 'De Bryune', 'Isak.']

In [22]:
fgo_missing_names_dict = {
    'Vinicius': 'Vinícius' ,
    'Mitooma': 'Mitoma',
    'Bradely': 'Bradley',
    'N.Semendo': 'N.Semedo',
    'De Bryune': 'De Bruyne',
    'Isak.': 'Isak'
}

# fpl_players_df.set_index('web_name')['fpl_name']

In [23]:
# Use .map() to look up corrected names and .fillna() to keep original names that weren't in the dict.
fgo_df['player_name'] = fgo_df['player_name'].map(fgo_missing_names_dict).fillna(fgo_df['player_name'])

# Map: web_name -> element_type
position_map = fpl_players_df.set_index('web_name')['element_type'].to_dict()

# Map: web_name -> id
id_map = fpl_players_df.set_index('web_name')['id'].to_dict()

# This looks up each corrected player_name in your new dictionaries.
fgo_df['position'] = fgo_df['player_name'].map(position_map)
fgo_df['fpl_id'] = fgo_df['player_name'].map(id_map)

fgo_df.loc[fgo_df['fpl_id'] == 862, 'fpl_id'] = 204

In [24]:
# 1. Calculate the number of managers for each gameweek
# This calculates the size of each group and divides by 11
manager_counts = fgo_df.groupby('gameweek')['gameweek'].transform('size') / 11
fgo_df['managers'] = manager_counts

# 2. Calculate the ownership counts for each player within each gameweek
ownership_counts = fgo_df.groupby(['gameweek', 'player_name'])['player_name'].transform('size')
fgo_df['owned_by'] = ownership_counts

# 3. Calculate the ownership percentage in one go
# We need to get the manager count for each group to divide by
# manager_counts_for_calc = fgo_df.groupby(['gameweek', 'player_name'])['managers'].first()
ownership_percentage = round((fgo_df['owned_by']  / fgo_df['managers']) * 100, 2)
fgo_df['ownership_percent'] = ownership_percentage

fgo_df

,gameweek,contestant_no,prize_pool,manager,entry_num,total_points,prize,player_name,points,position,is_captin,is_vice,fpl_id,managers,owned_by,ownership_percent
0,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Sanchez,2.0,1,False,False,145,66.0,1,1.52
1,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Veltman,1.0,2,False,False,151,66.0,9,13.64
2,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Wan-Bissaka,12.0,2,False,False,401,66.0,7,10.61
3,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Estupiñan,7.0,2,False,False,131,66.0,32,48.48
4,1,175,"R 8,180.18",Radynster,1,81.5,"R 5,596.88",Mitoma,5.0,3,False,False,143,66.0,16,24.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110083,38,256,"R 9,500.00",MJ23,2,26.0,,B.Fernandes,0.0,3,True,False,373,256.0,33,12.89
110084,38,256,"R 9,500.00",MJ23,2,26.0,,Bailey,0.0,3,False,False,34,256.0,6,2.34
110085,38,256,"R 9,500.00",MJ23,2,26.0,,Haaland,3.0,4,False,True,355,256.0,177,69.14
110086,38,256,"R 9,500.00",MJ23,2,26.0,,Darwin,1.0,4,False,False,293,256.0,4,1.56
110087,38,256,"R 9,500.00",MJ23,2,26.0,,Højlund,7.0,4,False,False,617,256.0,6,2.34

## Combine with FPL merged data

In [45]:
fpl_23_24 = pd.read_csv('../with new features/data/joint/23-24/merged_player_data.csv')
players_preds_36 = pd.read_csv('../with new features/models/preds/players_preds_36.csv')
players_preds_37 = pd.read_csv('../with new features/models/preds/players_preds_37.csv')
players_preds_38 = pd.read_csv('../with new features/models/preds/players_preds_38.csv')
# fpl_23_24[['event', 'fpl_id', 'ownership_percent']]

In [46]:
# Select only the necessary columns
ownership_lookup = fgo_df[['gameweek', 'fpl_id', 'player_name','ownership_percent', 'points']].copy()

# Ensure 'gameweek' is numeric
ownership_lookup['gameweek'] = pd.to_numeric(ownership_lookup['gameweek'])

ownership_lookup

        gameweek  fpl_id  player_name  ownership_percent  points
0              1     145      Sanchez               1.52     2.0
1              1     151      Veltman              13.64     1.0
2              1     401  Wan-Bissaka              10.61    12.0
3              1     131    Estupiñan              48.48     7.0
4              1     143       Mitoma              24.24     5.0
...          ...     ...          ...                ...     ...
110083        38     373  B.Fernandes              12.89     0.0
110084        38      34       Bailey               2.34     0.0
110085        38     355      Haaland              69.14     3.0
110086        38     293       Darwin               1.56     1.0
110087        38     617      Højlund               2.34     7.0

[110088 rows x 5 columns]

In [47]:
# Drop duplicate entries to have one row per player per gameweek
ownership_lookup.drop_duplicates(subset=['gameweek', 'fpl_id'], inplace=True)
ownership_lookup = ownership_lookup.rename(columns={'gameweek':'event'})
ownership_lookup

        event  fpl_id  player_name  ownership_percent  points
0           1     145      Sanchez               1.52     2.0
1           1     151      Veltman              13.64     1.0
2           1     401  Wan-Bissaka              10.61    12.0
3           1     131    Estupiñan              48.48     7.0
4           1     143       Mitoma              24.24     5.0
...       ...     ...          ...                ...     ...
109935     38     544        Zouma               0.39     1.0
110025     38     545    Aït-Nouri               0.39     1.0
110033     38     299    Henderson               0.39     6.0
110036     38      70        Kelly               0.39     1.0
110080     38     350        Rúben               0.39     2.0

[5892 rows x 5 columns]

In [48]:
missing_ids = set(set(ownership_lookup['fpl_id'].unique()) - set(fpl_23_24['fpl_id'].unique()))
len(missing_ids)

# Get the player names for missing ids
missing_players = ownership_lookup[ownership_lookup['fpl_id'].isin(missing_ids)].drop_duplicates(subset=['fpl_id'])
missing_players[['fpl_id', 'player_name']]

       fpl_id  player_name
6         505     Ndombele
33        498      Forster
627       323        Macey
704       299    Henderson
711        35      Buendia
714       443       Dennis
3408      207       Lukaku
5962      502       Lloris
30624     384       Heaton
30634     717      Stutter
31416     448    Hennessey
31801     646         Hein
32482     720  Ola-Adebomi
35748     399    Shoretire
36300     284        Rodák
38744     835          Mee
49887      32  Alex Moreno
56639     669        Vítek
72230     736      Walters
78961       7      Holding

In [49]:
# Merge on both 'gameweek' and 'fpl_id' to ensure correct matching
final_df = pd.merge(
    fpl_23_24,
    ownership_lookup,
    on=['event', 'fpl_id'],  # Use a list for multiple merge keys
    how='left'               # Use 'left' to keep all rows from merged_player_df
)

# Merge on both 'gameweek' and 'fpl_id' to ensure correct matching
preds_36 = pd.merge(
    players_preds_36,
    ownership_lookup,
    on=['event', 'fpl_id'],  # Use a list for multiple merge keys
    how='left'               # Use 'left' to keep all rows from merged_player_df
)

preds_37 = pd.merge(
    players_preds_37,
    ownership_lookup,
    on=['event', 'fpl_id'],  # Use a list for multiple merge keys
    how='left'               # Use 'left' to keep all rows from merged_player_df
)

preds_38 = pd.merge(
    players_preds_38,
    ownership_lookup,
    on=['event', 'fpl_id'],  # Use a list for multiple merge keys
    how='left'               # Use 'left' to keep all rows from merged_player_df
)


final_df['ownership_percent'] = final_df['ownership_percent'].fillna(0)
preds_36['ownership_percent'] = preds_36['ownership_percent'].fillna(0)
preds_37['ownership_percent'] = preds_37['ownership_percent'].fillna(0)
preds_38['ownership_percent'] = preds_38['ownership_percent'].fillna(0)

In [50]:
final_df.to_csv('./fantasyGo_FPL.csv')
preds_36.to_csv('./fantasyGo_preds_36.csv')
preds_37.to_csv('./fantasyGo_preds_37.csv')
preds_38.to_csv('./fantasyGo_preds_38.csv')

In [51]:
final_df[['total_points', 'points']]

       total_points  points
0                 0     NaN
1                 0     NaN
2                 0     NaN
3                 0     NaN
4                 0     NaN
...             ...     ...
11787             2     NaN
11788             9    11.0
11789             6     6.0
11790             2     2.0
11791             3     3.0

[11792 rows x 2 columns]

In [52]:
import pandas as pd
m = pd.read_csv('./fgo_managers.csv')
m

,gameweek,contestant_no,prize_pool,manager,entry,points,prize,pick
0,1,175,"R 8,180.18",Radynster,1,81.5 Points,"R 5,596.88","[{'player_name': 'Sanchez', 'points': '2', 'po..."
1,1,175,"R 8,180.18",paradise-prince,2,79.5 Points,"R 1,721.93","[{'player_name': 'Steele', 'points': '2', 'pos..."
2,1,175,"R 8,180.18",KloppinSquad 2.0,1,77.5 Points,R 430.69,"[{'player_name': 'Steele', 'points': '2', 'pos..."
3,1,175,"R 8,180.18",zbongo,1,77.5 Points,R 430.69,"[{'player_name': 'Forster', 'points': '0', 'po..."
4,1,175,"R 8,180.18",jacquesmieny,1,76 Points,R 25.00,"[{'player_name': 'Onana', 'points': '9', 'posi..."
...,...,...,...,...,...,...,...,...
10008,38,256,"R 9,500.00",enricocelento,1,34.5 Points,NaN,"[{'player_name': 'Henderson', 'points': '6', '..."
10009,38,256,"R 9,500.00",Mr.2,3,34.5 Points,NaN,"[{'player_name': 'Vicario', 'points': '6', 'po..."
10010,38,256,"R 9,500.00",Sundowns,9,32 Points,NaN,"[{'player_name': 'Ortega Moreno', 'points': '2..."
10011,38,256,"R 9,500.00",itu,4,29 Points,NaN,"[{'player_name': 'Leno', 'points': '2', 'posit..."
10012,38,256,"R 9,500.00",MJ23,2,26 Points,NaN,"[{'player_name': 'Martinez', 'points': '0', 'p..."

In [53]:
m[m['gameweek'] == 36]

,gameweek,contestant_no,prize_pool,manager,entry,points,prize,pick
9285,36,229,"R 9,500.00",maxreich,1,124 Points,"R 3,890.25","[{'player_name': 'Raya', 'points': '6', 'posit..."
9286,36,229,"R 9,500.00",CR7FC,10,115.5 Points,"R 1,396.50","[{'player_name': 'Flekken', 'points': '10', 'p..."
9287,36,229,"R 9,500.00",jacquesmieny,2,115.5 Points,"R 1,396.50","[{'player_name': 'Petrović', 'points': '6', 'p..."
9288,36,229,"R 9,500.00",chiefmatt,2,113.5 Points,R 522.50,"[{'player_name': 'Sels', 'points': '3', 'posit..."
9289,36,229,"R 9,500.00",justincredibles,2,112.5 Points,R 399.00,"[{'player_name': 'Flekken', 'points': '10', 'p..."
...,...,...,...,...,...,...,...,...
9509,36,229,"R 9,500.00",mo_carrim,2,39.5 Points,NaN,"[{'player_name': 'Sels', 'points': '3', 'posit..."
9510,36,229,"R 9,500.00",DokotelaVuyo,2,39 Points,NaN,"[{'player_name': 'Ortega Moreno', 'points': '0..."
9511,36,229,"R 9,500.00",Nico Celento,4,35 Points,NaN,"[{'player_name': 'Kaminski', 'points': '3', 'p..."
9512,36,229,"R 9,500.00",ialreadywonbruv,5,34 Points,NaN,"[{'player_name': 'Dubravka', 'points': '3', 'p..."
9513,36,229,"R 9,500.00",Mr.2,2,31 Points,NaN,"[{'player_name': 'Pickford', 'points': '3', 'p..."