In [ ]:
# 1. Scrap the old versions to avoid conflicts
!apt-get remove google-chrome-stable chromium-browser chromium-chromedriver

# 2. Install necessary system dependencies
!apt-get update
!apt-get install -y wget xvfb unzip
!apt-get install -y libnss3 libgconf-2-4 libfontconfig1 libgbm1

# 3. Download and install a verified Chromium version
!wget https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.85/linux64/chrome-linux64.zip
!wget https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.85/linux64/chromedriver-linux64.zip

# 4. Unzip them
!unzip chrome-linux64.zip
!unzip chromedriver-linux64.zip

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package google-chrome-stable
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,089 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unzip is already the newest version (6.0-26ubuntu3.2).
wget is already the newest version (1.21.2-2ubuntu1.1).
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.16).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.2).
libnss3 set to manually installed.
The following additional packages will be installed:
  gconf-service gconf-service-backend gconf2-common libdbus-glib-1-2
The following NEW packages will be installed:
  gconf-service gconf-service-backend gconf2-common libdbus-glib-1-2
  libgconf-2-4
0 upgraded, 5 newly installed, 0 to remove and 35 not upgraded.
Need to get 926 kB of archives.
After this operation, 8,309 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdbus-glib-1-2 amd64 0.112-2build1 [65.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 gconf2-common all 3.2.6-7ubuntu2 [698 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgconf-2-4 amd64 3.2.6-7ubuntu2 [86.0 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 gconf-service-backend amd64 3.2.6-7ubuntu2 [59.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 gconf-service amd64 3.2.6-7ubuntu2 [17.4 kB]
Fetched 926 kB in 2s (446 kB/s)
Selecting previously unselected package libdbus-glib-1-2:amd64.
(Reading database ... 118003 files and directories currently installed.)
Preparing to unpack .../libdbus-glib-1-2_0.112-2build1_amd64.deb ...
Unpacking libdbus-glib-1-2:amd64 (0.112-2build1) ...
Selecting previously unselected package gconf2-common.
Preparing to unpack .../gconf2-common_3.2.6-7ubuntu2_all.deb ...
Unpacking gconf2-common (3.2.6-7ubuntu2) ...
Selecting previously unselected package libgconf-2-4:amd64.
Preparing to unpack .../libgconf-2-4_3.2.6-7ubuntu2_amd64.deb ...
Unpacking libgconf-2-4:amd64 (3.2.6-7ubuntu2) ...
Selecting previously unselected package gconf-service-backend.
Preparing to unpack .../gconf-service-backend_3.2.6-7ubuntu2_amd64.deb ...
Unpacking gconf-service-backend (3.2.6-7ubuntu2) ...
Selecting previously unselected package gconf-service.
Preparing to unpack .../gconf-service_3.2.6-7ubuntu2_amd64.deb ...
Unpacking gconf-service (3.2.6-7ubuntu2) ...
Setting up gconf2-common (3.2.6-7ubuntu2) ...

Creating config file /etc/gconf/2/path with new version
Setting up libdbus-glib-1-2:amd64 (0.112-2build1) ...
Setting up libgconf-2-4:amd64 (3.2.6-7ubuntu2) ...
Setting up gconf-service (3.2.6-7ubuntu2) ...
Setting up gconf-service-backend (3.2.6-7ubuntu2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

--2026-01-31 15:45:46--  https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.85/linux64/chrome-linux64.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.10.207, 142.251.12.207, 64.233.170.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.10.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149587479 (143M) [application/zip]
Saving to: ‘chrome-linux64.zip’

chrome-linux64.zip   96%[==================> ] 138.30M  23.4MB/s    eta 1s

In [3]:
# Install chromium, its driver, and selenium
!apt-get update
!apt-get install -y chromium-browser
!apt install -y chromium-chromedriver
!pip install selenium parsel webdriver_manager

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,085 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-browser is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (4.40.0)
Requirement already satisfied: parsel in /usr/local/lib/python3.12/dist-packages (1.11.0)
Collecting webdriver_manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.1.4)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.32.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: trio-typing>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (0.10.0)
Requirement already satisfied: types-certifi>=2021.10.8.3 in /usr/local/lib/python3.12/dist-packages (from selenium) (2021.10.8.3)
Requirement already satisfied: types-urllib3>=1.26.25.14 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.26.25.14)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: cssselect>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from parsel) (1.4.0)
Requirement already satisfied: jmespath>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from parsel) (1.1.0)
Requirement already satisfied: lxml>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from parsel) (6.0.2)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from parsel) (25.0)
Requirement already satisfied: w3lib>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from parsel) (2.4.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver_manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver_manager) (1.2.1)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: mypy-extensions>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from trio-typing>=0.10.0->selenium) (1.1.0)
Requirement already satisfied: async-generator in /usr/local/lib/python3.12/dist-packages (from trio-typing>=0.10.0->selenium) (1.10)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from trio-typing>=0.10.0->selenium) (8.7.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver_manager) (3.4.4)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->trio-typing>=0.10.0->selenium) (3.23.0)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver_manager
Successfully installed webdriver_manager-4.0.2

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

from parsel import Selector
from time import sleep
import pandas as pd
import numpy as np

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.action_chains import ActionChains

from selenium.common.exceptions import NoSuchWindowException
from selenium.common.exceptions import StaleElementReferenceException

import time
import re


# driver_path = r"C:\Users\burio\Downloads\chromedriver-win64 (3)\chromedriver-win64\chromedriver.exe"
# s = Service('/usr/bin/chromedriver')
# driver = webdriver.Chrome(service=s)

In [5]:
# Setup Chrome Options
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

# Explicitly set the binary location if the system can't find it
chrome_options.binary_location = "/usr/bin/chromium-browser"

# Initialize the driver without hardcoding the service path
# (The system path usually handles this now)
driver = webdriver.Chrome(options=chrome_options)

# Verification
driver.get("https://www.google.com")
print("Connection Successful! Title:", driver.title)

SessionNotCreatedException: Message: session not created: Chrome instance exited. Examine ChromeDriver verbose log to determine the cause.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#sessionnotcreatedexception
Stacktrace:
#0 0x59c6e07e9f1a <unknown>
#1 0x59c6e01fe922 <unknown>
#2 0x59c6e023c48b <unknown>
#3 0x59c6e0237159 <unknown>
#4 0x59c6e0288b16 <unknown>
#5 0x59c6e02881fc <unknown>
#6 0x59c6e0245adf <unknown>
#7 0x59c6e02468a1 <unknown>
#8 0x59c6e07af119 <unknown>
#9 0x59c6e07b2021 <unknown>
#10 0x59c6e079c069 <unknown>
#11 0x59c6e07b2bde <unknown>
#12 0x59c6e07824f0 <unknown>
#13 0x59c6e07d6aa8 <unknown>
#14 0x59c6e07d6c78 <unknown>
#15 0x59c6e07e8563 <unknown>
#16 0x794d88767ac3 <unknown>

In [ ]:
# driver_path = r"C:\Users\burio\Downloads\chromedriver-win64 (3)\chromedriver-win64\chromedriver.exe"
# s = Service('/usr/bin/chromedriver')
# driver = webdriver.Chrome(service=s)

# chrome_options = Options()
# chrome_options.add_argument("--headless")        # Required
# chrome_options.add_argument("--no-sandbox")
# chrome_options.add_argument("--disable-dev-shm-usage")
# chrome_options.add_argument("--window-size=1920,1080")

# service = Service("/usr/bin/chromedriver")
# driver = webdriver.Chrome(service=service, options=chrome_options)

WebDriverException: Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1

In [ ]:
gw = 23

# William Hill Odds

In [ ]:
driver.get('https://sports.williamhill.com/betting/en-gb/football/competitions/OB_TY295/English-Premier-League/matches/OB_MGMB/Match-Betting')

In [ ]:
sel = Selector(text = driver.page_source)

match_links = sel.xpath('//*[starts-with(@class, "sp-o-market__more")]/a/@href')

# Extract the urls from the Selector object
unique_match_links = ['https://sports.williamhill.com'+i.get() for i in match_links]

unique_match_links

['https://sports.williamhill.com/betting/en-gb/football/OB_EV38317142/west-ham-vs-sunderland',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317143/burnley-vs-tottenham',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317148/fulham-vs-brighton',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317149/man-city-vs-wolves',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317158/bournemouth-vs-liverpool',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317157/brentford-vs-nottingham-forest',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317159/crystal-palace-vs-chelsea',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317193/newcastle-vs-aston-villa',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317194/arsenal-vs-man-utd',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38317203/everton-vs-leeds',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410159/brighton-vs-everton',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410156/leeds-vs-arsenal',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410157/wolves-vs-bournemouth',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410160/chelsea-vs-west-ham',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410158/liverpool-vs-newcastle',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410163/aston-villa-vs-brentford',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410162/man-utd-vs-fulham',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410161/nottingham-forest-vs-crystal-palace',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410165/tottenham-vs-man-city',
 'https://sports.williamhill.com/betting/en-gb/football/OB_EV38410164/sunderland-vs-burnley']

In [ ]:
# Function for extracting
def get_full_xpath(element):
    components = []
    child = element
    while child.tag_name != "html":
        parent = child.find_element(By.XPATH, "..")
        siblings = parent.find_elements(By.XPATH, "*")
        same_tag_siblings = [sib for sib in siblings if sib.tag_name == child.tag_name]

        # Attempt to use a more stable identifier if available
        data_id = child.get_attribute("data-id")
        if data_id:
            position = f"[@data-id='{data_id}']"
        elif len(same_tag_siblings) > 1:
            index = same_tag_siblings.index(child) + 1
            position = f"[{index}]"
        else:
            position = ''

        components.append(f"{child.tag_name}{position}")
        child = parent

    components.append("html")
    components.reverse()
    return '/' + '/'.join(components)

In [ ]:
# Function to determine if a scoreline is a draw
def is_draw(scoreline):
    home_goals, away_goals = map(int, scoreline.split('-'))
    return home_goals == away_goals

In [ ]:
team_xG_list= []

In [ ]:
appended_data = []

In [ ]:
#driver.back()

In [ ]:
for i in range(10):
    driver.get(unique_match_links[i])

    sleep(3)
    # grab the webpage
    sel2 = Selector(text = driver.page_source)
# /html/body/div[7]/div[1]/div/div/div[6]/div/div/main/div[2]/div[1]/div/div/div/div[2]/div/h1
    contest = sel2.xpath('//*[starts-with(@class, "css-1e7nc0h")]/text()').extract()
    teams = contest[0].split(" v ")

    player_name = sel2.xpath('//*[starts-with(@class, "cpt-goalscorer__title")]/h3/text()').extract()
    anytime = sel2.xpath('//li[starts-with(@class, "odds-market-2")]/button/@data-odds')
    two_or_more = sel2.xpath('//li[starts-with(@class, "odds-market-4")]/button/@data-odds')
    hatrick = sel2.xpath('//li[starts-with(@class, "odds-market-5")]/button/@data-odds')

    anytime_odds = [i.get() for i in anytime]
    two_or_more = [i.get() for i in two_or_more]
    hatrick = [i.get() for i in hatrick]

    player_name= player_name[:-1]

    print(contest[0])
    mid_index = len(player_name) // 2   # integer division
    # del vec[mid_index]
    print(len(player_name),len(anytime_odds), len(hatrick), len(two_or_more))

    wh = pd.DataFrame({'home_team': teams[0], 'away_team': teams[1],'player_name':player_name[:mid_index], 'anytime_odds':anytime_odds[:mid_index], 'two_or_more':two_or_more[:mid_index], 'hatrick':hatrick[:mid_index] })

    appended_data.append(wh)

    ###########################################################
    # Team xG
    ##############################################################
    target_text = "Correct Score"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons = driver.find_elements(By.XPATH, target_buttons_xpath)
    matches = []
    # HOME DATA
    for button in target_buttons:
        full_xpath = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
    #     pattern = r"container\[(\d+)\]"div[12]/section
        pattern = r"div\[(\d+)\]/section"
        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath)

        # Print extracted numbers
        for match in matches:
            xG_index = match

#         init_path = '//sx-pricing-page//sx-p-panel-container['+ str(xG_index)
#         #                sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[4]/div/sc-panel/div/div/div[2]/header/div/div[1]/span
#         target_xpath_pattern = init_path

#     /html/body/div[7]/div[1]/div/div/div[6]/div/div/main/div[2]/div[11]/div/div/div[12]/section/header/h2
    scoreline_links = sel2.xpath('//div['+ xG_index + ']/section/div/div/div/div[starts-with(@class, "btmarket__selection")]/button/@data-name')
    scoreline_odds_links = sel2.xpath('//div['+ xG_index + ']/section/div/div/div/div[starts-with(@class, "btmarket__selection")]/button/@data-odds')

    scoreline = [i.get() for i in scoreline_links]
    scoreline_odds = [i.get() for i in scoreline_odds_links]

    xG_df = pd.DataFrame({'scoreline':scoreline,'scoreline_odds':scoreline_odds, 'contest': contest[0]})

    # Determine the outcome based on whether the scoreline represents a draw
    xG_df['Outcome'] = xG_df['scoreline'].apply(lambda x: 'draw' if is_draw(x) else 'undetermined')

    # Now, identify the draw scorelines to separate the wins and losses
    draw_indices = xG_df.index[xG_df['Outcome'] == 'draw'].tolist()

    # The first non-draw scoreline after the draw section is where the away_team wins start
    away_team_start_index = draw_indices[-1] + 1 if draw_indices else len(xG_df)

    # Categorize outcomes based on the index
    xG_df['Outcome'] = xG_df.index.to_series().apply(lambda x: teams[0]+' Win' if x < draw_indices[0] else
                                               teams[1]+' Win' if x >= away_team_start_index else
                                               'Draw')
    team_xG_list.append(xG_df)

West Ham v Sunderland
85 84 84 84
Burnley v Tottenham
103 102 102 102
Fulham v Brighton
85 84 84 84
Man City v Wolves
83 82 82 82
Bournemouth v Liverpool
85 84 84 84
Brentford v Nottingham Forest
85 84 84 84
Crystal Palace v Chelsea
85 84 84 84
Newcastle v Aston Villa
79 78 78 78
Arsenal v Man Utd
89 88 88 88
Everton v Leeds
85 84 84 84

In [ ]:
appended_data2 = pd.concat(appended_data)
appended_data2

   home_team   away_team         player_name anytime_odds two_or_more hatrick
0   West Ham  Sunderland        Pablo Felipe         11/5        60/1     9/2
1   West Ham  Sunderland       Callum Wilson        19/10        50/1     9/2
2   West Ham  Sunderland    Taty Castellanos          5/2        80/1    11/2
3   West Ham  Sunderland        Jarrod Bowen         13/5        80/1     6/1
4   West Ham  Sunderland       Lucas Paqueta         16/5       100/1    13/2
..       ...         ...                 ...          ...         ...     ...
37   Everton       Leeds  Sebastiaan Bornauw         10/1       250/1    20/1
38   Everton       Leeds        Ethan Ampadu         11/1       400/1    22/1
39   Everton       Leeds        Jayden Bogle         11/1       300/1    22/1
40   Everton       Leeds          Ilia Gruev         12/1       300/1    25/1
41   Everton       Leeds           Sam Byram         16/1       400/1    35/1

[427 rows x 6 columns]

In [ ]:
appended_data2 = pd.concat(appended_data)
appended_data2

   home_team   away_team         player_name anytime_odds two_or_more hatrick
0   West Ham  Sunderland        Pablo Felipe         11/5        60/1     9/2
1   West Ham  Sunderland       Callum Wilson        19/10        50/1     9/2
2   West Ham  Sunderland    Taty Castellanos          5/2        80/1    11/2
3   West Ham  Sunderland        Jarrod Bowen         13/5        80/1     6/1
4   West Ham  Sunderland       Lucas Paqueta         16/5       100/1    13/2
..       ...         ...                 ...          ...         ...     ...
37   Everton       Leeds  Sebastiaan Bornauw         10/1       250/1    20/1
38   Everton       Leeds        Ethan Ampadu         11/1       400/1    22/1
39   Everton       Leeds        Jayden Bogle         11/1       300/1    22/1
40   Everton       Leeds          Ilia Gruev         12/1       300/1    25/1
41   Everton       Leeds           Sam Byram         16/1       400/1    35/1

[427 rows x 6 columns]

In [ ]:
xG_data = pd.concat(team_xG_list)
xG_data

   scoreline scoreline_odds                contest       Outcome
0        1-0            7/1  West Ham v Sunderland  West Ham Win
1        2-0           11/1  West Ham v Sunderland  West Ham Win
2        2-1           15/2  West Ham v Sunderland  West Ham Win
3        3-0           22/1  West Ham v Sunderland  West Ham Win
4        3-1           20/1  West Ham v Sunderland  West Ham Win
..       ...            ...                    ...           ...
41       6-2          150/1        Everton v Leeds     Leeds Win
42       7-0          150/1        Everton v Leeds     Leeds Win
43       7-1          150/1        Everton v Leeds     Leeds Win
44       8-0          150/1        Everton v Leeds     Leeds Win
45       9-0          150/1        Everton v Leeds     Leeds Win

[461 rows x 4 columns]

In [ ]:
# Player to score odds
prefix ="C:/Users/burio/Downloads/FPL2026/williamHill/scorer/gw"
# prefix = "williamHill/gw"

file_name =  prefix + str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/williamHill/scorer/gw23.csv'

In [ ]:
appended_data2.to_csv(file_name, index = False)# encoding = 'utf-8'

In [ ]:
#Team xG
prefix = "C:/Users/burio/Downloads/FPL2026/williamHill/team_xG/gw"
file_name =  prefix + str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/williamHill/team_xG/gw23.csv'

In [ ]:
xG_data.to_csv(file_name, index = False)# encoding = 'utf-8'

# fixed Odds

In [ ]:
driver.get('https://www.sportingindex.com/spread-betting/football/uk-domestic-premier-league')
# driver.get('https://www.sportingindex.com/sports/en-GB/spread-betting/football/league/47/spr/c57')
# driver.get('https://www.sportingindex.com/sports/en-GB/spread-betting/football/premier-league/bournemouth-v-luton/fo/p3166000')

In [ ]:
# After clicking the buttons, find buttons with the specified text
target_text = "Fixed Odds"

# XPath selector for buttons with the target text
target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'

# Find all buttons with the target text
target_buttons = driver.find_elements(By.XPATH, target_buttons_xpath)

# Print or interact with the found buttons
try:
    # Wait up to 10 seconds for the button to be clickable
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))

    # Scroll the element into view
    ActionChains(driver).move_to_element(target_buttons[0]).perform()

    # Click the button using JavaScript
    driver.execute_script("arguments[0].click();", target_buttons[0])

    # Optional: Wait for a moment
    time.sleep(3)

except TimeoutException:
    print(f"Timeout waiting for the Fixed Odds button to be clickable.")

In [ ]:
sel3 = Selector(text = driver.page_source)

contest = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[1]/span/text()').extract()

# Pattern to match (for example, strings that contain 'a')
pattern = re.compile(r' v ')

# Filter the list, keeping only strings that match the pattern
contest_list = [s for s in contest if pattern.search(s)]
contest_list

['West Ham v Sunderland',
 'Burnley v Tottenham',
 'Fulham v Brighton',
 'Man City v Wolves',
 'Bournemouth v Liverpool',
 'Brentford v Nottingham Forest',
 'Crystal Palace v Chelsea',
 'Newcastle v Aston Villa',
 'Arsenal v Man Utd',
 'Everton v Leeds',
 'Brighton v Everton',
 'Leeds v Arsenal',
 'Wolves v Bournemouth',
 'Chelsea v West Ham',
 'Liverpool v Newcastle',
 'Aston Villa v Brentford',
 'Man Utd v Fulham',
 'Nottingham Forest v Crystal Palace',
 'Tottenham v Man City',
 'Sunderland v Burnley']

In [ ]:
# del contest_list[18]

In [ ]:
#home = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[2]/div[1]/sx-fo-price-button/sx-fo-price-button-v/div/div/div/text()').extract()
home = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[2]/div[1]/sx-fo-price-button/sx-fo-price-button-new/div/div/div/text()').extract()
draw = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[2]/div[2]/sx-fo-price-button/sx-fo-price-button-new/div/div/div/text()').extract()
away = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[2]/div[3]/sx-fo-price-button/sx-fo-price-button-new/div/div/div/text()').extract()

In [ ]:
match_up_df = pd.DataFrame({"contest": contest_list, "home": home, "draw": draw, "away": away})
match_up_df

                               contest     home     draw     away
0                West Ham v Sunderland   31/20     11/5    19/10
1                  Burnley v Tottenham    13/5      5/2    21/20
2                    Fulham v Brighton   31/20      5/2    17/10
3                    Man City v Wolves     1/5     13/2     12/1
4              Bournemouth v Liverpool    14/5    29/10    10/11
5        Brentford v Nottingham Forest   10/11      5/2      3/1
6             Crystal Palace v Chelsea     5/2    27/10      Evs
7              Newcastle v Aston Villa     Evs     13/5     13/5
8                    Arsenal v Man Utd     4/7      3/1      5/1
9                      Everton v Leeds     6/4     11/5    19/10
10                  Brighton v Everton     4/5    27/10     10/3
11                     Leeds v Arsenal     5/1     16/5      1/2
12                Wolves v Bournemouth   21/10     13/5    23/20
13                  Chelsea v West Ham     4/9     18/5     11/2
14               Liverpool v Newcastle     4/5      3/1    29/10
15             Aston Villa v Brentford     Evs      5/2      5/2
16                    Man Utd v Fulham    8/13     16/5     15/4
17  Nottingham Forest v Crystal Palace     Evs     12/5     13/5
18                Tottenham v Man City    10/3      3/1     7/10
19                Sunderland v Burnley     3/4     12/5     15/4

In [ ]:
match_up_df2 = match_up_df[:10]
match_up_df2

                         contest     home     draw     away
0          West Ham v Sunderland   31/20     11/5    19/10
1            Burnley v Tottenham    13/5      5/2    21/20
2              Fulham v Brighton   31/20      5/2    17/10
3              Man City v Wolves     1/5     13/2     12/1
4        Bournemouth v Liverpool    14/5    29/10    10/11
5  Brentford v Nottingham Forest   10/11      5/2      3/1
6       Crystal Palace v Chelsea     5/2    27/10      Evs
7        Newcastle v Aston Villa     Evs     13/5     13/5
8              Arsenal v Man Utd     4/7      3/1      5/1
9                Everton v Leeds     6/4     11/5    19/10

In [ ]:
prefix = "C:/Users/burio/Downloads/FPL2026/fixedSporting/game_outcome/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/fixedSporting/game_outcome/gw23.csv'

In [ ]:
match_up_df.to_csv(file_name, index = False)

In [ ]:
no_games = len(contest_list)
button_xpath = ("/html/body/app/div/main/sx-content/div/div[3]/div[3]/sx-sh-grouped/sc-panel/div/div[2]/content/sx-coupon-panel-container/"
                f"sx-coupon-panel[1]/sc-panel/div/div[2]/content/sx-coupon-panel-item[position() <= {no_games}]/div/div[1]/span")

In [ ]:
contest_list

['West Ham v Sunderland',
 'Burnley v Tottenham',
 'Fulham v Brighton',
 'Man City v Wolves',
 'Bournemouth v Liverpool',
 'Brentford v Nottingham Forest',
 'Crystal Palace v Chelsea',
 'Newcastle v Aston Villa',
 'Arsenal v Man Utd',
 'Everton v Leeds',
 'Brighton v Everton',
 'Leeds v Arsenal',
 'Wolves v Bournemouth',
 'Chelsea v West Ham',
 'Liverpool v Newcastle',
 'Aston Villa v Brentford',
 'Man Utd v Fulham',
 'Nottingham Forest v Crystal Palace',
 'Tottenham v Man City',
 'Sunderland v Burnley']

In [ ]:
# Function for extracting
def get_full_xpath(element):
    components = []
    child = element
    while child.tag_name != "html":
        parent = child.find_element(By.XPATH, "..")
        siblings = parent.find_elements(By.XPATH, "*")
        same_tag_siblings = [sib for sib in siblings if sib.tag_name == child.tag_name]

        # Attempt to use a more stable identifier if available
        data_id = child.get_attribute("data-id")
        if data_id:
            position = f"[@data-id='{data_id}']"
        elif len(same_tag_siblings) > 1:
            index = same_tag_siblings.index(child) + 1
            position = f"[{index}]"
        else:
            position = ''

        components.append(f"{child.tag_name}{position}")
        child = parent

    components.append("html")
    components.reverse()
    return '/' + '/'.join(components)

In [ ]:
scorer_df_list = []
assists_df_list = []
cards_df_list = []

In [ ]:
driver.back()

In [ ]:
button_elements = driver.find_elements(By.XPATH, button_xpath)
max_retries = 3
for  i in range(4,10):#len(button_elements)
    print('On: '+contest_list[i])
    retries = 0
    while retries < max_retries:
        try:
            # Re-find the elements to handle staleness
            button_elements = WebDriverWait(driver, 10).until(
                EC.presence_of_all_elements_located((By.XPATH, button_xpath))
            )

            # Click the element
            button_elements[i].click()

            # Optional: Wait for a moment
            time.sleep(3)

            break  # Exit the loop if click is successful

        except StaleElementReferenceException:
            print("Element reference is stale. Retrying...")
            retries += 1

    if retries == max_retries:
        print(f"Failed to click button at index {i} after {max_retries} retries.")

    time.sleep(3)
    #driver.get('https://www.sportingindex.com/sports/en-GB/spread-betting/football/premier-league/aston-villa-v-liverpool/spr/p3818123')
#     ############################################################
#     #scorer click
#     ############################################################

    # After clicking the buttons, find buttons with the specified text
    target_text = "Goalscorer Markets"

    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'

    # Find all buttons with the target text
    target_buttons = driver.find_elements(By.XPATH, target_buttons_xpath)

    # Print or interact with the found buttons
#    for j in range(1):
#       try:
#            # Wait up to 10 seconds for the button to be clickable
#            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
#
#            # Scroll the element into view
#            ActionChains(driver).move_to_element(target_buttons[j]).perform()
#
#            # Click the button using JavaScript
#            driver.execute_script("arguments[0].click();", target_buttons[j])
#
#            # Optional: Wait for a moment
#            time.sleep(3)
#
#        except TimeoutException:
#            print(f"Timeout waiting for the button to be clickable.")
    time.sleep(3)
    ############################################################
    #card click
    ############################################################

        # After clicking the buttons, find buttons with the specified text
    target_text = "Card Markets"

    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'

    # Find all buttons with the target text
    target_buttons3 = driver.find_elements(By.XPATH, target_buttons_xpath)

        # Print or interact with the found buttons
    for j in range(1):
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))

            # Scroll the element into view
            ActionChains(driver).move_to_element(target_buttons3[j]).perform()

            # Click the button using JavaScript
            driver.execute_script("arguments[0].click();", target_buttons3[j])

            # Optional: Wait for a moment
            time.sleep(3)

        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")
    time.sleep(3)
    ###########################################################
#     assit click
    ###########################################################

    # After clicking the buttons, find buttons with the specified text
    target_text2 = "Player Assists"

    # XPath selector for buttons with the target text
    target_buttons_xpath2 = f'//*[contains(text(), "{target_text2}")]'

    # Get all matching elements, waiting for them to exist
    target_buttons2 = WebDriverWait(driver, 10).until(
        EC.presence_of_all_elements_located((By.XPATH, target_buttons_xpath2))
    )

    # Optionally filter just to visible + enabled ones
    target_buttons2 = [
        el for el in target_buttons2
        if el.is_displayed() and el.is_enabled()
    ]

    for j, button in enumerate(target_buttons2):
        print(f"Button {j}:", button.tag_name, button.location, button.size)

        # Scroll into view first
        driver.execute_script(
            "arguments[0].scrollIntoView({block: 'center'});",
            button
        )

        # Extra: wait until THIS button is interactable
        WebDriverWait(driver, 10).until(
            lambda d: button.is_displayed() and button.is_enabled()
        )

        # Now move & click
        ActionChains(driver).move_to_element(button).perform()

        # Use JS click as a fallback
        driver.execute_script("arguments[0].click();", button)

    ###########################################################
    #see more click
    ############################################################

        # After clicking the buttons, find buttons with the specified text
    target_text2 = "more markets"

    see_more_buttons_xpath2 = (
        f"//*[contains(normalize-space(text()), '{target_text2}')]"
    )


    # Find all buttons with the target text
    see_more_buttons2 = driver.find_elements(By.XPATH, see_more_buttons_xpath2)
    see_more_buttons2 = driver.find_elements(By.XPATH, see_more_buttons_xpath2)

            # Print or interact with the found buttons

    for j in range(len(see_more_buttons2)):
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, see_more_buttons_xpath2)))

            # Scroll the element into view
            ActionChains(driver).move_to_element(see_more_buttons2[j]).perform()

            # Click the button using JavaScript
            driver.execute_script("arguments[0].click();", see_more_buttons2[j])

            # Optional: Wait for a moment
            time.sleep(3)

        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")
 ############################################################
    #scorer MARKETS
    ############################################################
    # HOME DATA
    # Assuming you have identified your elements as follows
    target_buttons = driver.find_elements(By.XPATH,'//*[contains(text(), "Goalscorer Markets")]')

    for button in target_buttons:
        full_xpath = get_full_xpath(button)

    # Regular expression pattern to find "container[<number>]"
    pattern = r"container\[(\d+)\]"

    # Search for all occurrences and extract numbers
    matches = re.findall(pattern, full_xpath)

    # Print extracted numbers
    for match in matches:
        scorer_index = match
#         print("Extracted number:", match)

#     shift_no = 3
#     scorer_index = 14+shift_no
# #     shift_no = -1
    init_path = '//sx-pricing-page//sx-p-panel-container['+ str(scorer_index)
    target_xpath_pattern = init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[1]/sx-p-panel-link-name/div/span'
#     sx-p-panel-container[18]/div/sc-panel/div/div[2]/content/sx-p-panel-fixed-odds/div/sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[1]/sx-p-panel-link-name/div/span
# /html/body/app/div/main/sx-content/div/div[3]/div[3]/sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[14]/div/sc-panel/div/div[2]/content/sx-p-panel-fixed-odds/div/sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[1]/sx-p-panel-link-name/div/span
    time.sleep(3)

    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            scorer_names = [target_element.text for target_element in target_elements]

            # Click the element
            1/len(scorer_names)


            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("scorer names not Found. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)

#     del scorer_names[5]
     # first score
    target_xpath_pattern = init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[2]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    first_score = [target_element.text for target_element in target_elements]

     # anytime score
    target_xpath_pattern = init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[3]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    anytime_score = [target_element.text for target_element in target_elements]

     # anytime score
    target_xpath_pattern = init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[4]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    last_score = [target_element.text for target_element in target_elements]

    # 2 or more goals
    target_xpath_pattern = init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[5]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    two_plus = [target_element.text for target_element in target_elements]

    # hatrick score
    target_xpath_pattern = init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[6]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    hatrick = [target_element.text for target_element in target_elements]

    # del scorer_names[30]
    scorer_df = pd.DataFrame({"player names": scorer_names[:-1], "first score": first_score[:-1], "anytime score": anytime_score, "last score": last_score,"two or more": two_plus,"hatrick": hatrick})
    scorer_df['contest'] = contest_list[i]
    scorer_df_list.append(scorer_df)
    print('Done with Scorers')
    ##########################################################
    #card MARKETS
    ############################################################
    # HOME DATA
    # Assuming you have identified your elements as follows
#     target_buttons = driver.find_elements(By.XPATH,'//*[contains(text(), "Goalscorer Markets")]')

    for button in target_buttons3:
        full_xpath = get_full_xpath(button)

    # Regular expression pattern to find "container[<number>]"
    pattern = r"container\[(\d+)\]"

    # Search for all occurrences and extract numbers
    matches = re.findall(pattern, full_xpath)

    # Print extracted numbers
    for match in matches:
        card_index = match

#     card_index = 17+shift_no
    card_init_path = '//sx-pricing-page//sx-p-panel-container['+ str(card_index)
    target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[1]/sx-p-panel-link-name/div/span'
#    sx-p-panel-container[21]/div/sc-panel/div/div[2]/content/sx-p-panel-fixed-odds/div/sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[1]/sx-p-panel-link-name/div/span
    time.sleep(3)

    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            card_names = [target_element.text for target_element in target_elements]

            # Click the element
            1/len(card_names)


            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("Zero names Found. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)

     # first
    target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[2]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
#                                             sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[2]/div/sx-fo-price-button/sx-fo-price-button-v/div/div/div
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    first_card = [target_element.text for target_element in target_elements]
    first_card
     # anytime
    target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[3]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
#                                             sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[2]/div/sx-fo-price-button/sx-fo-price-button-v/div/div/div
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    anytime_card = [target_element.text for target_element in target_elements]
    anytime_card
    # red card
    target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[4]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    red_card = [target_element.text for target_element in target_elements]

    '''del card_names[0]
    del first_card[0]
    del anytime_card[0]

    del card_names[13]
    del first_card[13]
    del anytime_card[13]

    del card_names[24]
    del first_card[33]
    del anytime_card[33]'''
    cards_df = pd.DataFrame({"player names": card_names[:-1],'first card': first_card[:-1], "anytime card": anytime_card,"red_card": red_card})
    cards_df['contest'] = contest_list[i]
    cards_df_list.append(cards_df)
    print('Done with cards')

   ##########################################################
    #assist MARKETS
    ############################################################
    # we use the detected button elements to extract the xpath and then from it extract the container number
    for button in target_buttons2:
        full_xpath = get_full_xpath(button)

    # Regular expression pattern to find "container[<number>]"
    pattern = r"container\[(\d+)\]"

    # Search for all occurrences and extract numbers
    matches = re.findall(pattern, full_xpath)

    # Print extracted numbers
    for match in matches:
        assist_index = match

#     assist_index = 51+shift_no #52
    assist_init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index)
    target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[1]/div/div[*]/div/div/sx-p-panel-link-name/div/span'
    time.sleep(3)

    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            assist_names = [target_element.text for target_element in target_elements]

            # Click the element
            1/len(assist_names)


            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("Zero names Found. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)

     # 1 or more assists
    target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[1]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'

    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    one_plus = [target_element.text for target_element in target_elements]
    one_plus
    # 2 or more assists
    target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[2]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    two_plus = [target_element.text for target_element in target_elements]

    desired_length = len(one_plus)

    # Calculate how many None values need to be added
    none_to_add = desired_length - len(two_plus)

    # Extend the list with None, if needed
    if none_to_add > 0:
        two_plus.extend([None] * none_to_add)

    assist_df = pd.DataFrame({"player names": assist_names, "one plus ": one_plus,"two plus": two_plus})
    assist_df['contest'] = contest_list[i]
    assists_df_list.append(assist_df)
    print('Done with assists')

    driver.back()
    time.sleep(3)
#     driver.back()

On: Bournemouth v Liverpool
Timeout waiting for the button to be clickable.
Button 0: span {'x': 215, 'y': 788} {'height': 16, 'width': 179}
Button 1: span {'x': 254, 'y': 2742} {'height': 31, 'width': 111}
Done with Scorers
Done with cards
Done with assists
On: Brentford v Nottingham Forest
Button 0: span {'x': 215, 'y': 849} {'height': 16, 'width': 213}
Button 1: span {'x': 254, 'y': 3039} {'height': 31, 'width': 111}
Done with Scorers
Done with cards
Done with assists
On: Crystal Palace v Chelsea
Button 0: span {'x': 215, 'y': 943} {'height': 16, 'width': 170}
Button 1: span {'x': 254, 'y': 3072} {'height': 31, 'width': 111}
Done with Scorers
Done with cards
Done with assists
On: Newcastle v Aston Villa
Button 0: span {'x': 215, 'y': 849} {'height': 16, 'width': 202}
Button 1: span {'x': 254, 'y': 3072} {'height': 31, 'width': 111}
Done with Scorers
Done with cards
Done with assists
On: Arsenal v Man Utd
Timeout waiting for the button to be clickable.
Button 0: span {'x': 215, 'y': 914} {'height': 16, 'width': 205}
Button 1: span {'x': 254, 'y': 2681} {'height': 31, 'width': 111}
Done with Scorers
Done with cards
Done with assists
On: Everton v Leeds
Button 0: span {'x': 254, 'y': 2855} {'height': 31, 'width': 111}
Done with Scorers
Done with cards
Done with assists

In [ ]:
len(target_buttons2)

3

In [ ]:
driver.back()

In [ ]:
len(see_more_buttons2)

2

In [ ]:
# we use the detected button elements to extract the xpath and then from it extract the container number
for button in target_buttons2:
    full_xpath = get_full_xpath(button)

# Regular expression pattern to find "container[<number>]"
pattern = r"container\[(\d+)\]"

# Search for all occurrences and extract numbers
matches = re.findall(pattern, full_xpath)

# Print extracted numbers
for match in matches:
    assist_index = match

#     assist_index = 51+shift_no #52
assist_init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index)
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[1]/div/div[*]/div/div/sx-p-panel-link-name/div/span'
time.sleep(3)

retries = 0
while retries < max_retries:
    try:
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        assist_names = [target_element.text for target_element in target_elements]

        # Click the element
        1/len(assist_names)


        break  # Exit the loop if click is successful

    except ZeroDivisionError:
        print("Zero names Found. Retrying...")
        retries += 1
        # Optional: Wait for a moment
        time.sleep(3)

 # 1 or more assists
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[1]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'

target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
one_plus = [target_element.text for target_element in target_elements]
one_plus
# 2 or more assists
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[2]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
two_plus = [target_element.text for target_element in target_elements]

desired_length = len(one_plus)

# Calculate how many None values need to be added
none_to_add = desired_length - len(two_plus)

# Extend the list with None, if needed
if none_to_add > 0:
    two_plus.extend([None] * none_to_add)

assist_df = pd.DataFrame({"player names": assist_names, "one plus ": one_plus,"two plus": two_plus})
assist_df['contest'] = contest_list[i]
assists_df_list.append(assist_df)
print('Done with assists')

StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=143.0.7499.41); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff68573a235
	0x7ff685492630
	0x7ff6852216dd
	0x7ff6852294c8
	0x7ff68522c52f
	0x7ff68522c5ef
	0x7ff6852741ab
	0x7ff6852a2b0a
	0x7ff68526cc36
	0x7ff6852cbaba
	0x7ff68526b0ed
	0x7ff68526bf63
	0x7ff685765d60
	0x7ff68575fe8a
	0x7ff685781005
	0x7ff6854ad71e
	0x7ff6854b4e1f
	0x7ff68549b7c4
	0x7ff68549b97f
	0x7ff6854818e8
	0x7ffe0ceee8d7
	0x7ffe0ea2c53c

In [ ]:

del scorer_names[30]
'''del anytime_score[29]
del last_score[28]
del two_plus[28]
del hatrick[18]'''

#del scorer_names[len(scorer_names)-1]
scorer_df = pd.DataFrame({"player names": scorer_names[:-1], "first score": first_score[:-1], "anytime score": anytime_score, "last score": last_score,"two or more": two_plus,"hatrick": hatrick})
scorer_df['contest'] = contest_list[i]
scorer_df_list.append(scorer_df)
print('Done with Scorers')
##########################################################
#card MARKETS
############################################################
# HOME DATA
# Assuming you have identified your elements as follows
#     target_buttons = driver.find_elements(By.XPATH,'//*[contains(text(), "Goalscorer Markets")]')

for button in target_buttons3:
    full_xpath = get_full_xpath(button)

# Regular expression pattern to find "container[<number>]"
pattern = r"container\[(\d+)\]"

# Search for all occurrences and extract numbers
matches = re.findall(pattern, full_xpath)

# Print extracted numbers
for match in matches:
    card_index = match

#     card_index = 17+shift_no
card_init_path = '//sx-pricing-page//sx-p-panel-container['+ str(card_index)
target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[1]/sx-p-panel-link-name/div/span'
#    sx-p-panel-container[21]/div/sc-panel/div/div[2]/content/sx-p-panel-fixed-odds/div/sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[1]/sx-p-panel-link-name/div/span
time.sleep(3)

retries = 0
while retries < max_retries:
    try:
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        card_names = [target_element.text for target_element in target_elements]

        # Click the element
        1/len(card_names)


        break  # Exit the loop if click is successful

    except ZeroDivisionError:
        print("Zero names Found. Retrying...")
        retries += 1
        # Optional: Wait for a moment
        time.sleep(3)

 # first
target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[2]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
#                                             sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[2]/div/sx-fo-price-button/sx-fo-price-button-v/div/div/div
target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
first_card = [target_element.text for target_element in target_elements]
first_card
 # anytime
target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[3]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
#                                             sx-p-panel-fixed-odds-grid[1]/div/div[2]/div[2]/div/sx-fo-price-button/sx-fo-price-button-v/div/div/div
target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
anytime_card = [target_element.text for target_element in target_elements]
anytime_card
# red card
target_xpath_pattern = card_init_path + ']//sx-p-panel-fixed-odds-grid[*]/div/div[*]/div[4]/div/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
red_card = [target_element.text for target_element in target_elements]

del card_names[1]
del first_card[1]
del anytime_card[1]


del card_names[33]
del first_card[33]
del anytime_card[33]
'''
del card_names[13]
del first_card[13]
del anytime_card[13]
del card_names[21]
del card_names[30]
del card_names[31]
del card_names[35]'''
cards_df = pd.DataFrame({"player names": card_names[:-1],'first card': first_card[:-1], "anytime card": anytime_card,"red_card": red_card})
cards_df['contest'] = contest_list[i]
cards_df_list.append(cards_df)
print('Done with cards')

##########################################################
#assist MARKETS
############################################################
# we use the detected button elements to extract the xpath and then from it extract the container number
for button in target_buttons2:
    full_xpath = get_full_xpath(button)

# Regular expression pattern to find "container[<number>]"
pattern = r"container\[(\d+)\]"

# Search for all occurrences and extract numbers
matches = re.findall(pattern, full_xpath)

# Print extracted numbers
for match in matches:
    assist_index = match

#     assist_index = 51+shift_no #52
assist_init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index)
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[1]/div/div[*]/div/div/sx-p-panel-link-name/div/span'
time.sleep(3)

retries = 0
while retries < max_retries:
    try:
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        assist_names = [target_element.text for target_element in target_elements]

        # Click the element
        1/len(assist_names)


        break  # Exit the loop if click is successful

    except ZeroDivisionError:
        print("Zero names Found. Retrying...")
        retries += 1
        # Optional: Wait for a moment
        time.sleep(3)

 # 1 or more assists
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[1]/sx-fo-price-button/sx-fo-price-button-c/div/div/div'

target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
one_plus = [target_element.text for target_element in target_elements]
one_plus
# 2 or more assists
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[2]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
two_plus = [target_element.text for target_element in target_elements]

desired_length = len(one_plus)

# Calculate how many None values need to be added
none_to_add = desired_length - len(two_plus)

# Extend the list with None, if needed
if none_to_add > 0:
    two_plus.extend([None] * none_to_add)

assist_df = pd.DataFrame({"player names": assist_names, "one plus ": one_plus,"two plus": two_plus})
assist_df['contest'] = contest_list[i]
assists_df_list.append(assist_df)
print('Done with assists')

driver.back()
time.sleep(3)
#     driver.back()

Done with Scorers

IndexError: list assignment index out of range

In [ ]:
len(card_names)
card_names[31]

'Samuel Chukwueze'

In [ ]:
del first_card[4]
del anytime_card[4]
del card_names[4]
# del red_card[16]
del first_card[13]
del anytime_card[13]
del card_names[13]

del first_card[29]
del anytime_card[29]
del card_names[29]

'''del first_card[2]
del anytime_card[2]
del card_names[2]
del first_card[12]
del anytime_card[12]'''
'''scorer_df = pd.DataFrame({"player names": scorer_names[:-1], "first score": first_score[:-1], "anytime score": anytime_score, "last score": last_score,"two or more": two_plus,"hatrick": hatrick})
scorer_df['contest'] = contest_list[i]
scorer_df_list.append(scorer_df)
print('Done with Scorers') '''
cards_df = pd.DataFrame({"player names": card_names[:-1],'first card': first_card[:-1], "anytime card": anytime_card,"red_card": red_card})
cards_df['contest'] = contest_list[i]
cards_df_list.append(cards_df)
print('Done with cards')

##########################################################
#assist MARKETS
############################################################
# we use the detected button elements to extract the xpath and then from it extract the container number
for button in target_buttons2:
    full_xpath = get_full_xpath(button)

# Regular expression pattern to find "container[<number>]"
pattern = r"container\[(\d+)\]"

# Search for all occurrences and extract numbers
matches = re.findall(pattern, full_xpath)

# Print extracted numbers
for match in matches:
    assist_index = match

#     assist_index = 51+shift_no #52
assist_init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index)
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[1]/div/div[*]/div/div/sx-p-panel-link-name/div/span'
time.sleep(3)

retries = 0
while retries < max_retries:
    try:
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        assist_names = [target_element.text for target_element in target_elements]

        # Click the element
        1/len(assist_names)


        break  # Exit the loop if click is successful

    except ZeroDivisionError:
        print("Zero names Found. Retrying...")
        retries += 1
        # Optional: Wait for a moment
        time.sleep(3)

 # 1 or more assists
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[1]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'

target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
one_plus = [target_element.text for target_element in target_elements]
one_plus
# 2 or more assists
target_xpath_pattern = assist_init_path + ']//sx-p-panel-fixed-odds-player-special[*]/div/div[2]/div/div[2]/div[*]/div[2]/sx-fo-price-button/sx-fo-price-button-new/div/div/div'
target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
two_plus = [target_element.text for target_element in target_elements]

desired_length = len(one_plus)

# Calculate how many None values need to be added
none_to_add = desired_length - len(two_plus)

# Extend the list with None, if needed
if none_to_add > 0:
    two_plus.extend([None] * none_to_add)

assist_df = pd.DataFrame({"player names": assist_names, "one plus ": one_plus,"two plus": two_plus})
assist_df['contest'] = contest_list[i]
assists_df_list.append(assist_df)
print('Done with assists')

driver.back()
time.sleep(3)

Done with cards

InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=143.0.7499.41)
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff68573a235
	0x7ff685492630
	0x7ff6852216dd
	0x7ff68520d205
	0x7ff685232a8a
	0x7ff6852aa476
	0x7ff6852cb3d2
	0x7ff68526b0ed
	0x7ff68526bf63
	0x7ff685765d60
	0x7ff68575fe8a
	0x7ff685781005
	0x7ff6854ad71e
	0x7ff6854b4e1f
	0x7ff68549b7c4
	0x7ff68549b97f
	0x7ff6854818e8
	0x7ffe0ceee8d7
	0x7ffe0ea2c53c

In [ ]:
final_score_df = pd.concat(scorer_df_list, ignore_index=True)
final_score_df

,player names,first score,anytime score,last score,two or more,hatrick,contest
0,Jarrod Bowen,6/1,23/10,7/1,14/1,50/1,West Ham v Sunderland
1,Taty Castellanos,6/1,9/4,13/2,14/1,50/1,West Ham v Sunderland
2,Callum Wilson,6/1,21/10,6/1,12/1,50/1,West Ham v Sunderland
3,Pablo,17/2,16/5,17/2,20/1,80/1,West Ham v Sunderland
4,Lucas Paqueta,11/1,4/1,11/1,28/1,100/1,West Ham v Sunderland
...,...,...,...,...,...,...,...
342,James Justin,25/1,12/1,25/1,100/1,500/1,Everton v Leeds
343,Joe Rodon,25/1,12/1,25/1,100/1,500/1,Everton v Leeds
344,Ilia Gruev,25/1,12/1,25/1,100/1,500/1,Everton v Leeds
345,Gabriel Gudmondsson,25/1,12/1,25/1,100/1,500/1,Everton v Leeds
346,Ethan Ampadu,33/1,14/1,33/1,150/1,500/1,Everton v Leeds

In [ ]:
final_cards_df = pd.concat(cards_df_list, ignore_index=True)
final_cards_df

,player names,first card,anytime card,red_card,contest
0,Lucas Paqueta,8/1,2/1,28/1,West Ham v Sunderland
1,Soungoutou Magassa,9/1,23/10,28/1,West Ham v Sunderland
2,Guido Rodriguez,10/1,13/5,33/1,West Ham v Sunderland
3,Mateus Fernandes,10/1,14/5,33/1,West Ham v Sunderland
4,Taty Castellanos,11/1,3/1,33/1,West Ham v Sunderland
...,...,...,...,...,...
356,Lucas Perri,18/1,6/1,50/1,Everton v Leeds
357,Joel Piroe,22/1,7/1,50/1,Everton v Leeds
358,Noah Okafor,20/1,13/2,50/1,Everton v Leeds
359,Lukas Nmecha,22/1,13/2,50/1,Everton v Leeds
360,Karl Darlow,22/1,7/1,50/1,Everton v Leeds

In [ ]:
final_assists_df = pd.concat(assists_df_list, ignore_index=True)
final_assists_df

             player names one plus  two plus                contest
0            Jarrod Bowen      18/5     28/1  West Ham v Sunderland
1        Taty Castellanos      11/2     None  West Ham v Sunderland
2   Crysencio Summerville      11/2     None  West Ham v Sunderland
3        Mateus Fernandes      13/2     None  West Ham v Sunderland
4           Brian Brobbey       9/2     None  West Ham v Sunderland
..                    ...       ...      ...                    ...
80       Nathan Patterson       7/1     None        Everton v Leeds
81           Jayden Bogle      14/5     None        Everton v Leeds
82  Dominic Calvert-Lewin       4/1     None        Everton v Leeds
83            Noah Okafor      19/4     None        Everton v Leeds
84       Brenden Aaronson       5/1     None        Everton v Leeds

[85 rows x 4 columns]

In [ ]:
prefix = "C:/Users/burio/Downloads/FPL2026/fixedSporting/cards/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/fixedSporting/cards/gw23.csv'

In [ ]:
final_cards_df.to_csv(file_name, index = False)# encoding = 'utf-8'

In [ ]:
prefix = "C:/Users/burio/Downloads/FPL2026/fixedSporting/scorer/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/fixedSporting/scorer/gw23.csv'

In [ ]:
final_score_df.to_csv(file_name, index = False)

In [ ]:
prefix = "C:/Users/burio/Downloads/FPL2026/fixedSporting/assist/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/fixedSporting/assist/gw23.csv'

In [ ]:
final_assists_df.to_csv(file_name, index = False)

In [ ]:
# Define the odds with the corresponding scores for each team and draws
west_ham_odds_extended_with_scores = [
    (1, 0, 16), (2, 0, 35), (2, 1, 18), (3, 0, 90), (3, 1, 55), (3, 2, 55), (4, 0, 200),
    (4, 1, 125), (4, 2, 125), (4, 3, 150), (5, 0, 250), (5, 1, 250), (5, 2, 200),
    (6, 0, 250), (6, 1, 250), (7, 0, 250), (8, 0, 250)
]

arsenal_odds_extended_with_scores = [
    (0, 1, 7), (0, 2, 13/2), (1, 2, 15/2), (0, 3, 11), (1, 3, 12), (2, 3, 25),
    (0, 4, 22), (1, 4, 45), (2, 4, 100), (0, 5, 50), (1, 5, 50), (2, 5, 90),
    (0, 6, 100), (1, 6, 100), (0, 7, 200), (0, 8, 250)
]

draw_odds_extended_with_scores = [
    (0, 0, 14), (1, 1, 15/2), (2, 2, 16), (3, 3, 70), (4, 4, 200)
]

# Convert odds to probabilities while accounting for the scores
def convert_odds_with_scores(odds_with_scores):
    probabilities_with_scores = []
    for home_score, away_score, odds in odds_with_scores:
        probability = 1 / (odds + 1)  # Convert odds to probability
        probabilities_with_scores.append((home_score, away_score, probability))
    return probabilities_with_scores

# Apply the conversion to all sets of odds
west_ham_probabilities_with_scores = convert_odds_with_scores(west_ham_odds_extended_with_scores)
arsenal_probabilities_with_scores = convert_odds_with_scores(arsenal_odds_extended_with_scores)
draw_probabilities_with_scores = convert_odds_with_scores(draw_odds_extended_with_scores)

# Calculate the total implied probability for normalization
total_implied_probability = sum(prob for _, _, prob in west_ham_probabilities_with_scores) + \
                            sum(prob for _, _, prob in arsenal_probabilities_with_scores) + \
                            sum(prob for _, _, prob in draw_probabilities_with_scores)

# Normalize the probabilities
west_ham_normalized_probs = [(home_score, away_score, prob / total_implied_probability)
                             for home_score, away_score, prob in west_ham_probabilities_with_scores]
arsenal_normalized_probs = [(home_score, away_score, prob / total_implied_probability)
                            for home_score, away_score, prob in arsenal_probabilities_with_scores]
draw_normalized_probs = [(home_score, away_score, prob / total_implied_probability)
                         for home_score, away_score, prob in draw_probabilities_with_scores]

# Aggregate the probabilities for each number of goals scored by each team
west_ham_goals_probs = {}
arsenal_goals_probs = {}

# Aggregate probabilities from all possible outcomes
for home_score, away_score, prob in west_ham_normalized_probs + draw_normalized_probs:
    west_ham_goals_probs[home_score] = west_ham_goals_probs.get(home_score, 0) + prob
    arsenal_goals_probs[away_score] = arsenal_goals_probs.get(away_score, 0) + prob

for home_score, away_score, prob in arsenal_normalized_probs:
    west_ham_goals_probs[home_score] = west_ham_goals_probs.get(home_score, 0) + prob
    arsenal_goals_probs[away_score] = arsenal_goals_probs.get(away_score, 0) + prob

# Calculate the expected goals for each team
expected_goals_west_ham = sum(score * prob for score, prob in west_ham_goals_probs.items())
expected_goals_arsenal = sum(score * prob for score, prob in arsenal_goals_probs.items())

expected_goals_west_ham, expected_goals_arsenal

(1.0572660278064892, 1.9666226510551146)

In [ ]:
this was the flowed by the fidffet stuff who is the main guy on this panel we'll be going all out this weekind for this kind of enjoyment who says otherwise!!