In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By

from parsel import Selector
from time import sleep
import pandas as pd
import numpy as np

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.action_chains import ActionChains

from selenium.common.exceptions import NoSuchWindowException
from selenium.common.exceptions import StaleElementReferenceException

import time
import re

ModuleNotFoundError: No module named 'webdriver_manager'

In [65]:
#driver_path = r"C:\Users\Guest_user\Downloads\chromedriver-win64\chromedriver-win64\chromedriver.exe"
driver_path = r"C:\Users\burio\Downloads\chromedriver-win64 (3)\chromedriver-win64\chromedriver.exe"

s = Service(driver_path)
driver = webdriver.Chrome(service=s)

In [66]:
gw = 23

# OddShark

In [7]:
driver.get('https://www.oddsshark.com/soccer/epl')

In [249]:
sel = Selector(text = driver.page_source)

In [ ]:
# function to get unique values
def unique(list1):

    # initialize a null list
    unique_list = []

    # traverse for all elements
    for x in list1:
        # check if exists in unique_list or not
        if x not in unique_list:
            unique_list.append(x)
    # print list
    return(unique_list)

In [226]:
# Get all the match day urls
# match_links = sel.xpath('//*[@id="oddsshark-upcoming-events"]/div/div/div[2]/ul/li/div/a/')
# match_links = sel.xpath('//*[@id="oddsshark-upcoming-events"]/div/div/div[2]/ul/li/div/a[contains(@href, "/soccer/epl/")]/@href').getall()
match_links = sel.xpath('//*[@id="oddsshark-ticker"]/div/div/div[2]/div/div/div/div/a[contains(@href, "/soccer/epl/")]/@href').getall()

# retain unique urls from each pair
# unique_match_links = unique([i.get() for i in match_links])

# add the prefix
full_links = ['https://www.oddsshark.com' + i for i in match_links]
full_links

[]

In [222]:
len(full_links)

0

In [18]:
full_links2 = full_links[1]

In [20]:
full_links2

'https://www.oddsshark.com/soccer/epl/crystal-palace-bournemouth-odds-october-18-2025-2403504'

In [26]:
rows_list = []

In [ ]:
for i in full_links[7:]:
    # to get urls for respective matches
    driver.get(i)

    sleep(2)

    # grab the webpage
    sel2 = Selector(text = driver.page_source)

    # Extract the names for the teams playing
#     teams = sel2.xpath('//*[starts-with(@class, "gc-team-info__text--primary")]/text()').extract()
    home_team = sel2.xpath('//*[starts-with(@class, "gc-both-home-name")]/text()').extract()[0]
    away_team = sel2.xpath('//*[starts-with(@class, "gc-both-away-name")]/text()').extract()[0]

    print(home_team+' v '+ away_team)

    # Extract the historic performance data
#     form = sel2.xpath('//*[starts-with(@class, "gc-team-info__text--secondary")]/text()').extract()
    away_perfomance = sel2.xpath('//*[starts-with(@class, "gc-both-away-subtitle-one")]/text()').extract()[0]
    away_form =  sel2.xpath('//*[starts-with(@class, "gc-both-away-subtitle-two")]/text()').extract()[0]

    home_perfomance = sel2.xpath('//*[starts-with(@class, "gc-both-home-subtitle-one")]/text()').extract()[0]
    home_form = sel2.xpath('//*[starts-with(@class, "gc-both-home-subtitle-two")]/text()').extract()[0]

    # Extract the predicted scores
    home_score = sel2.xpath('//*[starts-with(@class, "gc-score__num gc-score__num--left")]/div/text()').extract_first()
    away_score = sel2.xpath('//*[starts-with(@class, "gc-score__num gc-score__num--right")]/div/text()').extract_first()

    # store all the collected match data into a dictionary
    dict1 = {'home_team': home_team, 'away_team':away_team,'home_score':home_score,'away_score':away_score,'home_form':home_form, 'away_form':away_form, 'home_perfomance':home_perfomance, 'away_perfomance':away_perfomance}
    rows_list.append(dict1)

    sleep(2)

Aston Villa v Manchester City
Bournemouth v Nottingham
Everton v Tottenham

In [29]:
away_form  = home_form  =None

In [31]:
away_form =  sel2.xpath('//*[starts-with(@class, "gc-both-away-subtitle-two")]/text()').extract()[0]
away_form

' L-W-L-D-L-W'

In [38]:
df = pd.DataFrame(rows_list)
df

,home_team,away_team,home_score,away_score,home_form,away_form,home_perfomance,away_perfomance
0,Newcastle,Fulham,2.1,0.8,L-W-L-D-W-D,L-L-L-W-W-L,2 - 3 - 3,2 - 2 - 4
1,Newcastle,Fulham,2.1,0.8,L-W-L-D-W-D,L-L-L-W-W-L,2 - 3 - 3,2 - 2 - 4
2,Chelsea,Sunderland,1.6,1.4,W-W-L-L-D-W,W-L-W-D-D-W,4 - 2 - 2,4 - 2 - 2
3,Manchester United,Brighton & Hove Albion,1.0,2.0,W-W-L-W-L-W,W-D-W-D-L-W,4 - 1 - 3,3 - 3 - 2
4,Brentford,Liverpool,0.7,2.4,W-L-W-L-D-L,L-L-L-W-W-W,3 - 1 - 4,5 - 0 - 3
5,Wolves,Burnley,1.6,1.2,L-D-D-L-L-L,W-L-L-D-L-L,0 - 2 - 6,2 - 1 - 5
6,Arsenal,Crystal Palace,2.2,0.5,W-W-W-D-W-L,D-L-W-W-D-W,6 - 1 - 1,3 - 4 - 1
7,Wolves,Burnley,1.6,1.2,L-D-D-L-L-L,W-L-L-D-L-L,0 - 2 - 6,2 - 1 - 5
8,Arsenal,Crystal Palace,2.2,0.5,W-W-W-D-W-L,D-L-W-W-D-W,6 - 1 - 1,3 - 4 - 1
9,Aston Villa,Manchester City,1.2,1.8,W-W-W-D-D-L,W-W-W-D-W-L,3 - 3 - 2,5 - 1 - 2
10,Aston Villa,Manchester City,1.2,1.8,W-W-W-D-D-L,W-W-W-D-W-L,3 - 3 - 2,5 - 1 - 2
11,Bournemouth,Nottingham,1.4,1.5,D-W-D-D-W-W,L-L-L-D-L-L,4 - 3 - 1,1 - 2 - 5
12,Everton,Tottenham,0.8,2.2,L-W-D-L-D-W,L-W-D-D-W-L,3 - 2 - 3,4 - 2 - 2

In [28]:
df = pd.DataFrame(rows_list[1:10])
df

,home_team,away_team,home_score,away_score,home_form,away_form,home_perfomance,away_perfomance
0,Brentford,Manchester United,1.5,1.6,L-D-L-W-L,W-L-W-D-L,1 - 1 - 3,2 - 1 - 2
1,Leeds,Bournemouth,1.0,2.0,W-L-D-L-W,D-W-W-W-L,2 - 1 - 2,3 - 1 - 1
2,Chelsea,Brighton & Hove Albion,1.7,1.4,L-D-W-W-D,D-L-W-L-D,2 - 2 - 1,1 - 2 - 2
3,Manchester City,Burnley,2.7,0.4,D-W-L-L-W,D-L-L-W-L,2 - 1 - 2,1 - 1 - 3
4,Crystal Palace,Liverpool,0.5,2.5,W-D-W-D-D,W-W-W-W-W,2 - 3 - 0,5 - 0 - 0
5,Nottingham,Sunderland,1.4,1.6,D-L-L-D-W,D-D-W-L-W,1 - 2 - 2,2 - 2 - 1
6,Tottenham,Wolves,1.5,1.5,D-W-L-W-W,L-L-L-L-L,3 - 1 - 1,0 - 0 - 5
7,Aston Villa,Fulham,2.0,0.9,D-D-L-L-D,W-W-L-D-D,0 - 3 - 2,2 - 2 - 1
8,Newcastle,Arsenal,1.2,1.6,D-W-D-L-D,D-W-L-W-W,1 - 3 - 1,3 - 1 - 1
9,Everton,West Ham,1.4,1.4,L-D-W-W-L,L-L-W-L-L,2 - 1 - 2,1 - 0 - 4

In [40]:
prefix ="C:/Users/burio/Downloads/FPL2026/oddsShark/gw"
file_name =  prefix + str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/oddsShark/gw9.csv'

In [42]:
df.to_csv(file_name, index = False)# encoding = 'utf-8'

# Spread Odds

In [69]:
driver.get('https://www.sportingindex.com/spread-betting/football/uk-domestic-premier-league')
# driver.get('https://www.sportingindex.com/sports/en-GB/spread-betting/football/fa-cup/aston-villa-v-chelsea/spr/p3109335')

# Match-up spreads

In [74]:
sel3 = Selector(text = driver.page_source)

contest = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[1]/span/text()').extract()

# Pattern to match (for example, strings that contain 'a')
pattern = re.compile(r' v ')

# Filter the list, keeping only strings that match the pattern
contest_list = [s for s in contest if pattern.search(s)]
contest_list

['West Ham v Sunderland',
 'Burnley v Tottenham',
 'Fulham v Brighton',
 'Man City v Wolves',
 'Bournemouth v Liverpool',
 'Brentford v Nottingham Forest',
 'Crystal Palace v Chelsea',
 'Newcastle v Aston Villa',
 'Arsenal v Man Utd',
 'Everton v Leeds',
 'Brighton v Everton',
 'Leeds v Arsenal',
 'Wolves v Bournemouth',
 'Chelsea v West Ham',
 'Liverpool v Newcastle',
 'Aston Villa v Brentford',
 'Man Utd v Fulham',
 'Nottingham Forest v Crystal Palace',
 'Tottenham v Man City',
 'Sunderland v Burnley']

In [76]:
spreads = sel3.xpath('//*[@id="premier-league"]/div/div[2]/content/sx-coupon-panel-item[*]/div/div[3]/div/sx-spr-price-button/div/div/text()').extract()
spreads

[' 0.05 - 0.25 ',
 ' 0.35 - 0.55 ',
 ' -0.1 - 0.1 ',
 ' 1.85 - 2.05 ',
 ' 0.55 - 0.75 ',
 ' 0.5 - 0.7 ',
 ' 0.4 - 0.6 ',
 ' 0.35 - 0.55 ',
 ' 1 - 1.2 ',
 ' 0 - 0.2 ',
 ' 0.6 - 0.8 ',
 ' 1.05 - 1.25 ',
 ' 0.2 - 0.4 ',
 ' 1.2 - 1.4 ',
 ' 0.6 - 0.8 ',
 ' 0.35 - 0.55 ',
 ' 0.85 - 1.05 ',
 ' 0.35 - 0.55 ',
 ' 0.75 - 0.95 ',
 ' 0.65 - 0.85 ']

In [78]:
match_up_df = pd.DataFrame({"contest": contest_list, "spread": spreads})
match_up_df

                               contest         spread
0                West Ham v Sunderland   0.05 - 0.25
1                  Burnley v Tottenham   0.35 - 0.55
2                    Fulham v Brighton    -0.1 - 0.1
3                    Man City v Wolves   1.85 - 2.05
4              Bournemouth v Liverpool   0.55 - 0.75
5        Brentford v Nottingham Forest     0.5 - 0.7
6             Crystal Palace v Chelsea     0.4 - 0.6
7              Newcastle v Aston Villa   0.35 - 0.55
8                    Arsenal v Man Utd       1 - 1.2
9                      Everton v Leeds       0 - 0.2
10                  Brighton v Everton     0.6 - 0.8
11                     Leeds v Arsenal   1.05 - 1.25
12                Wolves v Bournemouth     0.2 - 0.4
13                  Chelsea v West Ham     1.2 - 1.4
14               Liverpool v Newcastle     0.6 - 0.8
15             Aston Villa v Brentford   0.35 - 0.55
16                    Man Utd v Fulham   0.85 - 1.05
17  Nottingham Forest v Crystal Palace   0.35 - 0.55
18                Tottenham v Man City   0.75 - 0.95
19                Sunderland v Burnley   0.65 - 0.85

In [80]:
match_up_df2 = match_up_df[:10]
match_up_df2

                         contest         spread
0          West Ham v Sunderland   0.05 - 0.25
1            Burnley v Tottenham   0.35 - 0.55
2              Fulham v Brighton    -0.1 - 0.1
3              Man City v Wolves   1.85 - 2.05
4        Bournemouth v Liverpool   0.55 - 0.75
5  Brentford v Nottingham Forest     0.5 - 0.7
6       Crystal Palace v Chelsea     0.4 - 0.6
7        Newcastle v Aston Villa   0.35 - 0.55
8              Arsenal v Man Utd       1 - 1.2
9                Everton v Leeds       0 - 0.2

In [82]:
#prefix = "~/Documents/FPL/FPL2024/sportingIndex/game_outcome/gw"
prefix ="C:/Users/burio/Downloads/FPL2026/sportingIndex/game_outcome/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/sportingIndex/game_outcome/gw23.csv'

In [84]:
match_up_df.to_csv(file_name, index = False)

# Goal scorer spread odds

In [87]:
contest_df_list = []
assists_df_list = []
assistsx10_df_list = []
cards_df_list = []
perfomance_df_list =[]

In [89]:
no_games = len(contest_list)
button_xpath = ("/html/body/app/div/main/sx-content/div/div[3]/div[3]/sx-sh-grouped/sc-panel/div/div[2]/content/sx-coupon-panel-container/"
                f"sx-coupon-panel[1]/sc-panel/div/div[2]/content/sx-coupon-panel-item[position() <= {no_games}]/div/div[1]/span")

In [ ]:
# Function for extracting
def get_full_xpath(element):
    components = []
    child = element
    while child.tag_name != "html":
        parent = child.find_element(By.XPATH, "..")
        siblings = parent.find_elements(By.XPATH, "*")
        same_tag_siblings = [sib for sib in siblings if sib.tag_name == child.tag_name]

        # Attempt to use a more stable identifier if available
        data_id = child.get_attribute("data-id")
        if data_id:
            position = f"[@data-id='{data_id}']"
        elif len(same_tag_siblings) > 1:
            index = same_tag_siblings.index(child) + 1
            position = f"[{index}]"
        else:
            position = ''

        components.append(f"{child.tag_name}{position}")
        child = parent

    components.append("html")
    components.reverse()
    return '/' + '/'.join(components)

In [93]:
contest_list

['West Ham v Sunderland',
 'Burnley v Tottenham',
 'Fulham v Brighton',
 'Man City v Wolves',
 'Bournemouth v Liverpool',
 'Brentford v Nottingham Forest',
 'Crystal Palace v Chelsea',
 'Newcastle v Aston Villa',
 'Arsenal v Man Utd',
 'Everton v Leeds',
 'Brighton v Everton',
 'Leeds v Arsenal',
 'Wolves v Bournemouth',
 'Chelsea v West Ham',
 'Liverpool v Newcastle',
 'Aston Villa v Brentford',
 'Man Utd v Fulham',
 'Nottingham Forest v Crystal Palace',
 'Tottenham v Man City',
 'Sunderland v Burnley']

In [676]:
# driver.back()

In [ ]:
button_elements = driver.find_elements(By.XPATH, button_xpath)
max_retries = 3
assist_index = 3

for i in range(3,10):
    print('On: '+contest_list[i])
    retries = 0
    while retries < max_retries:
        try:
            # Re-find the elements to handle staleness
            button_elements = WebDriverWait(driver, 10).until(
                EC.presence_of_all_elements_located((By.XPATH, button_xpath))
            )
            # Click the element
            button_elements[i].click()
            # Optional: Wait for a moment
            time.sleep(3)

            break  # Exit the loop if click is successful

        except StaleElementReferenceException:
            print("Element reference is stale. Retrying...")
            retries += 1
    if retries == max_retries:
        print(f"Failed to click button at index {i} after {max_retries} retries.")

    time.sleep(5)


    #     ############################################################
    #     #scorer click
    #     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Goal Minutes"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons1 = driver.find_elements(By.XPATH, target_buttons_xpath)

    for button in target_buttons1:
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
            # Scroll into view
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", button)

            # Try normal click first
            try:
                button.click()
            except Exception:
                # Fallback: JS click
                driver.execute_script("arguments[0].click();", button)
            # Optional: Wait for a moment
            time.sleep(3)
        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")


    #     ############################################################
    #     #PLAYERS click
    #     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Players"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons = driver.find_elements(By.XPATH, target_buttons_xpath)
    # Print or interact with the found buttons
    try:
        # Wait up to 10 seconds for the button to be clickable
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
        # Scroll the element into view
        ActionChains(driver).move_to_element(target_buttons[0]).perform()
        # Click the button using JavaScript
        driver.execute_script("arguments[0].click();", target_buttons[0])
        # Optional: Wait for a moment
        time.sleep(3)
    except TimeoutException:
        print(f"Timeout waiting for the button to be clickable.")


    ############################################################
    #Scorer Markets
    ############################################################
    time.sleep(4)
    matches = []

    for button in target_buttons1:
        full_xpath = get_full_xpath(button)
        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"
        # Search for all occurrences and extract numbers
        matches.append(re.findall(pattern, full_xpath))

    home_index = matches[0]
    away_index = matches[1]

    # HOME DATA
    init_path = '//sx-pricing-page//sx-p-panel-container['+ home_index[0]
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
    # /sc-panel/div/div[2]/content/sx-p-panel-spreads/div/div/sx-p-panel-spreads-column[1]/div/div[2]/div[2]/div/div/sx-p-panel-link-name/div/span
    # sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[1]/div/sc-panel/div/div[2]/content/sx-p-panel-spreads/div/div/sx-p-panel-spreads-column[1]/div/div[2]/div[2]/div/div/sx-p-panel-link-name/div/span
    # /html/body/app/div/main/sx-content/div/div[3]/div[3]/
    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            PGM_names = [target_element.text for target_element in target_elements]
            # Click the element
            1/len(PGM_names)

            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("Division by zero. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)


    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    PGM_odds = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_names = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_odds = [target_element.text for target_element in target_elements]

    home_df = pd.DataFrame({"PGM_names": PGM_names, "PGM_odds": PGM_odds,"SMM_names": SMM_names, "SMM_odds": SMM_odds})

    print('home PGM: '+ str(len(PGM_names)),'home SMM: '+ str(len(SMM_names)))

    # AWAY DATA
    # After clicking the initial buttons, find elements that match the specified XPath pattern
    init_path = '//sx-pricing-page//sx-p-panel-container['+ away_index[0]

    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'

    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            PGM_names = [target_element.text for target_element in target_elements]

            # Click the element
            1/len(PGM_names)

            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("Division by zero. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    PGM_odds = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_names = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_odds = [target_element.text for target_element in target_elements]

    print('away PGM: '+ str(len(PGM_names)),'away SMM: '+ str(len(SMM_names)))

    away_df = pd.DataFrame({"PGM_names": PGM_names, "PGM_odds": PGM_odds,"SMM_names": SMM_names, "SMM_odds": SMM_odds})

    contest_df = pd.concat([home_df, away_df], ignore_index=True)
    contest_df["contest"] = contest_list[i]

    contest_df_list.append(contest_df)

    print('Done with Scorers')


    #     ############################################################
    #     #Player Performance Points
    #     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Performance Points"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons4 = driver.find_elements(By.XPATH, target_buttons_xpath)

    matches = []
    # HOME DATA
    for button in target_buttons4:
        full_xpath = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"

        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath)

    if len(matches)!=0:
        # Print extracted numbers
        for match in matches:
            perfomance_index = match

        init_path = '//sx-pricing-page//sx-p-panel-container['+ str(perfomance_index)
        #                sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[4]/div/sc-panel/div/div/div[2]/header/div/div[1]/span
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
        retries = 0
        while retries < max_retries:
            try:
                # Find all elements that match the specified XPath pattern
                target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                # Extract and print information from all matching elements
                perfomance_names = [target_element.text for target_element in target_elements]

                # Click the element
                1/len(perfomance_names)

                break  # Exit the loop if click is successful

            except ZeroDivisionError:
                print("Zero names Found. Retrying...")
                retries += 1
                # Optional: Wait for a moment
                time.sleep(3)
        perfomance_names

        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        perfomance_odds = [target_element.text for target_element in target_elements]

        perfomance_df = pd.DataFrame({"perfomance_names": perfomance_names, "perfomance_odds": perfomance_odds})

        perfomance_df = pd.concat([perfomance_df], ignore_index=True)
        perfomance_df['contest'] = contest_list[i]
        perfomance_df_list.append(perfomance_df)

        print('Done with Perfomance Points')
    else:
        print('Perfomance Points not Found')
#     ############################################################
#     #Cards click
#     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Cards"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons6 = driver.find_elements(By.XPATH, target_buttons_xpath)
    # Print or interact with the found buttons

    # After clicking the buttons, find buttons with the specified text
    target_text = "Card Markets"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons6 = driver.find_elements(By.XPATH, target_buttons_xpath)

    if len(target_buttons6)!=0:
        time.sleep(4)
        matches = []

        for button in target_buttons6:
            full_xpath = get_full_xpath(button)
            # Regular expression pattern to find "container[<number>]"
            pattern = r"container\[(\d+)\]"
            # Search for all occurrences and extract numbers
            matches.append(re.findall(pattern, full_xpath))

        home_cards_index = matches[0]
        away_cards_index = matches[1]


        # After clicking the Cards button
        init_path = '//sx-pricing-page//sx-p-panel-container['+ str(home_cards_index[0])
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
        retries = 0

        while retries < max_retries:
            try:
                # Find all elements that match the specified XPath pattern
                target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                # Extract and print information from all matching elements
                home_card_names = [target_element.text for target_element in target_elements]

                # Click the element
                1/len(home_card_names)

                break  # Exit the loop if click is successful

            except ZeroDivisionError:
                print("Zero names Found. Retrying...")
                retries += 1
                # Optional: Wait for a moment
                time.sleep(3)
        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        home_card_odds = [target_element.text for target_element in target_elements]

        init_path = '//sx-pricing-page//sx-p-panel-container['+ (away_cards_index[0])
        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'

        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        away_card_names = [target_element.text for target_element in target_elements]

        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        away_card_odds = [target_element.text for target_element in target_elements]

        home_card_df = pd.DataFrame({"card_names": home_card_names, "card_odds": home_card_odds})
        away_card_df = pd.DataFrame({"card_names": away_card_names, "card_odds": away_card_odds})

        cards_df = pd.concat([home_card_df,away_card_df], ignore_index=True)
        cards_df['contest'] = contest_list[i]

        cards_df_list.append(cards_df)
        print('Done with cards')

    time.sleep(3)
    ############################################################
    #Assist click
    ############################################################

    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Assist Minutes"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons3 = driver.find_elements(By.XPATH, target_buttons_xpath)
        # Print or interact with the found buttons
    for j in range(len(target_buttons3)):
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
            # Scroll the element into view
            ActionChains(driver).move_to_element(target_buttons3[j]).perform()
            # Click the button using JavaScript
            driver.execute_script("arguments[0].click();", target_buttons3[j])
            # Optional: Wait for a moment
            time.sleep(3)
        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")
    time.sleep(3)
    ####################################################################
    # Assist x10 click
    ####################################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Assists x 10"

    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'

    # Find all buttons with the target text
    target_buttons4 = driver.find_elements(By.XPATH, target_buttons_xpath)

        # Print or interact with the found buttons
    for j in range(len(target_buttons4)):
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
            # Scroll the element into view
            ActionChains(driver).move_to_element(target_buttons4[j]).perform()
            # Click the button using JavaScript
            driver.execute_script("arguments[0].click();", target_buttons4[j])
            # Optional: Wait for a moment
            time.sleep(3)
        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")
    time.sleep(3)


    ############################################################
    #Assist MARKETS
    ############################################################
    matches = []
    # HOME DATA
    for button in target_buttons3:
        full_xpath = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"

        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath)

    if len(matches)!=0:
        # Print extracted numbers
        for match in matches:
            assist_index = match

        init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index)
        #                sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[4]/div/sc-panel/div/div/div[2]/header/div/div[1]/span
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
        retries = 0
        while retries < max_retries:
            try:
                # Find all elements that match the specified XPath pattern
                target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                # Extract and print information from all matching elements
                home_AM_names = [target_element.text for target_element in target_elements]

                # Click the element
                1/len(home_AM_names)

                break  # Exit the loop if click is successful

            except ZeroDivisionError:
                print("Zero names Found. Retrying...")
                retries += 1
                # Optional: Wait for a moment
                time.sleep(3)
        home_AM_names

        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        #                                         sx-p-panel-spreads-column[1]/div/div[2]/div[3]/sx-spr-price-button/div/div
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        home_AM_odds = [target_element.text for target_element in target_elements]

        home_assists_df = pd.DataFrame({"AM_names": home_AM_names, "AM_odds": home_AM_odds})
    #     away_assists_df = pd.DataFrame({"AM_names": away_AM_names, "AM_odds": away_AM_odds})

        assists_df = pd.concat([home_assists_df], ignore_index=True) #away_assists_df
        assists_df['contest'] = contest_list[i]
        assists_df_list.append(assists_df)

        print('Done with assists')
    else:
        print('Assists not Found')

    ##################################################################
    # Assists x 10
    ##################################################################
    matches = []
    for button in target_buttons4:
        full_xpath2 = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"

        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath2)

    if len(matches)!=0:
        # Print extracted numbers
        for match in matches:
            assist_index2 = match

            init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index2)
    #         target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
            target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'

            retries = 0
            while retries < max_retries:
                try:
                    # Find all elements that match the specified XPath pattern
                    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                    # Extract and print information from all matching elements
                    home_AM_namesX10 = [target_element.text for target_element in target_elements]

                    # Click the element
                    1/len(home_AM_namesX10)

                    break  # Exit the loop if click is successful

                except ZeroDivisionError:
                    print("Division by zero. Retrying...")
                    retries += 1
                    # Optional: Wait for a moment
                    time.sleep(3)

            # After clicking the initial buttons, find elements that match the specified XPath pattern
            target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            home_AM_oddsX10 = [target_element.text for target_element in target_elements]

            home_assistsX10_df = pd.DataFrame({"AM_namesX10": home_AM_namesX10, "AM_oddsX10": home_AM_oddsX10})

            assistsX10_df = pd.concat([home_assistsX10_df], ignore_index=True) #,away_assistsX10_df
            assistsX10_df['contest'] = contest_list[i]
            assistsx10_df_list.append(assistsX10_df)

            print('Done with assistsX10')
    else:
        print('AssistsX10 not Found')

    driver.back()
    time.sleep(3)

On: Man City v Wolves
home PGM: 17 home SMM: 17
away PGM: 17 away SMM: 17
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
Done with assistsX10
On: Bournemouth v Liverpool
home PGM: 14 home SMM: 14
away PGM: 18 away SMM: 18
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
Done with assistsX10
On: Brentford v Nottingham Forest
home PGM: 18 home SMM: 18
away PGM: 18 away SMM: 18
Done with Scorers
Perfomance Points not Found
Done with cards
Assists not Found
AssistsX10 not Found
On: Crystal Palace v Chelsea
home PGM: 17 home SMM: 17
away PGM: 20 away SMM: 20
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
AssistsX10 not Found
On: Newcastle v Aston Villa
home PGM: 15 home SMM: 15
away PGM: 17 away SMM: 17
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
AssistsX10 not Found
On: Arsenal v Man Utd
home PGM: 19 home SMM: 19
away PGM: 18 away SMM: 18
Done with Scorers
Perfomance Points not Found
Done with cards
Assists not Found
AssistsX10 not Found
On: Everton v Leeds
home PGM: 16 home SMM: 16
away PGM: 17 away SMM: 17
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
Done with assistsX10

In [718]:
driver.back()

In [ ]:
button_elements = driver.find_elements(By.XPATH, button_xpath)
max_retries = 3
assist_index = 3

for i in range(3,10):
    print('On: '+contest_list[i])
    retries = 0
    while retries < max_retries:
        try:
            # Re-find the elements to handle staleness
            button_elements = WebDriverWait(driver, 10).until(
                EC.presence_of_all_elements_located((By.XPATH, button_xpath))
            )
            # Click the element
            button_elements[i].click()
            # Optional: Wait for a moment
            time.sleep(3)

            break  # Exit the loop if click is successful

        except StaleElementReferenceException:
            print("Element reference is stale. Retrying...")
            retries += 1
    if retries == max_retries:
        print(f"Failed to click button at index {i} after {max_retries} retries.")

    time.sleep(5)


    #     ############################################################
    #     #scorer click
    #     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Goal Minutes"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons1 = driver.find_elements(By.XPATH, target_buttons_xpath)

    for button in target_buttons1:
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
            # Scroll into view
            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", button)

            # Try normal click first
            try:
                button.click()
            except Exception:
                # Fallback: JS click
                driver.execute_script("arguments[0].click();", button)
            # Optional: Wait for a moment
            time.sleep(3)
        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")


    #     ############################################################
    #     #PLAYERS click
    #     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Players"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons = driver.find_elements(By.XPATH, target_buttons_xpath)
    # Print or interact with the found buttons
    try:
        # Wait up to 10 seconds for the button to be clickable
        WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
        # Scroll the element into view
        ActionChains(driver).move_to_element(target_buttons[0]).perform()
        # Click the button using JavaScript
        driver.execute_script("arguments[0].click();", target_buttons[0])
        # Optional: Wait for a moment
        time.sleep(3)
    except TimeoutException:
        print(f"Timeout waiting for the button to be clickable.")


    ############################################################
    #Scorer Markets
    ############################################################
    time.sleep(4)
    matches = []

    for button in target_buttons1:
        full_xpath = get_full_xpath(button)
        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"
        # Search for all occurrences and extract numbers
        matches.append(re.findall(pattern, full_xpath))

    home_index = matches[0]
    away_index = matches[1]

    # HOME DATA
    init_path = '//sx-pricing-page//sx-p-panel-container['+ home_index[0]
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
    # /sc-panel/div/div[2]/content/sx-p-panel-spreads/div/div/sx-p-panel-spreads-column[1]/div/div[2]/div[2]/div/div/sx-p-panel-link-name/div/span
    # sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[1]/div/sc-panel/div/div[2]/content/sx-p-panel-spreads/div/div/sx-p-panel-spreads-column[1]/div/div[2]/div[2]/div/div/sx-p-panel-link-name/div/span
    # /html/body/app/div/main/sx-content/div/div[3]/div[3]/
    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            PGM_names = [target_element.text for target_element in target_elements]
            # Click the element
            1/len(PGM_names)

            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("Division by zero. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)


    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    PGM_odds = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_names = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_odds = [target_element.text for target_element in target_elements]

    home_df = pd.DataFrame({"PGM_names": PGM_names, "PGM_odds": PGM_odds,"SMM_names": SMM_names, "SMM_odds": SMM_odds})

    print('home PGM: '+ str(len(PGM_names)),'home SMM: '+ str(len(SMM_names)))

    # AWAY DATA
    # After clicking the initial buttons, find elements that match the specified XPath pattern
    init_path = '//sx-pricing-page//sx-p-panel-container['+ away_index[0]

    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'

    retries = 0
    while retries < max_retries:
        try:
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            PGM_names = [target_element.text for target_element in target_elements]

            # Click the element
            1/len(PGM_names)

            break  # Exit the loop if click is successful

        except ZeroDivisionError:
            print("Division by zero. Retrying...")
            retries += 1
            # Optional: Wait for a moment
            time.sleep(3)

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    PGM_odds = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_names = [target_element.text for target_element in target_elements]

    # After clicking the initial buttons, find elements that match the specified XPath pattern
    target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[2]/div/div[*]/div[3]/sx-spr-price-button/div/div'
    # Find all elements that match the specified XPath pattern
    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
    # Extract and print information from all matching elements
    SMM_odds = [target_element.text for target_element in target_elements]

    print('away PGM: '+ str(len(PGM_names)),'away SMM: '+ str(len(SMM_names)))

    away_df = pd.DataFrame({"PGM_names": PGM_names, "PGM_odds": PGM_odds,"SMM_names": SMM_names, "SMM_odds": SMM_odds})

    contest_df = pd.concat([home_df, away_df], ignore_index=True)
    contest_df["contest"] = contest_list[i]

    contest_df_list.append(contest_df)

    print('Done with Scorers')


    #     ############################################################
    #     #Player Performance Points
    #     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Performance Points"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons4 = driver.find_elements(By.XPATH, target_buttons_xpath)

    matches = []
    # HOME DATA
    for button in target_buttons4:
        full_xpath = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"

        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath)

    if len(matches)!=0:
        # Print extracted numbers
        for match in matches:
            perfomance_index = match

        init_path = '//sx-pricing-page//sx-p-panel-container['+ str(perfomance_index)
        #                sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[4]/div/sc-panel/div/div/div[2]/header/div/div[1]/span
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
        retries = 0
        while retries < max_retries:
            try:
                # Find all elements that match the specified XPath pattern
                target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                # Extract and print information from all matching elements
                perfomance_names = [target_element.text for target_element in target_elements]

                # Click the element
                1/len(perfomance_names)

                break  # Exit the loop if click is successful

            except ZeroDivisionError:
                print("Zero names Found. Retrying...")
                retries += 1
                # Optional: Wait for a moment
                time.sleep(3)
        perfomance_names

        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        perfomance_odds = [target_element.text for target_element in target_elements]

        perfomance_df = pd.DataFrame({"perfomance_names": perfomance_names, "perfomance_odds": perfomance_odds})

        perfomance_df = pd.concat([perfomance_df], ignore_index=True)
        perfomance_df['contest'] = contest_list[i]
        perfomance_df_list.append(perfomance_df)

        print('Done with Perfomance Points')
    else:
        print('Perfomance Points not Found')
#     ############################################################
#     #Cards click
#     ############################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Cards"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons6 = driver.find_elements(By.XPATH, target_buttons_xpath)
    # Print or interact with the found buttons

    # After clicking the buttons, find buttons with the specified text
    target_text = "Card Markets"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons6 = driver.find_elements(By.XPATH, target_buttons_xpath)

    if len(target_buttons6)!=0:
        time.sleep(4)
        matches = []

        for button in target_buttons6:
            full_xpath = get_full_xpath(button)
            # Regular expression pattern to find "container[<number>]"
            pattern = r"container\[(\d+)\]"
            # Search for all occurrences and extract numbers
            matches.append(re.findall(pattern, full_xpath))

        home_cards_index = matches[0]
        away_cards_index = matches[1]


        # After clicking the Cards button
        init_path = '//sx-pricing-page//sx-p-panel-container['+ str(home_cards_index[0])
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
        retries = 0

        while retries < max_retries:
            try:
                # Find all elements that match the specified XPath pattern
                target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                # Extract and print information from all matching elements
                home_card_names = [target_element.text for target_element in target_elements]

                # Click the element
                1/len(home_card_names)

                break  # Exit the loop if click is successful

            except ZeroDivisionError:
                print("Zero names Found. Retrying...")
                retries += 1
                # Optional: Wait for a moment
                time.sleep(3)
        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        home_card_odds = [target_element.text for target_element in target_elements]

        init_path = '//sx-pricing-page//sx-p-panel-container['+ (away_cards_index[0])
        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'

        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        away_card_names = [target_element.text for target_element in target_elements]

        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        away_card_odds = [target_element.text for target_element in target_elements]

        home_card_df = pd.DataFrame({"card_names": home_card_names, "card_odds": home_card_odds})
        away_card_df = pd.DataFrame({"card_names": away_card_names, "card_odds": away_card_odds})

        cards_df = pd.concat([home_card_df,away_card_df], ignore_index=True)
        cards_df['contest'] = contest_list[i]

        cards_df_list.append(cards_df)
        print('Done with cards')

    time.sleep(3)
    ############################################################
    #Assist click
    ############################################################

    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Assist Minutes"
    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'
    # Find all buttons with the target text
    target_buttons3 = driver.find_elements(By.XPATH, target_buttons_xpath)
        # Print or interact with the found buttons
    for j in range(len(target_buttons3)):
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
            # Scroll the element into view
            ActionChains(driver).move_to_element(target_buttons3[j]).perform()
            # Click the button using JavaScript
            driver.execute_script("arguments[0].click();", target_buttons3[j])
            # Optional: Wait for a moment
            time.sleep(3)
        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")
    time.sleep(3)
    ####################################################################
    # Assist x10 click
    ####################################################################
    # After clicking the buttons, find buttons with the specified text
    target_text = "Player Assists x 10"

    # XPath selector for buttons with the target text
    target_buttons_xpath = f'//*[contains(text(), "{target_text}")]'

    # Find all buttons with the target text
    target_buttons4 = driver.find_elements(By.XPATH, target_buttons_xpath)

        # Print or interact with the found buttons
    for j in range(len(target_buttons4)):
        try:
            # Wait up to 10 seconds for the button to be clickable
            WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, target_buttons_xpath)))
            # Scroll the element into view
            ActionChains(driver).move_to_element(target_buttons4[j]).perform()
            # Click the button using JavaScript
            driver.execute_script("arguments[0].click();", target_buttons4[j])
            # Optional: Wait for a moment
            time.sleep(3)
        except TimeoutException:
            print(f"Timeout waiting for the button to be clickable.")
    time.sleep(3)


    ############################################################
    #Assist MARKETS
    ############################################################
    matches = []
    # HOME DATA
    for button in target_buttons3:
        full_xpath = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"

        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath)

    if len(matches)!=0:
        # Print extracted numbers
        for match in matches:
            assist_index = match

        init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index)
        #                sx-pricing-page/div[1]/sc-panel/div/div[2]/content/sx-p-panel-container[4]/div/sc-panel/div/div/div[2]/header/div/div[1]/span
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
        retries = 0
        while retries < max_retries:
            try:
                # Find all elements that match the specified XPath pattern
                target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                # Extract and print information from all matching elements
                home_AM_names = [target_element.text for target_element in target_elements]

                # Click the element
                1/len(home_AM_names)

                break  # Exit the loop if click is successful

            except ZeroDivisionError:
                print("Zero names Found. Retrying...")
                retries += 1
                # Optional: Wait for a moment
                time.sleep(3)
        home_AM_names

        # After clicking the initial buttons, find elements that match the specified XPath pattern
        target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
        #                                         sx-p-panel-spreads-column[1]/div/div[2]/div[3]/sx-spr-price-button/div/div
        # Find all elements that match the specified XPath pattern
        target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
        # Extract and print information from all matching elements
        home_AM_odds = [target_element.text for target_element in target_elements]

        home_assists_df = pd.DataFrame({"AM_names": home_AM_names, "AM_odds": home_AM_odds})
    #     away_assists_df = pd.DataFrame({"AM_names": away_AM_names, "AM_odds": away_AM_odds})

        assists_df = pd.concat([home_assists_df], ignore_index=True) #away_assists_df
        assists_df['contest'] = contest_list[i]
        assists_df_list.append(assists_df)

        print('Done with assists')
    else:
        print('Assists not Found')

    ##################################################################
    # Assists x 10
    ##################################################################
    matches = []
    for button in target_buttons4:
        full_xpath2 = get_full_xpath(button)

        # Regular expression pattern to find "container[<number>]"
        pattern = r"container\[(\d+)\]"

        # Search for all occurrences and extract numbers
        matches = re.findall(pattern, full_xpath2)

    if len(matches)!=0:
        # Print extracted numbers
        for match in matches:
            assist_index2 = match

            init_path = '//sx-pricing-page//sx-p-panel-container['+ str(assist_index2)
    #         target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[1]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'
            target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[2]/div/div/sx-p-panel-link-name/div/span'

            retries = 0
            while retries < max_retries:
                try:
                    # Find all elements that match the specified XPath pattern
                    target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
                    # Extract and print information from all matching elements
                    home_AM_namesX10 = [target_element.text for target_element in target_elements]

                    # Click the element
                    1/len(home_AM_namesX10)

                    break  # Exit the loop if click is successful

                except ZeroDivisionError:
                    print("Division by zero. Retrying...")
                    retries += 1
                    # Optional: Wait for a moment
                    time.sleep(3)

            # After clicking the initial buttons, find elements that match the specified XPath pattern
            target_xpath_pattern = init_path + ']//sx-p-panel-spreads-column[*]/div/div[*]/div[3]/sx-spr-price-button/div/div'
            # Find all elements that match the specified XPath pattern
            target_elements = driver.find_elements(By.XPATH, target_xpath_pattern)
            # Extract and print information from all matching elements
            home_AM_oddsX10 = [target_element.text for target_element in target_elements]

            home_assistsX10_df = pd.DataFrame({"AM_namesX10": home_AM_namesX10, "AM_oddsX10": home_AM_oddsX10})

            assistsX10_df = pd.concat([home_assistsX10_df], ignore_index=True) #,away_assistsX10_df
            assistsX10_df['contest'] = contest_list[i]
            assistsx10_df_list.append(assistsX10_df)

            print('Done with assistsX10')
    else:
        print('AssistsX10 not Found')

    driver.back()
    time.sleep(3)

On: Bournemouth v Arsenal
home PGM: 15 home SMM: 15
away PGM: 18 away SMM: 18
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
Done with assistsX10
On: Leeds v Man Utd
home PGM: 17 home SMM: 17
away PGM: 17 away SMM: 17
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
Done with assistsX10
On: Everton v Brentford
home PGM: 17 home SMM: 17
away PGM: 16 away SMM: 16
Done with Scorers
Perfomance Points not Found
Done with cards
Assists not Found
AssistsX10 not Found
On: Fulham v Liverpool
home PGM: 16 home SMM: 16
away PGM: 15 away SMM: 15
Done with Scorers
Done with Perfomance Points
Done with cards
Done with assists
Done with assistsX10
On: Newcastle v Crystal Palace
home PGM: 14 home SMM: 14
away PGM: 15 away SMM: 15
Done with Scorers
Perfomance Points not Found
Done with cards
Assists not Found
AssistsX10 not Found
On: Tottenham v Sunderland
home PGM: 15 home SMM: 15
away PGM: 15 away SMM: 15
Done with Scorers
Perfomance Points not Found
Done with cards
Assists not Found
AssistsX10 not Found
On: Man City v Chelsea
home PGM: 16 home SMM: 16
away PGM: 18 away SMM: 18
Done with Scorers
Perfomance Points not Found
Assists not Found
AssistsX10 not Found

In [99]:
final_cards = pd.concat(cards_df_list)
final_cards

               card_names card_odds                contest
0        Lucas Paqueta CM   19 - 23  West Ham v Sunderland
1   Soungoutou Magassa CM   17 - 21  West Ham v Sunderland
2      Guido Rodriguez CM   15 - 19  West Ham v Sunderland
3     Mateus Fernandes CM   13 - 17  West Ham v Sunderland
4     Taty Castellanos CM   12 - 16  West Ham v Sunderland
..                    ...       ...                    ...
31         Noah Okafor CM     3 - 6        Everton v Leeds
32          Joel Piroe CM     3 - 6        Everton v Leeds
33        Lukas Nmecha CM   2.5 - 5        Everton v Leeds
34         Karl Darlow CM     5 - 8        Everton v Leeds
35      Sean Longstaff CM    7 - 11        Everton v Leeds

[367 rows x 3 columns]

In [ ]:
final_scorer_df = pd.concat(contest_df_list, ignore_index=True)
final_scorer_df

,PGM_names,PGM_odds,SMM_names,SMM_odds,contest
0,Jarrod Bowen PGM,14 - 17,Jarrod Bowen SMM,21 - 26,West Ham v Sunderland
1,Taty Castellanos PGM,14 - 17,Taty Castellanos SMM,20 - 24,West Ham v Sunderland
2,Callum Wilson PGM,11 - 14,Callum Wilson SMM,16 - 20,West Ham v Sunderland
3,Pablo PGM,9 - 12,Pablo SMM,13 - 17,West Ham v Sunderland
4,Lucas Paqueta PGM,7 - 10,Lucas Paqueta SMM,10 - 14,West Ham v Sunderland
...,...,...,...,...,...
345,Joe Rodon PGM,1 - 3,Joe Rodon SMM,2 - 4,Everton v Leeds
346,Ilia Gruev PGM,1 - 3,Ilia Gruev SMM,2 - 4,Everton v Leeds
347,Gabriel Gudmondsson PGM,1 - 3,Gabriel Gudmondsson SMM,2 - 4,Everton v Leeds
348,Ethan Ampadu PGM,1 - 3,Ethan Ampadu SMM,2 - 4,Everton v Leeds
349,Sean Longstaff PGM,2.5 - 5,Sean Longstaff SMM,4 - 7,Everton v Leeds

In [103]:
#prefix = "C:/Users/Guest_user/Documents/FPL/FPL2024/sportingIndex/scorer/gw"
prefix ="C:/Users/burio/Downloads/FPL2026/sportingIndex/cards/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/sportingIndex/cards/gw232.csv'

In [105]:
final_cards.to_csv(file_name, index = False)# encoding = 'utf-8'

In [107]:
#prefix = "C:/Users/Guest_user/Documents/FPL/FPL2024/sportingIndex/scorer/gw"
prefix ="C:/Users/burio/Downloads/FPL2026/sportingIndex/scorer/gw"

file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/sportingIndex/scorer/gw232.csv'

In [109]:
final_scorer_df.to_csv(file_name, index = False)# encoding = 'utf-8'

In [111]:
final_assists = pd.concat(assists_df_list)
final_assists

                    AM_names  AM_odds                contest
0            Jarrod Bowen AM   9 - 12  West Ham v Sunderland
1           Lucas Paqueta AM   8 - 11  West Ham v Sunderland
2   Crysencio Summerville AM    6 - 9  West Ham v Sunderland
3   El Hadji Malick Diouf AM    4 - 7  West Ham v Sunderland
4        Mateus Fernandes AM    4 - 7  West Ham v Sunderland
..                       ...      ...                    ...
23           Ethan Ampadu AM    1 - 3        Everton v Leeds
24           Lukas Nmecha AM  0.5 - 2        Everton v Leeds
25         Pascal Struijk AM  0.1 - 1        Everton v Leeds
26              Joe Rodon AM  0.1 - 1        Everton v Leeds
27     Sebastiaan Bornauw AM  0.1 - 1        Everton v Leeds

[172 rows x 3 columns]

In [113]:
prefix ="C:/Users/burio/Downloads/FPL2026/sportingIndex/assist/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/sportingIndex/assist/gw232.csv'

In [115]:
final_assists.to_csv(file_name, index = False)# encoding = 'utf-8'

In [117]:
final_assistsX10 = pd.concat(assistsx10_df_list)
final_assistsX10

                   AM_namesX10 AM_oddsX10                contest
0            Jarrod Bowen Ax10    2 - 2.4  West Ham v Sunderland
1             Enzo Le Fee Ax10  1.8 - 2.2  West Ham v Sunderland
2            Granit Xhaka Ax10  1.6 - 1.9  West Ham v Sunderland
3   Crysencio Summerville Ax10  1.4 - 1.7  West Ham v Sunderland
4        Mateus Fernandes Ax10  1.1 - 1.4  West Ham v Sunderland
..                         ...        ...                    ...
23           Lukas Nmecha Ax10  0.2 - 0.4        Everton v Leeds
24           Jake O'Brien Ax10  0.1 - 0.3        Everton v Leeds
25         Pascal Struijk Ax10    0 - 0.2        Everton v Leeds
26              Joe Rodon Ax10    0 - 0.2        Everton v Leeds
27     Sebastiaan Bornauw Ax10    0 - 0.2        Everton v Leeds

[145 rows x 3 columns]

In [119]:
prefix ="C:/Users/burio/Downloads/FPL2026/sportingIndex/assistX10/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/sportingIndex/assistX10/gw232.csv'

In [120]:
final_assistsX10.to_csv(file_name, index = False)# encoding = 'utf-8'

In [123]:
final_perf = pd.concat(perfomance_df_list)
final_perf

                perfomance_names perfomance_odds                contest
0          Mateus Fernandes Perf         19 - 22  West Ham v Sunderland
1             Lucas Paqueta Perf         19 - 22  West Ham v Sunderland
2   Konstantinos Mavropanos Perf       16.5 - 19  West Ham v Sunderland
3              Jarrod Bowen Perf       16 - 18.5  West Ham v Sunderland
4         Aaron Wan-Bissaka Perf       16 - 18.5  West Ham v Sunderland
..                           ...             ...                    ...
23      Gabriel Gudmondsson Perf       14 - 16.5        Everton v Leeds
24             Jayden Bogle Perf       13.5 - 16        Everton v Leeds
25          Wilfried Gnonto Perf       13.5 - 16        Everton v Leeds
26       Sebastiaan Bornauw Perf       13 - 15.5        Everton v Leeds
27              Noah Okafor Perf       12.5 - 15        Everton v Leeds

[152 rows x 3 columns]

In [125]:
prefix ="C:/Users/burio/Downloads/FPL2026/sportingIndex/performance_points/gw"
file_name =  prefix+ str(gw) + '.csv'
file_name

'C:/Users/burio/Downloads/FPL2026/sportingIndex/performance_points/gw232.csv'

In [127]:
final_perf.to_csv(file_name, index = False)# encoding = 'utf-8'