In [219]:
# For playing up to 60 minutes	1
# For playing 60 minutes or more (excluding stoppage time)	2
# For each goal scored by a goalkeeper	10
# For each goal scored by a defender	6
# For each goal scored by a midfielder	5
# For each goal scored by a forward	4
# For each goal assist	3
# For a clean sheet by a goalkeeper or defender	4
# For a clean sheet by a midfielder	1
# For every 3 shot saves by a goalkeeper	1
# For each penalty save	5
# For each penalty miss	-2
# Bonus points for the best players in a match	1-3
# For every 2 goals conceded by a goalkeeper or defender	-1
# For each yellow card	-1
# For each red card	-3
# For each own goal	-2

## GK
## ---> >60  = 2
## ---> cs*4
## ---> ((sv)/3)*1
## ---> gc
## ---> yc*-1


## DEF
## ---> >60  = 2
## ---> xg*6
## ---> xa*3
## ---> cs*4
## ---> gc
## ---> yc*-1


## MID
## ---> >60  = +2
## ---> xg*5
## ---> xa*3
## ---> cs*1
## ---> yc*-1


## FWD
## ---> >60  = 2
## ---> xg*4
## ---> xa*3
## ---> yc*-1

# Innit

In [1]:
import pandas as pd

from pycaret.regression import load_model as load_model_r, predict_model as predict_model_r
from pycaret.classification import load_model as load_model_c,  predict_model as predict_model_c

In [221]:
gw=32
data_22_23 = pd.read_csv('./data/joint/22-23/merged_player_data.csv',).dropna()
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv').dropna()
data_24_25 = pd.read_csv('./data/joint/24-25/merged_player_data.csv')
data_tar = data_24_25[data_24_25['event']==gw]
data_24_25_ = data_24_25[data_24_25['event'] != gw]

data = pd.concat([data_22_23, data_23_24, data_24_25_])

In [222]:
# Make a copy to avoid changing the original if needed
df_with_preds = data_tar.copy()

# GK

In [223]:
## GK
## ---> >60  = 2
## ---> cs*4
## ---> ((sv)/3)*1
## ---> gc
## ---> yc*-1

## CS

In [224]:
g_cs_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers', 'clean_sheets',
                 'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


g_cs_data_tar = data_tar[data_tar['position'] == '1']
g_cs_data_tar = g_cs_data_tar[g_cs_features]

g_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)

gk_cs_model = load_model_c('gk_cs_model')  # No need to add `.pkl`

preds = predict_model_c(gk_cs_model, data=g_cs_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'cs_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.507612,NaN,0.615,0.220,0.164,0.0
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.10,NaN,0.0,-0.243328,NaN,0.187,0.216,0.596,0.0
636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.772093,NaN,0.732,0.173,0.095,0.0
719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.11,NaN,0.0,0.136709,NaN,0.732,0.173,0.095,0.0
811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,0.13,NaN,0.0,0.361856,NaN,0.615,0.220,0.164,0.0
837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,0.02,NaN,0.0,-0.758231,NaN,0.441,0.263,0.296,0.0
1331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.05,0.05,NaN,0.0,0.514311,NaN,0.695,0.188,0.117,0.0
1680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.08,0.06,NaN,0.0,0.042998,NaN,0.624,0.212,0.164,0.0
1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.19,1.02,0.0,-0.193798,NaN,0.413,0.271,0.316,0.0
2298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,0.02,NaN,0.0,-0.696991,NaN,0.449,0.290,0.262,0.0
2596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.18,NaN,0.0,-0.149796,NaN,0.441,0.263,0.296,0.0
3185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.03,0.98,0.0,-0.550388,NaN,0.695,0.188,0.117,0.0
3362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,0.01,NaN,0.0,0.252174,NaN,0.732,0.173,0.095,0.0
3516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.18,0.82,0.0,-0.819196,NaN,0.732,0.173,0.095,0.0
3577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.020177,NaN,0.732,0.173,0.095,0.0
3640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.16,NaN,0.0,-0.922349,NaN,0.703,0.187,0.110,0.0
3923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.19,NaN,0.0,0.636802,NaN,0.703,0.187,0.110,0.0
4304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.11,NaN,0.0,0.606642,NaN,0.624,0.212,0.164,0.0
4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.42,0.42,2.26,0.0,-0.660465,NaN,0.624,0.212,0.164,0.0
4995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,0.03,NaN,0.0,-0.190563,NaN,0.542,0.243,0.215,0.0
5134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,0.17,NaN,0.0,-1.000000,NaN,0.187,0.216,0.596,0.0
5249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,2.68,0.0,-0.915803,NaN,0.542,0.243,0.215,0.0
5530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.36,0.36,NaN,0.0,0.736071,NaN,0.542,0.243,0.215,0.0
6029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,0.02,NaN,0.0,0.387800,NaN,0.449,0.290,0.262,0.0
6272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.821429,NaN,0.187,0.216,0.596,0.0
6299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.10,0.50,0.0,-0.113924,NaN,0.187,0.216,0.596,0.0
6332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.14,NaN,0.0,0.647546,NaN,0.187,0.216,0.596,0.0
6472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.667984,NaN,0.413,0.271,0.316,0.0
6621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.34,0.34,2.98,0.0,-0.750000,NaN,0.413,0.271,0.316,0.0
6979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15,0.15,NaN,0.0,-0.441832,NaN,0.413,0.271,0.316,0.0
7002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.129909,NaN,0.187,0.216,0.596,0.0
7066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.07,0.07,NaN,0.0,0.169436,NaN,0.703,0.187,0.110,0.0
7186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,0.09,1.80,0.0,-0.871358,NaN,0.703,0.187,0.110,0.0
7621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,0.01,NaN,0.0,-0.635932,NaN,0.413,0.271,0.316,0.0
7797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.16,2.22,0.0,-0.925816,NaN,0.695,0.188,0.117,0.0
8077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.23,0.23,NaN,0.0,-0.941410,NaN,0.695,0.188,0.117,0.0
9145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.783784,NaN,0.703,0.187,0.110,0.0
9324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.800000,NaN,0.413,0.271,0.316,0.0
9365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.432161,NaN,0.441,0.263,0.296,0.0
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.22,NaN,0.0,-0.489726,NaN,0.695,0.188,0.117,0.0
9653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.10,1.14,0.0,-1.000000,NaN,0.441,0.263,0.296,0.0
9829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.04,NaN,0.0,-0.393388,NaN,0.615,0.220,0.164,0.0

## Saves

In [225]:
g_saves_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_a_difficulty', 'team_h_difficulty', 'percenatge_net_transfers','ownership_change',

            'saves',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


g_saves_data_tar = data_tar[data_tar['position'] == '1']
g_saves_data_tar = g_saves_data_tar[g_saves_features]

gk_saves_model = load_model_r('gk_saves_model')  # No need to add `.pkl`

g_saves_data_tar.drop(columns=['position', 'saves'], inplace=True)

preds = predict_model_r(gk_saves_model, data=g_saves_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'saves_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.507612,NaN,0.615,0.220,0.164,0.0,2.842552
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,NaN,0.0,-0.243328,NaN,0.187,0.216,0.596,0.0,2.958359
636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.772093,NaN,0.732,0.173,0.095,0.0,3.031928
719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,NaN,0.0,0.136709,NaN,0.732,0.173,0.095,0.0,2.885543
811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,NaN,0.0,0.361856,NaN,0.615,0.220,0.164,0.0,2.925170
837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,-0.758231,NaN,0.441,0.263,0.296,0.0,2.960681
1331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.05,NaN,0.0,0.514311,NaN,0.695,0.188,0.117,0.0,3.018821
1680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.06,NaN,0.0,0.042998,NaN,0.624,0.212,0.164,0.0,2.646466
1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,1.02,0.0,-0.193798,NaN,0.413,0.271,0.316,0.0,2.987363
2298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,-0.696991,NaN,0.449,0.290,0.262,0.0,3.056534
2596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,NaN,0.0,-0.149796,NaN,0.441,0.263,0.296,0.0,3.078334
3185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,0.98,0.0,-0.550388,NaN,0.695,0.188,0.117,0.0,3.334828
3362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,NaN,0.0,0.252174,NaN,0.732,0.173,0.095,0.0,2.970431
3516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.82,0.0,-0.819196,NaN,0.732,0.173,0.095,0.0,3.175095
3577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.020177,NaN,0.732,0.173,0.095,0.0,2.792203
3640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,NaN,0.0,-0.922349,NaN,0.703,0.187,0.110,0.0,3.087594
3923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,NaN,0.0,0.636802,NaN,0.703,0.187,0.110,0.0,3.136500
4304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,NaN,0.0,0.606642,NaN,0.624,0.212,0.164,0.0,3.018523
4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.42,2.26,0.0,-0.660465,NaN,0.624,0.212,0.164,0.0,3.018213
4995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,NaN,0.0,-0.190563,NaN,0.542,0.243,0.215,0.0,3.167883
5134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,NaN,0.0,-1.000000,NaN,0.187,0.216,0.596,0.0,2.538622
5249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,2.68,0.0,-0.915803,NaN,0.542,0.243,0.215,0.0,3.206991
5530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.36,NaN,0.0,0.736071,NaN,0.542,0.243,0.215,0.0,2.960937
6029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,0.387800,NaN,0.449,0.290,0.262,0.0,3.125903
6272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.821429,NaN,0.187,0.216,0.596,0.0,3.146963
6299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.50,0.0,-0.113924,NaN,0.187,0.216,0.596,0.0,3.215006
6332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,NaN,0.0,0.647546,NaN,0.187,0.216,0.596,0.0,2.371826
6472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.667984,NaN,0.413,0.271,0.316,0.0,2.918888
6621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.34,2.98,0.0,-0.750000,NaN,0.413,0.271,0.316,0.0,3.161730
6979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15,NaN,0.0,-0.441832,NaN,0.413,0.271,0.316,0.0,2.961932
7002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.129909,NaN,0.187,0.216,0.596,0.0,2.693126
7066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.07,NaN,0.0,0.169436,NaN,0.703,0.187,0.110,0.0,3.141831
7186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,1.80,0.0,-0.871358,NaN,0.703,0.187,0.110,0.0,2.941318
7621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,NaN,0.0,-0.635932,NaN,0.413,0.271,0.316,0.0,2.975922
7797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,2.22,0.0,-0.925816,NaN,0.695,0.188,0.117,0.0,3.075440
8077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.23,NaN,0.0,-0.941410,NaN,0.695,0.188,0.117,0.0,3.125447
9145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.783784,NaN,0.703,0.187,0.110,0.0,3.513210
9324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.800000,NaN,0.413,0.271,0.316,0.0,2.869529
9365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.432161,NaN,0.441,0.263,0.296,0.0,2.982329
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,NaN,0.0,-0.489726,NaN,0.695,0.188,0.117,0.0,2.899553
9653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,1.14,0.0,-1.000000,NaN,0.441,0.263,0.296,0.0,3.166708
9829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,NaN,0.0,-0.393388,NaN,0.615,0.220,0.164,0.0,3.093946

## GC

In [226]:
g_xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'ownership_change', 'percenatge_net_transfers', 'team_h_difficulty', 'team_a_difficulty',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

g_xgc_data_tar = data_tar[data_tar['position'] == '1']

g_xgc_data_tar = g_xgc_data_tar[g_xgc_features]

g_xgc_data_tar.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

gk_xgc_model = load_model_r('gk_xgc_model')  # No need to add `.pkl`

preds = predict_model_r(gk_xgc_model, data=g_xgc_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'xgc_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.507612,NaN,0.615,0.220,0.164,0.0,2.842552,1.661132
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.243328,NaN,0.187,0.216,0.596,0.0,2.958359,1.661801
636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.772093,NaN,0.732,0.173,0.095,0.0,3.031928,1.381286
719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.136709,NaN,0.732,0.173,0.095,0.0,2.885543,1.358967
811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.361856,NaN,0.615,0.220,0.164,0.0,2.925170,1.159556
837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.758231,NaN,0.441,0.263,0.296,0.0,2.960681,1.350607
1331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.514311,NaN,0.695,0.188,0.117,0.0,3.018821,1.347572
1680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.042998,NaN,0.624,0.212,0.164,0.0,2.646466,1.497222
1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.02,0.0,-0.193798,NaN,0.413,0.271,0.316,0.0,2.987363,1.563444
2298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.696991,NaN,0.449,0.290,0.262,0.0,3.056534,1.581093
2596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.149796,NaN,0.441,0.263,0.296,0.0,3.078334,1.394312
3185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.98,0.0,-0.550388,NaN,0.695,0.188,0.117,0.0,3.334828,2.075462
3362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.252174,NaN,0.732,0.173,0.095,0.0,2.970431,1.865785
3516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.82,0.0,-0.819196,NaN,0.732,0.173,0.095,0.0,3.175095,1.667342
3577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.020177,NaN,0.732,0.173,0.095,0.0,2.792203,1.506841
3640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.922349,NaN,0.703,0.187,0.110,0.0,3.087594,1.006783
3923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.636802,NaN,0.703,0.187,0.110,0.0,3.136500,1.259208
4304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.606642,NaN,0.624,0.212,0.164,0.0,3.018523,1.337902
4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.26,0.0,-0.660465,NaN,0.624,0.212,0.164,0.0,3.018213,1.367691
4995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.190563,NaN,0.542,0.243,0.215,0.0,3.167883,1.517447
5134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-1.000000,NaN,0.187,0.216,0.596,0.0,2.538622,1.346678
5249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.68,0.0,-0.915803,NaN,0.542,0.243,0.215,0.0,3.206991,1.455318
5530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.736071,NaN,0.542,0.243,0.215,0.0,2.960937,1.348526
6029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.387800,NaN,0.449,0.290,0.262,0.0,3.125903,1.325740
6272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.821429,NaN,0.187,0.216,0.596,0.0,3.146963,1.537862
6299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,0.0,-0.113924,NaN,0.187,0.216,0.596,0.0,3.215006,1.619900
6332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.647546,NaN,0.187,0.216,0.596,0.0,2.371826,1.640748
6472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.667984,NaN,0.413,0.271,0.316,0.0,2.918888,1.303662
6621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.98,0.0,-0.750000,NaN,0.413,0.271,0.316,0.0,3.161730,1.378761
6979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.441832,NaN,0.413,0.271,0.316,0.0,2.961932,1.310154
7002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.129909,NaN,0.187,0.216,0.596,0.0,2.693126,1.592734
7066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.169436,NaN,0.703,0.187,0.110,0.0,3.141831,1.624775
7186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.80,0.0,-0.871358,NaN,0.703,0.187,0.110,0.0,2.941318,1.868880
7621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.635932,NaN,0.413,0.271,0.316,0.0,2.975922,1.476377
7797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.22,0.0,-0.925816,NaN,0.695,0.188,0.117,0.0,3.075440,1.801694
8077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.941410,NaN,0.695,0.188,0.117,0.0,3.125447,1.175189
9145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.783784,NaN,0.703,0.187,0.110,0.0,3.513210,1.268333
9324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.800000,NaN,0.413,0.271,0.316,0.0,2.869529,1.425445
9365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.432161,NaN,0.441,0.263,0.296,0.0,2.982329,1.433153
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.489726,NaN,0.695,0.188,0.117,0.0,2.899553,1.984000
9653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.14,0.0,-1.000000,NaN,0.441,0.263,0.296,0.0,3.166708,1.167390
9829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.393388,NaN,0.615,0.220,0.164,0.0,3.093946,1.757227

## YC

In [227]:
g_yc_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

                'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


g_yc_data_tar = data_tar[data_tar['position'] == '1']

g_yc_data_tar = g_yc_data_tar[g_yc_features]

g_yc_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)


gk_yc_model = load_model_c('gk_yc_model')  # No need to add `.pkl`

preds = predict_model_c(gk_yc_model, data=g_yc_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'yc_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.507612,NaN,0.615,0.220,0.164,0.0,2.842552,1.661132,0.0
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.243328,NaN,0.187,0.216,0.596,0.0,2.958359,1.661801,0.0
636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.772093,NaN,0.732,0.173,0.095,0.0,3.031928,1.381286,0.0
719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.136709,NaN,0.732,0.173,0.095,0.0,2.885543,1.358967,0.0
811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.361856,NaN,0.615,0.220,0.164,0.0,2.925170,1.159556,0.0
837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.758231,NaN,0.441,0.263,0.296,0.0,2.960681,1.350607,0.0
1331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.514311,NaN,0.695,0.188,0.117,0.0,3.018821,1.347572,0.0
1680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.042998,NaN,0.624,0.212,0.164,0.0,2.646466,1.497222,0.0
1715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.193798,NaN,0.413,0.271,0.316,0.0,2.987363,1.563444,0.0
2298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.696991,NaN,0.449,0.290,0.262,0.0,3.056534,1.581093,0.0
2596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.149796,NaN,0.441,0.263,0.296,0.0,3.078334,1.394312,0.0
3185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.550388,NaN,0.695,0.188,0.117,0.0,3.334828,2.075462,0.0
3362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.252174,NaN,0.732,0.173,0.095,0.0,2.970431,1.865785,0.0
3516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.819196,NaN,0.732,0.173,0.095,0.0,3.175095,1.667342,0.0
3577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.020177,NaN,0.732,0.173,0.095,0.0,2.792203,1.506841,0.0
3640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.922349,NaN,0.703,0.187,0.110,0.0,3.087594,1.006783,0.0
3923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.636802,NaN,0.703,0.187,0.110,0.0,3.136500,1.259208,0.0
4304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.606642,NaN,0.624,0.212,0.164,0.0,3.018523,1.337902,0.0
4524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.660465,NaN,0.624,0.212,0.164,0.0,3.018213,1.367691,0.0
4995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.190563,NaN,0.542,0.243,0.215,0.0,3.167883,1.517447,0.0
5134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-1.000000,NaN,0.187,0.216,0.596,0.0,2.538622,1.346678,0.0
5249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.915803,NaN,0.542,0.243,0.215,0.0,3.206991,1.455318,0.0
5530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.736071,NaN,0.542,0.243,0.215,0.0,2.960937,1.348526,0.0
6029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.387800,NaN,0.449,0.290,0.262,0.0,3.125903,1.325740,0.0
6272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.821429,NaN,0.187,0.216,0.596,0.0,3.146963,1.537862,0.0
6299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.113924,NaN,0.187,0.216,0.596,0.0,3.215006,1.619900,0.0
6332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.647546,NaN,0.187,0.216,0.596,0.0,2.371826,1.640748,0.0
6472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.667984,NaN,0.413,0.271,0.316,0.0,2.918888,1.303662,0.0
6621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.750000,NaN,0.413,0.271,0.316,0.0,3.161730,1.378761,0.0
6979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.441832,NaN,0.413,0.271,0.316,0.0,2.961932,1.310154,0.0
7002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.129909,NaN,0.187,0.216,0.596,0.0,2.693126,1.592734,0.0
7066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.169436,NaN,0.703,0.187,0.110,0.0,3.141831,1.624775,0.0
7186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.871358,NaN,0.703,0.187,0.110,0.0,2.941318,1.868880,0.0
7621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.635932,NaN,0.413,0.271,0.316,0.0,2.975922,1.476377,0.0
7797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.925816,NaN,0.695,0.188,0.117,0.0,3.075440,1.801694,0.0
8077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.941410,NaN,0.695,0.188,0.117,0.0,3.125447,1.175189,0.0
9145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.783784,NaN,0.703,0.187,0.110,0.0,3.513210,1.268333,0.0
9324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.800000,NaN,0.413,0.271,0.316,0.0,2.869529,1.425445,0.0
9365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.432161,NaN,0.441,0.263,0.296,0.0,2.982329,1.433153,0.0
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.489726,NaN,0.695,0.188,0.117,0.0,2.899553,1.984000,0.0
9653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-1.000000,NaN,0.441,0.263,0.296,0.0,3.166708,1.167390,0.0
9829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.393388,NaN,0.615,0.220,0.164,0.0,3.093946,1.757227,0.0

# Def

In [228]:
## DEF
## ---> >60  = 2
## ---> xg*6
## ---> xa*3
## ---> cs*4
## ---> gc
## ---> yc*-1

## XG

In [229]:
def_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


def_xg_data_tar = data_tar[data_tar['position'] == '2']
def_xg_data_tar = def_xg_data_tar[def_xg_features]
def_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)


def_xg_model = load_model_r('def_xg_model')  # No need to add `.pkl`

preds = predict_model_r(def_xg_model, data=def_xg_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'xg_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.464646,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.042967
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.391304,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.053098
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.056737
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.581669,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.052009
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.791684,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.052305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.600945,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.053068
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.053381,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.045786
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.330801,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.055800
9831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.379310,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.058515
9886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.720524,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.050521

## XA

In [230]:
def_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence',
                   'creativity', 'threat', 'red_cards', 'yellow_cards', 'starts',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


def_xa_data_tar = data_tar[data_tar['position'] == '2']
def_xa_data_tar = def_xa_data_tar[def_xa_features]
def_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)

def_xa_model = load_model_r('def_xa_model')  # No need to add `.pkl`

preds = predict_model_r(def_xa_model, data=def_xa_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'xa_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.042967,0.066550
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.053098,0.048532
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.056737,0.078002
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.052009,0.048618
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.052305,0.042035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.053068,0.056034
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.045786,0.043904
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.055800,0.051282
9831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.058515,0.061868
9886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.050521,0.036949

## CS

In [231]:
d_cs_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
                'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


def_cs_data_tar = data_tar[data_tar['position'] == '2']

def_cs_data_tar = def_cs_data_tar[d_cs_features]

def_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)

def_cs_model = load_model_c('def_cs_model')  # No need to add `.pkl`

preds = predict_model_c(def_cs_model, data=def_cs_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'cs_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.042967,0.066550
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.053098,0.048532
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.056737,0.078002
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,0.0,NaN,NaN,NaN,0.052009,0.048618
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,1.0,NaN,NaN,NaN,0.052305,0.042035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,0.0,NaN,NaN,NaN,0.053068,0.056034
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.045786,0.043904
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.055800,0.051282
9831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.058515,0.061868
9886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,NaN,NaN,0.050521,0.036949

## GC

In [232]:
def_xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3',  'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


def_xgc_data_tar = data_tar[data_tar['position'] == '2']
def_xgc_data_tar = def_xgc_data_tar[def_xgc_features]
def_xgc_data_tar.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

def_xgc_model = load_model_r('def_xgc_model')  # No need to add `.pkl`

preds = predict_model_r(def_xgc_model, data=def_xgc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'xgc_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.6800,NaN,0.042967,0.066550
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,2.0238,NaN,0.053098,0.048532
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,2.1777,NaN,0.056737,0.078002
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,0.0,NaN,0.8480,NaN,0.052009,0.048618
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,1.0,NaN,0.9831,NaN,0.052305,0.042035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,0.0,NaN,1.1248,NaN,0.053068,0.056034
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.3404,NaN,0.045786,0.043904
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.8328,NaN,0.055800,0.051282
9831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.8752,NaN,0.058515,0.061868
9886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,2.0468,NaN,0.050521,0.036949

## YC

In [233]:
def_yc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

            'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

def_yc_data_tar = data_tar[data_tar['position'] == '2']


def_yc_data_tar = def_yc_data_tar[def_yc_features]
def_yc_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)

def_yc_model = load_model_c('def_yc_model')  # No need to add `.pkl`
preds = predict_model_c(def_yc_model, data=def_yc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'yc_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.6800,0.0,0.042967,0.066550
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,2.0238,0.0,0.053098,0.048532
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,2.1777,0.0,0.056737,0.078002
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,0.0,NaN,0.8480,0.0,0.052009,0.048618
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,1.0,NaN,0.9831,0.0,0.052305,0.042035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,0.0,NaN,1.1248,0.0,0.053068,0.056034
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.3404,0.0,0.045786,0.043904
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.8328,0.0,0.055800,0.051282
9831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,1.8752,0.0,0.058515,0.061868
9886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,0.0,NaN,2.0468,0.0,0.050521,0.036949

# Mid

In [234]:
## MID
## ---> >60  = +2
## ---> xg*5
## ---> xa*3
## ---> cs*1
## ---> yc*-1

## XG

In [235]:
mid_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

mid_xg_data_tar = data_tar[data_tar['position'] == '3']
mid_xg_data_tar = mid_xg_data_tar[mid_xg_features]
mid_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)


mid_xg_model = load_model_r('mid_xg_model')  # No need to add `.pkl`

preds = predict_model_r(mid_xg_model, data=mid_xg_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'xg_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.106029,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.106991,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.326897,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.100105,NaN
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.165236,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.113884,NaN
9882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.116293,NaN
9894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.353466,NaN
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.108523,NaN
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.121334,NaN

## XA

In [236]:
mid_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

mid_xa_data_tar = data_tar[data_tar['position'] == '3']
mid_xa_data_tar = mid_xa_data_tar[mid_xa_features]
mid_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)


mid_xa_model = load_model_r('mid_xa_model')  # No need to add `.pkl`

preds = predict_model_r(mid_xa_model, data=mid_xa_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'xa_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.106029,0.107377
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.106991,0.120347
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.326897,0.097279
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.100105,0.125533
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.165236,0.106982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.113884,0.101517
9882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.116293,0.109255
9894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.353466,0.096049
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.108523,0.115156
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,NaN,NaN,NaN,NaN,0.121334,0.126960

## CS

In [237]:
mid_cs_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
                 'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

mid_cs_data_tar = data_tar[data_tar['position'] == '3']
mid_cs_data_tar = mid_cs_data_tar[mid_cs_features]
mid_cs_data_tar.drop(columns=['clean_sheets', 'position'], inplace=True)


mid_cs_model = load_model_c('mid_cs_model')  # No need to add `.pkl`

preds = predict_model_c(mid_cs_model, data=mid_cs_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'cs_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.106029,0.107377
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.106991,0.120347
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.326897,0.097279
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.100105,0.125533
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.165236,0.106982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.113884,0.101517
9882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.116293,0.109255
9894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.353466,0.096049
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.108523,0.115156
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,NaN,0.121334,0.126960

## YC

In [238]:
mid_yc_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
            'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

mid_yc_data_tar = data_tar[data_tar['position'] == '3']
mid_yc_data_tar = mid_yc_data_tar[mid_yc_features]
mid_yc_data_tar.drop(columns=['yellow_cards', 'position'], inplace=True)


mid_yc_model = load_model_c('mid_yc_model')  # No need to add `.pkl`

preds = predict_model_c(mid_yc_model, data=mid_yc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'yc_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.106029,0.107377
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.106991,0.120347
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.326897,0.097279
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.100105,0.125533
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.165236,0.106982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.113884,0.101517
9882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.116293,0.109255
9894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.353466,0.096049
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.108523,0.115156
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.22,0.164,0.0,NaN,NaN,0.0,0.121334,0.126960

# Fwd

In [239]:
## FWD
## ---> >60  = 2
## ---> xg*4
## ---> xa*3
## ---> yc*-1

## XG

In [240]:
fwd_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',


            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

fwd_xg_data_tar = data_tar[data_tar['position'] == '4']
fwd_xg_data_tar = fwd_xg_data_tar[fwd_xg_features]
fwd_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)


fwd_xg_model = load_model_r('fwd_xg_model')  # No need to add `.pkl`

preds = predict_model_r(fwd_xg_model, data=fwd_xg_data_tar)

df_with_preds.loc[df_with_preds['position'] == '4', 'xg_pred'] = preds.loc[df_with_preds['position'] == '4', 'prediction_label']
df_with_preds[df_with_preds['position'] == '4']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.425041,NaN
173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.437441,NaN
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.385241,NaN
423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.452713,NaN
491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.386166,NaN
758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.461185,NaN
852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.436937,NaN
1170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.377152,NaN
1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.383336,NaN
1540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.389733,NaN
1586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.342779,NaN
1801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.421375,NaN
1969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.430819,NaN
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.357535,NaN
2236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.441902,NaN
2665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.430540,NaN
2698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.376718,NaN
2746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.319202,NaN
2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.399976,NaN
2946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.427481,NaN
2978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.442763,NaN
3023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.425707,NaN
3267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.422084,NaN
3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.465412,NaN
3736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.449852,NaN
3840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.458567,NaN
4423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.447005,NaN
4840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.442294,NaN
4918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.410936,NaN
5115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.409343,NaN
5337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.407218,NaN
5366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.390196,NaN
5672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.419211,NaN
5760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.459046,NaN
6064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.440760,NaN
6155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.396114,NaN
6355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.380370,NaN
6390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.391567,NaN
6795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.384828,NaN
6854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.368600,NaN
7044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.399842,NaN
7202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.396794,NaN
7752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.385070,NaN
8042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.457727,NaN
8203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.419515,NaN
8220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.408833,NaN
8494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.374169,NaN
8566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.421769,NaN
9018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.450402,NaN
9204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.434415,NaN
9218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.340562,NaN
9273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.318002,NaN
9275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.323531,NaN
9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.408179,NaN
9623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.434656,NaN

## XA

In [241]:
fwd_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

fwd_xa_data_tar = data_tar[data_tar['position'] == '4']
fwd_xa_data_tar = fwd_xa_data_tar[fwd_xa_features]
fwd_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)


fwd_xa_model = load_model_r('fwd_xa_model')  # No need to add `.pkl`

preds = predict_model_r(fwd_xa_model, data=fwd_xa_data_tar)

df_with_preds.loc[df_with_preds['position'] == '4', 'xa_pred'] = preds.loc[df_with_preds['position'] == '4', 'prediction_label']
df_with_preds[df_with_preds['position'] == '4']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.425041,0.069171
173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.437441,0.122415
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.385241,0.108631
423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.452713,0.066229
491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.386166,0.096075
758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.461185,0.101488
852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.436937,0.079875
1170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.377152,0.117892
1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.383336,0.080122
1540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.389733,0.068821
1586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.342779,0.117464
1801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.421375,0.070720
1969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.430819,0.125443
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.357535,0.073212
2236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.441902,0.091592
2665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.430540,0.095398
2698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.376718,0.095831
2746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.319202,0.086890
2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.399976,0.072027
2946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.427481,0.101443
2978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.442763,0.104508
3023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,NaN,0.425707,0.070836
3267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.422084,0.087350
3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,NaN,0.465412,0.118605
3736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.449852,0.098739
3840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.458567,0.083297
4423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.447005,0.109544
4840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.442294,0.103478
4918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.410936,0.102340
5115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.409343,0.091713
5337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,NaN,0.407218,0.108048
5366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.390196,0.123002
5672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.419211,0.080221
5760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.459046,0.084611
6064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,NaN,0.440760,0.091626
6155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.396114,0.086813
6355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.380370,0.097466
6390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.391567,0.074977
6795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.384828,0.101748
6854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.368600,0.098135
7044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.399842,0.071620
7202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.396794,0.071474
7752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.385070,0.096352
8042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,NaN,0.457727,0.109443
8203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.419515,0.069861
8220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,NaN,0.408833,0.074565
8494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.374169,0.100805
8566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.421769,0.124343
9018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.450402,0.083471
9204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.434415,0.061733
9218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.340562,0.105220
9273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,NaN,0.318002,0.094137
9275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,NaN,0.323531,0.091559
9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,NaN,0.408179,0.078502
9623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,NaN,0.434656,0.121141

## YC

In [242]:
fwd_yc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home',  'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers', 'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

fwd_yc_data_tar = data_tar[data_tar['position'] == '4']
fwd_yc_data_tar = fwd_yc_data_tar[fwd_yc_features]
fwd_yc_data_tar.drop(columns=['yellow_cards', 'position'], inplace=True)


fwd_yc_model = load_model_c('fwd_yc_model')  # No need to add `.pkl`

preds = predict_model_c(fwd_yc_model, data=fwd_yc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '4', 'yc_pred'] = preds.loc[df_with_preds['position'] == '4', 'prediction_label']
df_with_preds[df_with_preds['position'] == '4']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,0.0,0.425041,0.069171
173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,0.0,0.437441,0.122415
203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,0.0,0.385241,0.108631
423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,0.0,0.452713,0.066229
491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,0.0,0.386166,0.096075
758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,0.0,0.461185,0.101488
852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,0.0,0.436937,0.079875
1170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,0.0,0.377152,0.117892
1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,0.0,0.383336,0.080122
1540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,0.0,0.389733,0.068821
1586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,0.0,0.342779,0.117464
1801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,0.0,0.421375,0.070720
1969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,0.0,0.430819,0.125443
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,0.0,0.357535,0.073212
2236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,0.0,0.441902,0.091592
2665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.430540,0.095398
2698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.376718,0.095831
2746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.319202,0.086890
2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,0.0,0.399976,0.072027
2946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,0.0,0.427481,0.101443
2978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,0.0,0.442763,0.104508
3023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.695,0.188,0.117,NaN,NaN,NaN,0.0,0.425707,0.070836
3267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,0.0,0.422084,0.087350
3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.732,0.173,0.095,NaN,NaN,NaN,0.0,0.465412,0.118605
3736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,0.0,0.449852,0.098739
3840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,0.0,0.458567,0.083297
4423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,0.0,0.447005,0.109544
4840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,0.0,0.442294,0.103478
4918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,0.0,0.410936,0.102340
5115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,0.0,0.409343,0.091713
5337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.615,0.220,0.164,NaN,NaN,NaN,0.0,0.407218,0.108048
5366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,0.0,0.390196,0.123002
5672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,0.0,0.419211,0.080221
5760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,0.0,0.459046,0.084611
6064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.449,0.290,0.262,NaN,NaN,NaN,0.0,0.440760,0.091626
6155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,0.0,0.396114,0.086813
6355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,0.0,0.380370,0.097466
6390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,0.0,0.391567,0.074977
6795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,0.0,0.384828,0.101748
6854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,0.0,0.368600,0.098135
7044,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,0.0,0.399842,0.071620
7202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,0.0,0.396794,0.071474
7752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,0.0,0.385070,0.096352
8042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.187,0.216,0.596,NaN,NaN,NaN,0.0,0.457727,0.109443
8203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,0.0,0.419515,0.069861
8220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.542,0.243,0.215,NaN,NaN,NaN,0.0,0.408833,0.074565
8494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,0.0,0.374169,0.100805
8566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.421769,0.124343
9018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.450402,0.083471
9204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.434415,0.061733
9218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,0.0,0.340562,0.105220
9273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.441,0.263,0.296,NaN,NaN,NaN,0.0,0.318002,0.094137
9275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.703,0.187,0.110,NaN,NaN,NaN,0.0,0.323531,0.091559
9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.624,0.212,0.164,NaN,NaN,NaN,0.0,0.408179,0.078502
9623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.413,0.271,0.316,NaN,NaN,NaN,0.0,0.434656,0.121141

# Unified

In [243]:
def calc_xP_pred(row):
    # Minutes played bonus
    if row['minutes_3'] >= 60:
        minutes_bonus = 2
    elif row['minutes_3'] > 0:
        minutes_bonus = 1
    else:
        minutes_bonus = 0  # if player didn't play at all
    if row['position'] == '1':

        ## GK
        ## ---> >60  = 2
        ## ---> cs*4
        ## ---> ((sv)/3)*1
        ## ---> (gc/2)*-1
        ## ---> yc*-1
        return (
            minutes_bonus +
            4 * row['cs_pred'] +
            1 * round(row['saves_pred']/3, 3) -
            1 * round(row['xgc_pred']/2, 3) -
            1 * row['yc_pred']
        )

    elif row['position'] == '2':
        ## DEF
        ## ---> >60  = 2
        ## ---> xg*6
        ## ---> xa*3
        ## ---> cs*4
        ## ---> gc
        ## ---> yc*-1


        return (
            minutes_bonus +
            6 * row['xg_pred'] +
            3 * row['xa_pred'] +
            4 * row['cs_pred'] -
            1 * round(row['xgc_pred']/2, 3) -
            1 * row['yc_pred']
        )
    elif row['position'] == '3':
        ## MID
        ## ---> >60  = +2
        ## ---> xg*5
        ## ---> xa*3
        ## ---> cs*1
        ## ---> yc*-1
        return (
            minutes_bonus +
            5 * row['xg_pred'] +
            3 * row['xa_pred'] +
            1 * row['cs_pred'] -
            1 * row['yc_pred']
        )
    elif row['position'] == '4':
        ## FWD
        ## ---> >60  = 2
        ## ---> xg*4
        ## ---> xa*3
        ## ---> yc*-1
        return (
            minutes_bonus +
            4 * row['xg_pred'] +
            3 * row['xa_pred'] -
            1 * row['yc_pred']
        )
    else:
        return 0  # fallback for unknown positions


df_with_preds['xP_pred'] = df_with_preds.apply(calc_xP_pred, axis=1)

In [244]:
id_name_df = pd.read_csv('./fpl_understat_id_name.csv')

In [245]:
def add_player_name(row):
    # Check if fpl_id exists in id_name_df
    player_row = id_name_df[id_name_df['fpl_id'] == row['fpl_id']]
    if not player_row.empty:
        return player_row.iloc[0]['fpl_name']
    else:
        return None  # or some default value

df_with_preds['fpl_name'] = df_with_preds.apply(add_player_name, axis=1)

In [246]:
df_with_preds.to_csv('./player_points_preds.csv', index=False)

In [4]:
pd.read_csv('./player_points_preds.csv')

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred,xP_pred,fpl_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.106029,0.107377,2.852277,Reiss Nelson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,1.6800,0.0,0.042967,0.066550,0.617456,Ben Mee
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.106991,0.120347,2.895999,Christian Nørgaard
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.326897,0.097279,1.926321,Frank Onyeka
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,2.0238,0.0,0.053098,0.048532,1.452184,Ethan Pinnock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.116293,0.109255,1.909228,Mathias Jensen
513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,2.0468,0.0,0.050521,0.036949,0.390976,Kim Ji-soo
514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.353466,0.096049,3.055476,Yunus Emre Konak
515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.108523,0.115156,2.888084,Keane Lewis-Potter
516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.164,0.0,NaN,NaN,0.0,0.121334,0.126960,2.987550,Bryan Mbeumo