In [75]:
# For playing up to 60 minutes	1
# For playing 60 minutes or more (excluding stoppage time)	2
# For each goal scored by a goalkeeper	10
# For each goal scored by a defender	6
# For each goal scored by a midfielder	5
# For each goal scored by a forward	4
# For each goal assist	3
# For a clean sheet by a goalkeeper or defender	4
# For a clean sheet by a midfielder	1
# For every 3 shot saves by a goalkeeper	1
# For each penalty save	5
# For each penalty miss	-2
# Bonus points for the best players in a match	1-3
# For every 2 goals conceded by a goalkeeper or defender	-1
# For each yellow card	-1
# For each red card	-3
# For each own goal	-2

## GK
## ---> >60  = 2
## ---> cs*4
## ---> ((sv)/3)*1
## ---> gc
## ---> yc*-1


## DEF
## ---> >60  = 2
## ---> xg*6
## ---> xa*3
## ---> cs*4
## ---> gc
## ---> yc*-1


## MID
## ---> >60  = +2
## ---> xg*5
## ---> xa*3
## ---> cs*1
## ---> yc*-1


## FWD
## ---> >60  = 2
## ---> xg*4
## ---> xa*3
## ---> yc*-1

# Innit

In [76]:
import pandas as pd

from pycaret.regression import load_model as load_model_r, predict_model as predict_model_r
from pycaret.classification import load_model as load_model_c,  predict_model as predict_model_c

In [77]:
gw=35
data_22_23 = pd.read_csv('./data/joint/22-23/merged_player_data.csv',).dropna()
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv').dropna()
data_24_25 = pd.read_csv('./data/joint/24-25/merged_player_data.csv')
data_tar = data_24_25[data_24_25['event']==gw]
data_24_25_ = data_24_25[data_24_25['event'] != gw]

data = pd.concat([data_22_23, data_23_24, data_24_25_])

In [78]:
# Make a copy to avoid changing the original if needed
df_with_preds = data_tar.copy()

# GK

In [79]:
## GK
## ---> >60  = 2
## ---> cs*4
## ---> ((sv)/3)*1
## ---> gc
## ---> yc*-1

## CS

In [80]:
g_cs_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers', 'clean_sheets',
                 'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


g_cs_data_tar = data_tar[data_tar['position'] == '1']
g_cs_data_tar = g_cs_data_tar[g_cs_features]

g_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)

gk_cs_model = load_model_c('gk_cs_model')  # No need to add `.pkl`

preds = predict_model_c(gk_cs_model, data=g_cs_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'cs_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.667012,NaN,0.445,0.267,0.288,0.0
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.11,NaN,0.0,0.490482,NaN,0.423,0.266,0.310,0.0
688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.191176,NaN,0.338,0.258,0.404,0.0
775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15,0.15,NaN,0.0,-0.880597,NaN,0.338,0.258,0.404,0.0
875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,0.20,NaN,0.0,-0.213083,NaN,0.499,0.264,0.237,0.0
904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,0.17,NaN,0.0,-0.414562,NaN,0.499,0.264,0.237,0.0
1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.16,NaN,0.0,-0.397284,NaN,0.443,0.266,0.291,0.0
1856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.19,1.02,0.0,-0.910256,NaN,0.688,0.187,0.125,0.0
2499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.16,NaN,0.0,0.838385,NaN,0.597,0.247,0.156,0.0
2821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,0.20,NaN,0.0,-0.779167,NaN,0.538,0.248,0.214,0.0
3458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.03,0.98,0.0,-0.534247,NaN,0.597,0.247,0.156,0.0
3653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.04,NaN,0.0,0.698598,NaN,0.423,0.266,0.310,0.0
3818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.18,0.82,0.0,-0.868132,NaN,0.423,0.266,0.310,0.0
3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.159170,NaN,0.423,0.266,0.310,0.0
3951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.42,0.42,NaN,0.0,-0.387234,NaN,0.443,0.266,0.291,0.0
4258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.19,NaN,0.0,-0.264317,NaN,0.443,0.266,0.291,0.0
4673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.30,0.21,NaN,0.0,-0.639189,NaN,0.688,0.187,0.125,0.0
4908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,0.02,NaN,0.0,0.614156,NaN,0.688,0.187,0.125,0.0
5412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,0.14,NaN,0.0,-0.637864,NaN,0.565,0.233,0.203,0.0
5562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,0.17,NaN,0.0,-1.000000,NaN,0.423,0.266,0.310,0.0
5690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,0.00,2.68,0.0,-0.837431,NaN,0.338,0.258,0.404,0.0
6001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,0.02,NaN,0.0,-0.013282,NaN,0.338,0.258,0.404,0.0
6544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.04,NaN,0.0,0.407058,NaN,0.445,0.267,0.288,0.0
6810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.853211,NaN,0.423,0.266,0.310,0.0
6840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.10,0.50,0.0,-0.080000,NaN,0.423,0.266,0.310,0.0
6876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.36,0.30,NaN,0.0,0.139997,NaN,0.538,0.248,0.214,0.0
7029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.584906,NaN,0.416,0.260,0.325,0.0
7190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.34,0.34,2.98,0.0,-0.670886,NaN,0.416,0.260,0.325,0.0
7581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.19,NaN,0.0,-0.233959,NaN,0.416,0.260,0.325,0.0
7604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.131579,NaN,0.538,0.248,0.214,0.0
7671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,0.14,NaN,0.0,0.077934,NaN,0.416,0.260,0.325,0.0
7800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,0.09,1.80,0.0,-0.829679,NaN,0.416,0.260,0.325,0.0
8271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.04,NaN,0.0,0.034996,NaN,0.688,0.187,0.125,0.0
8462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.16,2.22,0.0,-0.875389,NaN,0.597,0.247,0.156,0.0
8762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.23,0.23,NaN,0.0,-0.917121,NaN,0.443,0.266,0.291,0.0
9915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.920000,NaN,0.443,0.266,0.291,0.0
10109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.414286,NaN,0.416,0.260,0.325,0.0
10157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,-0.847273,NaN,0.499,0.264,0.237,0.0
10278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.19,NaN,0.0,0.387205,NaN,0.597,0.247,0.156,0.0
10490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.10,1.14,0.0,-1.000000,NaN,0.499,0.264,0.237,0.0
10680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.10,NaN,0.0,0.357593,NaN,0.445,0.267,0.288,0.0

## Saves

In [81]:
g_saves_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_a_difficulty', 'team_h_difficulty', 'percenatge_net_transfers','ownership_change',

            'saves',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


g_saves_data_tar = data_tar[data_tar['position'] == '1']
g_saves_data_tar = g_saves_data_tar[g_saves_features]

gk_saves_model = load_model_r('gk_saves_model')  # No need to add `.pkl`

g_saves_data_tar.drop(columns=['position', 'saves'], inplace=True)

preds = predict_model_r(gk_saves_model, data=g_saves_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'saves_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.667012,NaN,0.445,0.267,0.288,0.0,2.833496
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,NaN,0.0,0.490482,NaN,0.423,0.266,0.310,0.0,3.008639
688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.191176,NaN,0.338,0.258,0.404,0.0,3.042252
775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15,NaN,0.0,-0.880597,NaN,0.338,0.258,0.404,0.0,2.948523
875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,NaN,0.0,-0.213083,NaN,0.499,0.264,0.237,0.0,3.032537
904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,NaN,0.0,-0.414562,NaN,0.499,0.264,0.237,0.0,3.157784
1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,NaN,0.0,-0.397284,NaN,0.443,0.266,0.291,0.0,2.758868
1856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,1.02,0.0,-0.910256,NaN,0.688,0.187,0.125,0.0,3.051776
2499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,NaN,0.0,0.838385,NaN,0.597,0.247,0.156,0.0,3.058469
2821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,NaN,0.0,-0.779167,NaN,0.538,0.248,0.214,0.0,2.897106
3458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,0.98,0.0,-0.534247,NaN,0.597,0.247,0.156,0.0,3.316561
3653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,NaN,0.0,0.698598,NaN,0.423,0.266,0.310,0.0,3.084603
3818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.82,0.0,-0.868132,NaN,0.423,0.266,0.310,0.0,3.113306
3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.159170,NaN,0.423,0.266,0.310,0.0,2.732153
3951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.42,NaN,0.0,-0.387234,NaN,0.443,0.266,0.291,0.0,3.023993
4258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,NaN,0.0,-0.264317,NaN,0.443,0.266,0.291,0.0,3.174751
4673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.21,NaN,0.0,-0.639189,NaN,0.688,0.187,0.125,0.0,2.662860
4908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,0.614156,NaN,0.688,0.187,0.125,0.0,2.766914
5412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,NaN,0.0,-0.637864,NaN,0.565,0.233,0.203,0.0,3.117009
5562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,NaN,0.0,-1.000000,NaN,0.423,0.266,0.310,0.0,2.522020
5690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,2.68,0.0,-0.837431,NaN,0.338,0.258,0.404,0.0,3.216765
6001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,-0.013282,NaN,0.338,0.258,0.404,0.0,2.744741
6544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,NaN,0.0,0.407058,NaN,0.445,0.267,0.288,0.0,3.060602
6810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.853211,NaN,0.423,0.266,0.310,0.0,3.130784
6840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.50,0.0,-0.080000,NaN,0.423,0.266,0.310,0.0,3.197951
6876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.30,NaN,0.0,0.139997,NaN,0.538,0.248,0.214,0.0,2.820325
7029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.584906,NaN,0.416,0.260,0.325,0.0,2.910086
7190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.34,2.98,0.0,-0.670886,NaN,0.416,0.260,0.325,0.0,3.152980
7581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,NaN,0.0,-0.233959,NaN,0.416,0.260,0.325,0.0,3.031269
7604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.131579,NaN,0.538,0.248,0.214,0.0,2.706712
7671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,NaN,0.0,0.077934,NaN,0.416,0.260,0.325,0.0,3.055617
7800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,1.80,0.0,-0.829679,NaN,0.416,0.260,0.325,0.0,2.867817
8271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,NaN,0.0,0.034996,NaN,0.688,0.187,0.125,0.0,3.116492
8462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,2.22,0.0,-0.875389,NaN,0.597,0.247,0.156,0.0,3.056716
8762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.23,NaN,0.0,-0.917121,NaN,0.443,0.266,0.291,0.0,3.149841
9915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.920000,NaN,0.443,0.266,0.291,0.0,3.541257
10109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.414286,NaN,0.416,0.260,0.325,0.0,2.856689
10157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.847273,NaN,0.499,0.264,0.237,0.0,3.043731
10278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,NaN,0.0,0.387205,NaN,0.597,0.247,0.156,0.0,3.182452
10490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,1.14,0.0,-1.000000,NaN,0.499,0.264,0.237,0.0,3.222572
10680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,NaN,0.0,0.357593,NaN,0.445,0.267,0.288,0.0,3.057255

## GC

In [82]:
g_xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'ownership_change', 'percenatge_net_transfers', 'team_h_difficulty', 'team_a_difficulty',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

g_xgc_data_tar = data_tar[data_tar['position'] == '1']

g_xgc_data_tar = g_xgc_data_tar[g_xgc_features]

g_xgc_data_tar.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

gk_xgc_model = load_model_r('gk_xgc_model')  # No need to add `.pkl`

preds = predict_model_r(gk_xgc_model, data=g_xgc_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'xgc_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.667012,NaN,0.445,0.267,0.288,0.0,2.833496,1.421886
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.490482,NaN,0.423,0.266,0.310,0.0,3.008639,1.520044
688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.191176,NaN,0.338,0.258,0.404,0.0,3.042252,1.406005
775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.880597,NaN,0.338,0.258,0.404,0.0,2.948523,1.256389
875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.213083,NaN,0.499,0.264,0.237,0.0,3.032537,1.196539
904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.414562,NaN,0.499,0.264,0.237,0.0,3.157784,1.576236
1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.397284,NaN,0.443,0.266,0.291,0.0,2.758868,1.308886
1856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.02,0.0,-0.910256,NaN,0.688,0.187,0.125,0.0,3.051776,1.914655
2499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.838385,NaN,0.597,0.247,0.156,0.0,3.058469,1.266174
2821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.779167,NaN,0.538,0.248,0.214,0.0,2.897106,1.523496
3458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.98,0.0,-0.534247,NaN,0.597,0.247,0.156,0.0,3.316561,1.770495
3653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.698598,NaN,0.423,0.266,0.310,0.0,3.084603,1.562558
3818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.82,0.0,-0.868132,NaN,0.423,0.266,0.310,0.0,3.113306,1.519374
3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.159170,NaN,0.423,0.266,0.310,0.0,2.732153,1.357512
3951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.387234,NaN,0.443,0.266,0.291,0.0,3.023993,1.256111
4258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.264317,NaN,0.443,0.266,0.291,0.0,3.174751,1.399317
4673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.639189,NaN,0.688,0.187,0.125,0.0,2.662860,1.277426
4908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.614156,NaN,0.688,0.187,0.125,0.0,2.766914,1.553179
5412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.637864,NaN,0.565,0.233,0.203,0.0,3.117009,1.553106
5562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-1.000000,NaN,0.423,0.266,0.310,0.0,2.522020,1.328117
5690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.68,0.0,-0.837431,NaN,0.338,0.258,0.404,0.0,3.216765,1.396284
6001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.013282,NaN,0.338,0.258,0.404,0.0,2.744741,1.011020
6544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.407058,NaN,0.445,0.267,0.288,0.0,3.060602,1.509881
6810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.853211,NaN,0.423,0.266,0.310,0.0,3.130784,1.355375
6840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,0.0,-0.080000,NaN,0.423,0.266,0.310,0.0,3.197951,1.495114
6876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.139997,NaN,0.538,0.248,0.214,0.0,2.820325,1.187568
7029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.584906,NaN,0.416,0.260,0.325,0.0,2.910086,1.294716
7190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.98,0.0,-0.670886,NaN,0.416,0.260,0.325,0.0,3.152980,1.383411
7581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.233959,NaN,0.416,0.260,0.325,0.0,3.031269,1.335763
7604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.131579,NaN,0.538,0.248,0.214,0.0,2.706712,1.409763
7671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.077934,NaN,0.416,0.260,0.325,0.0,3.055617,1.331951
7800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.80,0.0,-0.829679,NaN,0.416,0.260,0.325,0.0,2.867817,1.616941
8271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.034996,NaN,0.688,0.187,0.125,0.0,3.116492,1.558964
8462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.22,0.0,-0.875389,NaN,0.597,0.247,0.156,0.0,3.056716,1.493644
8762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.917121,NaN,0.443,0.266,0.291,0.0,3.149841,1.210518
9915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.920000,NaN,0.443,0.266,0.291,0.0,3.541257,1.380098
10109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.414286,NaN,0.416,0.260,0.325,0.0,2.856689,1.377726
10157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.847273,NaN,0.499,0.264,0.237,0.0,3.043731,1.467870
10278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.387205,NaN,0.597,0.247,0.156,0.0,3.182452,1.415533
10490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.14,0.0,-1.000000,NaN,0.499,0.264,0.237,0.0,3.222572,1.202108
10680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.357593,NaN,0.445,0.267,0.288,0.0,3.057255,1.356717

## YC

In [83]:
g_yc_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

                'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


g_yc_data_tar = data_tar[data_tar['position'] == '1']

g_yc_data_tar = g_yc_data_tar[g_yc_features]

g_yc_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)


gk_yc_model = load_model_c('gk_yc_model')  # No need to add `.pkl`

preds = predict_model_c(gk_yc_model, data=g_yc_data_tar)

# Only update the rows where position == 'GK'
df_with_preds.loc[df_with_preds['position'] == '1', 'yc_pred'] = preds.loc[df_with_preds['position'] == '1', 'prediction_label']
df_with_preds[df_with_preds['position'] == '1']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.667012,NaN,0.445,0.267,0.288,0.0,2.833496,1.421886,0.0
683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.490482,NaN,0.423,0.266,0.310,0.0,3.008639,1.520044,0.0
688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.191176,NaN,0.338,0.258,0.404,0.0,3.042252,1.406005,0.0
775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.880597,NaN,0.338,0.258,0.404,0.0,2.948523,1.256389,0.0
875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.213083,NaN,0.499,0.264,0.237,0.0,3.032537,1.196539,0.0
904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.414562,NaN,0.499,0.264,0.237,0.0,3.157784,1.576236,0.0
1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.397284,NaN,0.443,0.266,0.291,0.0,2.758868,1.308886,0.0
1856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.910256,NaN,0.688,0.187,0.125,0.0,3.051776,1.914655,0.0
2499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.838385,NaN,0.597,0.247,0.156,0.0,3.058469,1.266174,0.0
2821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.779167,NaN,0.538,0.248,0.214,0.0,2.897106,1.523496,0.0
3458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.534247,NaN,0.597,0.247,0.156,0.0,3.316561,1.770495,0.0
3653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.698598,NaN,0.423,0.266,0.310,0.0,3.084603,1.562558,0.0
3818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.868132,NaN,0.423,0.266,0.310,0.0,3.113306,1.519374,0.0
3885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.159170,NaN,0.423,0.266,0.310,0.0,2.732153,1.357512,0.0
3951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.387234,NaN,0.443,0.266,0.291,0.0,3.023993,1.256111,0.0
4258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.264317,NaN,0.443,0.266,0.291,0.0,3.174751,1.399317,0.0
4673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.639189,NaN,0.688,0.187,0.125,0.0,2.662860,1.277426,0.0
4908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.614156,NaN,0.688,0.187,0.125,0.0,2.766914,1.553179,0.0
5412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.637864,NaN,0.565,0.233,0.203,0.0,3.117009,1.553106,0.0
5562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-1.000000,NaN,0.423,0.266,0.310,0.0,2.522020,1.328117,0.0
5690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.837431,NaN,0.338,0.258,0.404,0.0,3.216765,1.396284,0.0
6001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.013282,NaN,0.338,0.258,0.404,0.0,2.744741,1.011020,0.0
6544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.407058,NaN,0.445,0.267,0.288,0.0,3.060602,1.509881,0.0
6810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.853211,NaN,0.423,0.266,0.310,0.0,3.130784,1.355375,0.0
6840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.080000,NaN,0.423,0.266,0.310,0.0,3.197951,1.495114,0.0
6876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.139997,NaN,0.538,0.248,0.214,0.0,2.820325,1.187568,0.0
7029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.584906,NaN,0.416,0.260,0.325,0.0,2.910086,1.294716,0.0
7190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.670886,NaN,0.416,0.260,0.325,0.0,3.152980,1.383411,0.0
7581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.233959,NaN,0.416,0.260,0.325,0.0,3.031269,1.335763,0.0
7604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.131579,NaN,0.538,0.248,0.214,0.0,2.706712,1.409763,0.0
7671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.077934,NaN,0.416,0.260,0.325,0.0,3.055617,1.331951,0.0
7800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.829679,NaN,0.416,0.260,0.325,0.0,2.867817,1.616941,0.0
8271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.034996,NaN,0.688,0.187,0.125,0.0,3.116492,1.558964,0.0
8462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.875389,NaN,0.597,0.247,0.156,0.0,3.056716,1.493644,0.0
8762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.917121,NaN,0.443,0.266,0.291,0.0,3.149841,1.210518,0.0
9915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.920000,NaN,0.443,0.266,0.291,0.0,3.541257,1.380098,0.0
10109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.414286,NaN,0.416,0.260,0.325,0.0,2.856689,1.377726,0.0
10157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-0.847273,NaN,0.499,0.264,0.237,0.0,3.043731,1.467870,0.0
10278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.387205,NaN,0.597,0.247,0.156,0.0,3.182452,1.415533,0.0
10490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,-1.000000,NaN,0.499,0.264,0.237,0.0,3.222572,1.202108,0.0
10680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.357593,NaN,0.445,0.267,0.288,0.0,3.057255,1.356717,0.0

# Def

In [84]:
## DEF
## ---> >60  = 2
## ---> xg*6
## ---> xa*3
## ---> cs*4
## ---> gc
## ---> yc*-1

## XG

In [85]:
def_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


def_xg_data_tar = data_tar[data_tar['position'] == '2']
def_xg_data_tar = def_xg_data_tar[def_xg_features]
def_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)


def_xg_model = load_model_r('def_xg_model')  # No need to add `.pkl`

preds = predict_model_r(def_xg_model, data=def_xg_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'xg_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,percenatge_net_transfers,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.136842,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.043708
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.142857,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.054112
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.000000,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.057042
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.584597,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.045757
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.455043,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.056808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.427984,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.053330
10546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.377778,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.060499
10581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.639774,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.045720
10683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.591837,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.071631
10742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.600000,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.050986

## XA

In [86]:
def_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence',
                   'creativity', 'threat', 'red_cards', 'yellow_cards', 'starts',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


def_xa_data_tar = data_tar[data_tar['position'] == '2']
def_xa_data_tar = def_xa_data_tar[def_xa_features]
def_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)

def_xa_model = load_model_r('def_xa_model')  # No need to add `.pkl`

preds = predict_model_r(def_xa_model, data=def_xa_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'xa_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.043708,0.066550
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.054112,0.048532
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.057042,0.078002
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.045757,0.048547
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.056808,0.046172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.053330,0.057329
10546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.060499,0.071840
10581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.045720,0.047725
10683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.071631,0.029231
10742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.050986,0.036949

## CS

In [87]:
d_cs_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
                'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


def_cs_data_tar = data_tar[data_tar['position'] == '2']

def_cs_data_tar = def_cs_data_tar[d_cs_features]

def_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)

def_cs_model = load_model_c('def_cs_model')  # No need to add `.pkl`

preds = predict_model_c(def_cs_model, data=def_cs_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'cs_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.043708,0.066550
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.054112,0.048532
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.057042,0.078002
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,0.0,NaN,NaN,NaN,0.045757,0.048547
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,0.0,NaN,NaN,NaN,0.056808,0.046172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,0.0,NaN,NaN,NaN,0.053330,0.057329
10546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.060499,0.071840
10581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.045720,0.047725
10683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.071631,0.029231
10742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.050986,0.036949

## GC

In [88]:
def_xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3',  'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]


def_xgc_data_tar = data_tar[data_tar['position'] == '2']
def_xgc_data_tar = def_xgc_data_tar[def_xgc_features]
def_xgc_data_tar.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

def_xgc_model = load_model_r('def_xgc_model')  # No need to add `.pkl`

preds = predict_model_r(def_xgc_model, data=def_xgc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'xgc_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.3741,NaN,0.043708,0.066550
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.4739,NaN,0.054112,0.048532
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.4890,NaN,0.057042,0.078002
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,0.0,NaN,1.4534,NaN,0.045757,0.048547
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,0.0,NaN,1.5611,NaN,0.056808,0.046172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,0.0,NaN,1.7265,NaN,0.053330,0.057329
10546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.5137,NaN,0.060499,0.071840
10581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.1873,NaN,0.045720,0.047725
10683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.2467,NaN,0.071631,0.029231
10742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.4424,NaN,0.050986,0.036949

## YC

In [89]:
def_yc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

            'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

def_yc_data_tar = data_tar[data_tar['position'] == '2']


def_yc_data_tar = def_yc_data_tar[def_yc_features]
def_yc_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)

def_yc_model = load_model_c('def_yc_model')  # No need to add `.pkl`
preds = predict_model_c(def_yc_model, data=def_yc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '2', 'yc_pred'] = preds.loc[df_with_preds['position'] == '2', 'prediction_label']
df_with_preds[df_with_preds['position'] == '2']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.3741,0.0,0.043708,0.066550
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.4739,0.0,0.054112,0.048532
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.4890,0.0,0.057042,0.078002
381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,0.0,NaN,1.4534,0.0,0.045757,0.048547
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,0.0,NaN,1.5611,0.0,0.056808,0.046172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,0.0,NaN,1.7265,0.0,0.053330,0.057329
10546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.5137,0.0,0.060499,0.071840
10581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.1873,0.0,0.045720,0.047725
10683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.2467,0.0,0.071631,0.029231
10742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,1.4424,0.0,0.050986,0.036949

# Mid

In [90]:
## MID
## ---> >60  = +2
## ---> xg*5
## ---> xa*3
## ---> cs*1
## ---> yc*-1

## XG

In [91]:
mid_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

mid_xg_data_tar = data_tar[data_tar['position'] == '3']
mid_xg_data_tar = mid_xg_data_tar[mid_xg_features]
mid_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)


mid_xg_model = load_model_r('mid_xg_model')  # No need to add `.pkl`

preds = predict_model_r(mid_xg_model, data=mid_xg_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'xg_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.106029,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.112786,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.326897,NaN
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.100586,NaN
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.167479,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.113278,NaN
10738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.111856,NaN
10751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.349450,NaN
10786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.113861,NaN
10821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.139014,NaN

## XA

In [92]:
mid_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

mid_xa_data_tar = data_tar[data_tar['position'] == '3']
mid_xa_data_tar = mid_xa_data_tar[mid_xa_features]
mid_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)


mid_xa_model = load_model_r('mid_xa_model')  # No need to add `.pkl`

preds = predict_model_r(mid_xa_model, data=mid_xa_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'xa_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.106029,0.103388
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.112786,0.112894
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.326897,0.092516
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.100586,0.121210
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.167479,0.098585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.113278,0.109653
10738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.111856,0.097132
10751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.349450,0.095933
10786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.113861,0.103210
10821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.139014,0.246531

## CS

In [93]:
mid_cs_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
                 'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

mid_cs_data_tar = data_tar[data_tar['position'] == '3']
mid_cs_data_tar = mid_cs_data_tar[mid_cs_features]
mid_cs_data_tar.drop(columns=['clean_sheets', 'position'], inplace=True)


mid_cs_model = load_model_c('mid_cs_model')  # No need to add `.pkl`

preds = predict_model_c(mid_cs_model, data=mid_cs_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'cs_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,0.0,NaN,NaN,NaN,0.106029,0.103388
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.112786,0.112894
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.326897,0.092516
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.100586,0.121210
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.167479,0.098585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.113278,0.109653
10738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.111856,0.097132
10751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.349450,0.095933
10786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.113861,0.103210
10821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,NaN,0.139014,0.246531

## YC

In [94]:
mid_yc_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
            'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

mid_yc_data_tar = data_tar[data_tar['position'] == '3']
mid_yc_data_tar = mid_yc_data_tar[mid_yc_features]
mid_yc_data_tar.drop(columns=['yellow_cards', 'position'], inplace=True)


mid_yc_model = load_model_c('mid_yc_model')  # No need to add `.pkl`

preds = predict_model_c(mid_yc_model, data=mid_yc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '3', 'yc_pred'] = preds.loc[df_with_preds['position'] == '3', 'prediction_label']
df_with_preds[df_with_preds['position'] == '3']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,0.0,NaN,NaN,0.0,0.106029,0.103388
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.112786,0.112894
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.326897,0.092516
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.100586,0.121210
240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.167479,0.098585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.113278,0.109653
10738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.111856,0.097132
10751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.349450,0.095933
10786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.113861,0.103210
10821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,0.0,NaN,NaN,0.0,0.139014,0.246531

# Fwd

In [95]:
## FWD
## ---> >60  = 2
## ---> xg*4
## ---> xa*3
## ---> yc*-1

## XG

In [96]:
fwd_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',


            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

fwd_xg_data_tar = data_tar[data_tar['position'] == '4']
fwd_xg_data_tar = fwd_xg_data_tar[fwd_xg_features]
fwd_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)


fwd_xg_model = load_model_r('fwd_xg_model')  # No need to add `.pkl`

preds = predict_model_r(fwd_xg_model, data=fwd_xg_data_tar)

df_with_preds.loc[df_with_preds['position'] == '4', 'xg_pred'] = preds.loc[df_with_preds['position'] == '4', 'prediction_label']
df_with_preds[df_with_preds['position'] == '4']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.425311,NaN
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.417282,NaN
455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.410914,NaN
529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.286660,NaN
817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.393154,NaN
921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.405030,NaN
1270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.380648,NaN
1341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.451697,NaN
1717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.344694,NaN
2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.433088,NaN
2191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.357368,NaN
2430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.423896,NaN
2896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.386633,NaN
2932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.443580,NaN
2982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.319960,NaN
3051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.399202,NaN
3198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.443884,NaN
3233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.435253,NaN
3283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.410248,NaN
3549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.404320,NaN
3863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.428727,NaN
4052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.403946,NaN
4169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.381489,NaN
4796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.446999,NaN
5244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.565,0.233,0.203,NaN,NaN,NaN,NaN,0.423944,NaN
5329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.413068,NaN
5543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.565,0.233,0.203,NaN,NaN,NaN,NaN,0.454706,NaN
5782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.409156,NaN
5815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.433289,NaN
6166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.422060,NaN
6257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.397490,NaN
6582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.433107,NaN
6683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.392304,NaN
6901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.416626,NaN
6943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.449597,NaN
7380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.341814,NaN
7445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.367499,NaN
7646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.398231,NaN
7816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.395165,NaN
8414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.447594,NaN
8724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.349120,NaN
8898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.349689,NaN
8916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.419862,NaN
9216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.372999,NaN
9293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.397678,NaN
9779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.451238,NaN
9977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.431353,NaN
9993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.340552,NaN
10052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.318876,NaN
10054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.325637,NaN
10231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.415292,NaN
10457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.456520,NaN

## XA

In [97]:
fwd_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

fwd_xa_data_tar = data_tar[data_tar['position'] == '4']
fwd_xa_data_tar = fwd_xa_data_tar[fwd_xa_features]
fwd_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)


fwd_xa_model = load_model_r('fwd_xa_model')  # No need to add `.pkl`

preds = predict_model_r(fwd_xa_model, data=fwd_xa_data_tar)

df_with_preds.loc[df_with_preds['position'] == '4', 'xa_pred'] = preds.loc[df_with_preds['position'] == '4', 'prediction_label']
df_with_preds[df_with_preds['position'] == '4']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.425311,0.069171
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.417282,0.090212
455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.410914,0.062609
529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.286660,0.082176
817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.393154,0.143321
921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.405030,0.092983
1270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.380648,0.117892
1341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.451697,0.104479
1717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.344694,0.117464
2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.433088,0.091953
2191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.357368,0.073212
2430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.423896,0.111637
2896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.386633,0.117055
2932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.443580,0.100582
2982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.319960,0.086890
3051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.399202,0.072027
3198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.443884,0.111291
3233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.435253,0.081013
3283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,NaN,0.410248,0.079208
3549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.404320,0.089665
3863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.428727,0.120320
4052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.403946,0.088247
4169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.381489,0.098851
4796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.446999,0.109544
5244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.565,0.233,0.203,NaN,NaN,NaN,NaN,0.423944,0.097133
5329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.413068,0.102340
5543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.565,0.233,0.203,NaN,NaN,NaN,NaN,0.454706,0.075347
5782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.409156,0.108048
5815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.433289,0.122238
6166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.422060,0.066809
6257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.397490,0.073006
6582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,NaN,0.433107,0.113880
6683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.392304,0.086813
6901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.416626,0.114861
6943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,NaN,0.449597,0.095374
7380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.341814,0.104178
7445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.367499,0.098135
7646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.398231,0.071620
7816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.395165,0.071474
8414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.447594,0.125302
8724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,NaN,0.349120,0.056059
8898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.349689,0.078605
8916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,NaN,0.419862,0.069200
9216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.372999,0.100805
9293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.397678,0.114527
9779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.451238,0.083471
9977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.431353,0.068480
9993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.340552,0.105220
10052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,NaN,0.318876,0.094137
10054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,NaN,0.325637,0.091559
10231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,NaN,0.415292,0.101933
10457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,NaN,0.456520,0.106170

## YC

In [98]:
fwd_yc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home',  'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers', 'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

fwd_yc_data_tar = data_tar[data_tar['position'] == '4']
fwd_yc_data_tar = fwd_yc_data_tar[fwd_yc_features]
fwd_yc_data_tar.drop(columns=['yellow_cards', 'position'], inplace=True)


fwd_yc_model = load_model_c('fwd_yc_model')  # No need to add `.pkl`

preds = predict_model_c(fwd_yc_model, data=fwd_yc_data_tar)

df_with_preds.loc[df_with_preds['position'] == '4', 'yc_pred'] = preds.loc[df_with_preds['position'] == '4', 'prediction_label']
df_with_preds[df_with_preds['position'] == '4']

Transformation Pipeline and Model Successfully Loaded

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,pts_bps,whh,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,0.0,0.425311,0.069171
212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,0.0,0.417282,0.090212
455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,0.0,0.410914,0.062609
529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,0.0,0.286660,0.082176
817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,0.0,0.393154,0.143321
921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.405030,0.092983
1270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,0.0,0.380648,0.117892
1341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,0.0,0.451697,0.104479
1717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,0.0,0.344694,0.117464
2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.433088,0.091953
2191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.357368,0.073212
2430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.423896,0.111637
2896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,0.0,0.386633,0.117055
2932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,0.0,0.443580,0.100582
2982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,0.0,0.319960,0.086890
3051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.399202,0.072027
3198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.443884,0.111291
3233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,0.0,0.435253,0.081013
3283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.597,0.247,0.156,NaN,NaN,NaN,0.0,0.410248,0.079208
3549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,0.0,0.404320,0.089665
3863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,0.0,0.428727,0.120320
4052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,0.0,0.403946,0.088247
4169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,0.0,0.381489,0.098851
4796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,0.0,0.446999,0.109544
5244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.565,0.233,0.203,NaN,NaN,NaN,0.0,0.423944,0.097133
5329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,0.0,0.413068,0.102340
5543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.565,0.233,0.203,NaN,NaN,NaN,0.0,0.454706,0.075347
5782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,0.0,0.409156,0.108048
5815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,0.0,0.433289,0.122238
6166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,0.0,0.422060,0.066809
6257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,0.0,0.397490,0.073006
6582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.445,0.267,0.288,NaN,NaN,NaN,0.0,0.433107,0.113880
6683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,0.0,0.392304,0.086813
6901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,0.0,0.416626,0.114861
6943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.423,0.266,0.310,NaN,NaN,NaN,0.0,0.449597,0.095374
7380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.341814,0.104178
7445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.367499,0.098135
7646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.398231,0.071620
7816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.395165,0.071474
8414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,0.0,0.447594,0.125302
8724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.538,0.248,0.214,NaN,NaN,NaN,0.0,0.349120,0.056059
8898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.349689,0.078605
8916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.338,0.258,0.404,NaN,NaN,NaN,0.0,0.419862,0.069200
9216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.372999,0.100805
9293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,0.0,0.397678,0.114527
9779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,0.0,0.451238,0.083471
9977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,0.0,0.431353,0.068480
9993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,0.0,0.340552,0.105220
10052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.499,0.264,0.237,NaN,NaN,NaN,0.0,0.318876,0.094137
10054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.443,0.266,0.291,NaN,NaN,NaN,0.0,0.325637,0.091559
10231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.688,0.187,0.125,NaN,NaN,NaN,0.0,0.415292,0.101933
10457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.416,0.260,0.325,NaN,NaN,NaN,0.0,0.456520,0.106170

# Unified

In [99]:
def calc_xP_pred(row):
    # Minutes played bonus
    if row['minutes_3'] >= 60:
        minutes_bonus = 2
    elif row['minutes_3'] > 0:
        minutes_bonus = 1
    else:
        minutes_bonus = 0  # if player didn't play at all
    if row['position'] == '1':

        ## GK
        ## ---> >60  = 2
        ## ---> cs*4
        ## ---> ((sv)/3)*1
        ## ---> (gc/2)*-1
        ## ---> yc*-1
        return (
            minutes_bonus +
            4 * row['cs_pred'] +
            1 * round(row['saves_pred']/3, 3) -
            1 * round(row['xgc_pred']/2, 3) -
            1 * row['yc_pred']
        )

    elif row['position'] == '2':
        ## DEF
        ## ---> >60  = 2
        ## ---> xg*6
        ## ---> xa*3
        ## ---> cs*4
        ## ---> gc
        ## ---> yc*-1


        return (
            minutes_bonus +
            6 * row['xg_pred'] +
            3 * row['xa_pred'] +
            4 * row['cs_pred'] -
            1 * round(row['xgc_pred']/2, 3) -
            1 * row['yc_pred']
        )
    elif row['position'] == '3':
        ## MID
        ## ---> >60  = +2
        ## ---> xg*5
        ## ---> xa*3
        ## ---> cs*1
        ## ---> yc*-1
        return (
            minutes_bonus +
            5 * row['xg_pred'] +
            3 * row['xa_pred'] +
            1 * row['cs_pred'] -
            1 * row['yc_pred']
        )
    elif row['position'] == '4':
        ## FWD
        ## ---> >60  = 2
        ## ---> xg*4
        ## ---> xa*3
        ## ---> yc*-1
        return (
            minutes_bonus +
            4 * row['xg_pred'] +
            3 * row['xa_pred'] -
            1 * row['yc_pred']
        )
    else:
        return 0  # fallback for unknown positions


df_with_preds['xP_pred'] = df_with_preds.apply(calc_xP_pred, axis=1)

In [100]:
id_name_df = pd.read_csv('./fpl_understat_id_name.csv')

In [101]:
def add_player_name(row):
    # Check if fpl_id exists in id_name_df
    player_row = id_name_df[id_name_df['fpl_id'] == row['fpl_id']]
    if not player_row.empty:
        return player_row.iloc[0]['fpl_name']
    else:
        return None  # or some default value

df_with_preds['fpl_name'] = df_with_preds.apply(add_player_name, axis=1)

In [105]:
df_with_preds['xg_pred']

12       0.106029
20       0.043708
51       0.112786
63       0.326897
87       0.054112
           ...
10738    0.111856
10742    0.050986
10751    0.349450
10786    0.113861
10821    0.139014
Name: xg_pred, Length: 489, dtype: float64

In [102]:
df_with_preds.to_csv('./player_points_preds.csv', index=False)

In [103]:
v = pd.read_csv('./player_points_preds.csv')
v[v['position'] == 1]

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,whd,wha,cs_pred,saves_pred,xgc_pred,yc_pred,xg_pred,xa_pred,xP_pred,fpl_name
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.267,0.288,0.0,2.833496,1.421886,0.0,NaN,NaN,0.233,Hákon Valdimarsson
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,3.008639,1.520044,0.0,NaN,NaN,2.243,Aaron Ramsdale
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.258,0.404,0.0,3.042252,1.406005,0.0,NaN,NaN,0.311,Jason Steele
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.258,0.404,0.0,2.948523,1.256389,0.0,NaN,NaN,2.355,Bart Verbruggen
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.264,0.237,0.0,3.032537,1.196539,0.0,NaN,NaN,2.413,David Raya Martin
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.264,0.237,0.0,3.157784,1.576236,0.0,NaN,NaN,2.265,Kepa Arrizabalaga
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.291,0.0,2.758868,1.308886,0.0,NaN,NaN,2.266,Robert Sánchez
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.187,0.125,0.0,3.051776,1.914655,0.0,NaN,NaN,2.060,Sam Johnstone
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.247,0.156,0.0,3.058469,1.266174,0.0,NaN,NaN,2.386,Jordan Pickford
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.248,0.214,0.0,2.897106,1.523496,0.0,NaN,NaN,2.204,Bernd Leno
133,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.247,0.156,0.0,3.316561,1.770495,0.0,NaN,NaN,2.221,Christian Walton
142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,3.084603,1.562558,0.0,NaN,NaN,2.247,Mads Hermansen
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,3.113306,1.519374,0.0,NaN,NaN,2.278,Jakub Stolarczyk
153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,2.732153,1.357512,0.0,NaN,NaN,0.232,Danny Ward
156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.291,0.0,3.023993,1.256111,0.0,NaN,NaN,2.380,Alisson Ramses Becker
169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.291,0.0,3.174751,1.399317,0.0,NaN,NaN,2.358,Caoimhin Kelleher
184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.187,0.125,0.0,2.662860,1.277426,0.0,NaN,NaN,2.249,Ederson Santana de Moraes
194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.187,0.125,0.0,2.766914,1.553179,0.0,NaN,NaN,2.145,Stefan Ortega Moreno
217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.233,0.203,0.0,3.117009,1.553106,0.0,NaN,NaN,2.262,André Onana
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,2.522020,1.328117,0.0,NaN,NaN,0.177,Joe Gauci
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.258,0.404,0.0,3.216765,1.396284,0.0,NaN,NaN,2.374,Martin Dúbravka
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.258,0.404,0.0,2.744741,1.011020,0.0,NaN,NaN,2.409,Nick Pope
264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.267,0.288,0.0,3.060602,1.509881,0.0,NaN,NaN,2.265,Matz Sels
279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,3.130784,1.355375,0.0,NaN,NaN,2.366,Joe Lumley
281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.310,0.0,3.197951,1.495114,0.0,NaN,NaN,2.318,Alex McCarthy
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.248,0.214,0.0,2.820325,1.187568,0.0,NaN,NaN,2.346,Emiliano Martínez Romero
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.260,0.325,0.0,2.910086,1.294716,0.0,NaN,NaN,0.323,Brandon Austin
298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.260,0.325,0.0,3.152980,1.383411,0.0,NaN,NaN,2.359,Fraser Forster
316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.260,0.325,0.0,3.031269,1.335763,0.0,NaN,NaN,2.342,Guglielmo Vicario
318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.248,0.214,0.0,2.706712,1.409763,0.0,NaN,NaN,2.197,Robin Olsen
321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.260,0.325,0.0,3.055617,1.331951,0.0,NaN,NaN,2.353,Alphonse Areola
328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.260,0.325,0.0,2.867817,1.616941,0.0,NaN,NaN,2.148,Łukasz Fabiański
346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.187,0.125,0.0,3.116492,1.558964,0.0,NaN,NaN,2.260,José Malheiro de Sá
355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.247,0.156,0.0,3.056716,1.493644,0.0,NaN,NaN,2.272,Arijanet Muric
368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.291,0.0,3.149841,1.210518,0.0,NaN,NaN,2.445,Filip Jørgensen
428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.266,0.291,0.0,3.541257,1.380098,0.0,NaN,NaN,0.490,Vítezslav Jaros
448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.260,0.325,0.0,2.856689,1.377726,0.0,NaN,NaN,2.263,Antonín Kinsky
454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.264,0.237,0.0,3.043731,1.467870,0.0,NaN,NaN,0.281,Norberto Murara Neto
463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.247,0.156,0.0,3.182452,1.415533,0.0,NaN,NaN,2.353,Alex Palmer
475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.264,0.237,0.0,3.222572,1.202108,0.0,NaN,NaN,2.473,Mark Travers
481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.267,0.288,0.0,3.057255,1.356717,0.0,NaN,NaN,2.341,Mark Flekken