In [1]:
import pandas as pd
from pycaret.regression import *

In [2]:
## GK
## ---> >60  = 2
## ---> cs*4
## ---> ((sv)/3)*1
## ---> gc
## ---> yc*-1


## DEF
## ---> >60  = 2
## ---> xg*6
## ---> xa*3
## ---> cs*4
## ---> gc
## ---> yc*-1


## MID
## ---> >60  = +2
## ---> xg*5
## ---> xa*3
## ---> cs*1
## ---> yc*-1


## FWD
## ---> >60  = 2
## ---> xg*4
## ---> xa*3
## ---> yc*-1

In [2]:
gw=35
data_22_23 = pd.read_csv('./data/joint/22-23/merged_player_data.csv',).dropna()
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv').dropna()
data_24_25 = pd.read_csv('./data/joint/24-25/merged_player_data.csv')
data_tar = data_24_25[data_24_25['event']==gw]
data_24_25_ = data_24_25[data_24_25['event'] != gw]

data = pd.concat([data_22_23, data_23_24, data_24_25_])

In [5]:
features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'ownership_change', 'percenatge_net_transfers',

            'clean_sheets', 'expected_assists', 'expected_goal_involvements', 'expected_goals', 'expected_goals_conceded', 'goals_conceded', 'goals_scored', 'ict_index',
            'influence', 'creativity', 'threat', 'minutes', 'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards', 'yellow_cards', 'saves', 'starts',
            'team_a_score', 'team_h_score', 'total_points', 'goals', 'shots', 'xG', 'xA', 'assists_x', 'assists_y', 'key_passes', 'npg', 'npxG', 'xGChain',  'xGBuildup',  'xP',

            'clean_sheets_1', 'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_missed_1', 'penalties_saved_1', 'red_cards_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1', 'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1',
            'xGBuildup_1',  'xP_1',

            'clean_sheets_2', 'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'goals_scored_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_missed_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2', 'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2',
            'xGBuildup_2',  'xP_2',

            'clean_sheets_3', 'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'goals_scored_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_missed_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3', 'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3',
            'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'goals_scored_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_missed_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4', 'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4',
            'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'goals_scored_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_missed_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5', 'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5',
            'xGBuildup_5',  'xP_5'
                        ]

# Goals

## Def

In [58]:
def_xg_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

In [ ]:

def_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'DEF')]
def_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '2')]

def_xg_data = def_data[def_xg_features]
def_xg_data_tar = def_data_tar[def_xg_features]

def_data.reset_index(drop=True, inplace=True)
def_xg_data.reset_index(drop=True, inplace=True)

def_xg_data.drop(columns=['position'], inplace=True)
def_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

def_xg_model = setup(def_xg_data, target = 'xG')

In [1]:
# Get feature selection results
selected_features = def_xg_model.get_config('X_train').columns.tolist()
print("Selected features:", selected_features)

NameError: name 'def_xg_model' is not defined

In [62]:
def_xg_best = def_xg_model.compare_models()

In [63]:
def_xg_best

BayesianRidge()

In [64]:
def_xg_model.evaluate_model(def_xg_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [65]:
preds = def_xg_model.predict_model(def_xg_best, data=def_xg_data_tar)

preds.rename(columns={'prediction_label': 'xG_pred'}, inplace=True)

def_xg_preds = preds[['xG_pred']]
def_xg_preds

def_data_tar = pd.concat([def_data_tar, def_xg_preds], axis=1)
def_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xG_pred
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.18,0.15,NaN,0.0,-0.391304,NaN,0.615,0.220,0.164,0.053098
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,0.50,NaN,0.0,0.581669,NaN,0.732,0.173,0.095,0.052009
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.23,0.23,NaN,0.0,0.791684,NaN,0.732,0.173,0.095,0.052305
464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.31,0.28,1.06,0.0,-0.857143,NaN,0.732,0.173,0.095,0.048036
531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,0.06,NaN,0.0,-0.991079,NaN,0.732,0.173,0.095,0.047639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.40,0.40,NaN,0.0,-0.284188,NaN,0.624,0.212,0.164,0.061114
9566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.12,0.09,NaN,0.0,0.739250,NaN,0.615,0.220,0.164,0.050883
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.04,NaN,0.0,-0.600945,NaN,0.441,0.263,0.296,0.053068
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.02,NaN,0.0,0.053381,NaN,0.615,0.220,0.164,0.045786
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,0.03,NaN,0.0,-0.330801,NaN,0.615,0.220,0.164,0.055800

In [67]:
save_model(def_xg_best, model_name='def_xg_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'expected_assists_1',
                                              'expected_goal_involvements_1',
                                              'expected_goals_1',
                                              'goals_scored_1', 'ict_index_1',
                                              'influence_1', 'creativity_1',
                                              'threat_1', 'minutes_1',
                                              'red_cards_1', 'yellow_cards_1',
                                              'starts_1', 'team_a_score_1',
                                              'team_h_score_1', 'total_points_1',
                                              'goals_1', 'shots_1', 'xG_1',
                                              'xA_1', 'assists_x_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model', BayesianRidge())]),
 'def_xg_model.pkl')

## Mid

In [76]:
m_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

In [77]:

mid_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'MID')]
mid_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '3')]

mid_xg_data = mid_data[m_features]
mid_xg_data_tar = mid_data_tar[m_features]

mid_data.reset_index(drop=True, inplace=True)
mid_xg_data.reset_index(drop=True, inplace=True)

mid_xg_data.drop(columns=['position'], inplace=True)
mid_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

mid_xg_data

,xG,whh,whd,wha,was_home,team_h_difficulty,team_a_difficulty,percenatge_net_transfers,ict_index,influence,...,xG_5,xA_5,assists_x_5,assists_y_5,key_passes_5,npg_5,npxG_5,xGChain_5,xGBuildup_5,xP_5
0,0.107095,0.378,0.296,0.326,True,2.0,2.0,0.687526,4.8,10.6,...,0.08,0.03,0.0,0.0,0.6,0.0,0.08,0.15,0.05,0.80
1,0.000000,0.713,0.188,0.099,False,2.0,4.0,0.687526,2.7,5.8,...,0.11,0.05,0.0,0.0,0.8,0.0,0.11,0.19,0.05,1.42
2,0.590692,0.359,0.314,0.327,False,2.0,2.0,-0.828125,12.2,45.8,...,0.09,0.08,0.0,0.0,1.2,0.0,0.09,0.34,0.18,1.90
3,0.000000,0.359,0.294,0.348,True,3.0,2.0,0.151261,3.2,18.4,...,0.14,0.13,0.0,0.0,1.6,0.2,0.14,0.35,0.21,2.40
4,0.506485,0.640,0.235,0.125,False,2.0,4.0,0.178930,11.9,62.6,...,0.14,0.14,0.2,0.2,1.8,0.2,0.14,0.35,0.20,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6693,0.375406,0.393,0.270,0.337,False,2.0,2.0,0.055302,7.5,14.8,...,0.56,0.32,0.0,0.0,2.2,0.0,0.41,0.90,0.25,4.14
6694,0.518498,0.470,0.269,0.261,True,2.0,3.0,0.842115,2.1,0.0,...,0.58,0.35,0.2,0.2,2.0,0.2,0.43,0.71,0.15,NaN
6695,0.053791,0.422,0.250,0.328,True,3.0,3.0,0.454586,4.1,13.0,...,0.38,0.35,0.4,0.2,1.8,0.2,0.38,0.80,0.28,NaN
6696,0.000000,0.539,0.236,0.225,False,2.0,3.0,0.391390,7.5,22.8,...,0.35,0.32,0.4,0.2,1.6,0.2,0.35,0.72,0.26,NaN
6697,0.184882,NaN,NaN,NaN,True,4.0,3.0,-0.638734,5.8,4.8,...,0.37,0.14,0.6,0.4,1.0,0.2,0.21,0.42,0.21,NaN

In [78]:
mid_xg_model = setup(mid_xg_data, target = 'xG')

In [79]:
mid_xg_best = mid_xg_model.compare_models()

In [81]:
mid_xg_best

GradientBoostingRegressor(random_state=1318)

In [19]:
mid_xg_model.evaluate_model(mid_xg_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [20]:
preds = mid_xg_model.predict_model(mid_xg_best, data=mid_xg_data_tar)

preds.rename(columns={'prediction_label': 'xG_pred'}, inplace=True)

mid_xg_preds = preds[['xG_pred']]
mid_xg_preds

mid_data_tar = pd.concat([mid_data_tar, mid_xg_preds], axis=1)
mid_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xG_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,0.30,2.02,0.0,-0.375000,NaN,0.615,0.220,0.164,0.073910
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,0.14,NaN,0.0,-0.305057,NaN,0.615,0.220,0.164,0.069978
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.26,0.02,NaN,0.0,-0.909705,NaN,0.615,0.220,0.164,0.070403
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.11,NaN,0.0,-0.109684,NaN,0.615,0.220,0.164,0.068312
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.57,0.45,NaN,0.0,-0.103448,NaN,0.732,0.173,0.095,0.066143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.12,0.01,NaN,0.0,-0.762236,NaN,0.615,0.220,0.164,0.069640
9797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.65,0.10,NaN,0.0,0.063236,NaN,0.615,0.220,0.164,0.091773
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.07,0.05,NaN,0.0,-0.759494,NaN,0.615,0.220,0.164,0.068312
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,0.12,NaN,0.0,-0.600000,NaN,0.615,0.220,0.164,0.067188
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.41,0.17,NaN,0.0,-0.770103,NaN,0.615,0.220,0.164,0.075984

In [82]:
save_model(mid_xg_best, model_name='mid_xg_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'expected_assists_1',
                                              'expected_goal_involvements_1',
                                              'expected_goals_1',
                                              'goals_scored_1', 'ict_index_1',
                                              'influence_1', 'creativi...
                                              'threat_1', 'minutes_1',
                                              'red_cards_1', 'yellow_cards_1',
                                              'starts_1', 'team_a_score_1',
                                              'team_h_score_1', 'total_points_1',
                                              'goals_1', 'shots_1', 'xG_1',
                                              'xA_1', 'assists_x_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model',
                  GradientBoostingRegressor(random_state=1318))]),
 'mid_xg_model.pkl')

## For

In [ ]:
f_features = [ 'position',  'xG', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',


            'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1',  'goals_scored_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2',  'goals_scored_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3',  'goals_scored_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4',  'goals_scored_4', 'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5',  'goals_scored_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]

In [89]:
fwd_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'FWD')]
fwd_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '4')]

fwd_xg_data = fwd_data[f_features]
fwd_xg_data_tar = fwd_data_tar[f_features]

fwd_data.reset_index(drop=True, inplace=True)
fwd_xg_data.reset_index(drop=True, inplace=True)

fwd_xg_data.drop(columns=['position'], inplace=True)
fwd_xg_data_tar.drop(columns=['xG', 'position'], inplace=True)

fwd_xg_model = setup(fwd_xg_data, target = 'xG')
fwd_xg_best = fwd_xg_model.compare_models()
fwd_xg_model.evaluate_model(fwd_xg_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [28]:
preds = fwd_xg_model.predict_model(fwd_xg_best, data=fwd_xg_data_tar)

preds.rename(columns={'prediction_label': 'xG_pred'}, inplace=True)

fwd_xg_preds = preds[['xG_pred']]
fwd_xg_preds

fwd_data_tar = pd.concat([fwd_data_tar, fwd_xg_preds], axis=1)
fwd_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xG_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,0.30,2.02,0.0,-0.375000,NaN,0.615,0.220,0.164,0.080359
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,0.14,NaN,0.0,-0.305057,NaN,0.615,0.220,0.164,0.072392
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.26,0.02,NaN,0.0,-0.909705,NaN,0.615,0.220,0.164,0.109488
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.11,NaN,0.0,-0.109684,NaN,0.615,0.220,0.164,0.081126
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.57,0.45,NaN,0.0,-0.103448,NaN,0.732,0.173,0.095,0.065403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.12,0.01,NaN,0.0,-0.762236,NaN,0.615,0.220,0.164,0.068027
9797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.65,0.10,NaN,0.0,0.063236,NaN,0.615,0.220,0.164,0.086503
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.07,0.05,NaN,0.0,-0.759494,NaN,0.615,0.220,0.164,0.080096
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,0.12,NaN,0.0,-0.600000,NaN,0.615,0.220,0.164,0.069326
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.41,0.17,NaN,0.0,-0.770103,NaN,0.615,0.220,0.164,0.081664

In [90]:
save_model(fwd_xg_best, model_name='fwd_xg_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'expected_assists_1',
                                              'expected_goal_involvements_1',
                                              'expected_goals_1',
                                              'goals_scored_1', 'ict_index_1',
                                              'influence_1', 'creativity_1',
                                              'threat_1', 'minutes_1',
                                              'red_cards_1', 'yellow_cards_1',
                                              'starts_1', 'team_a_score_1',
                                              'team_h_score_1', 'total_points_1',
                                              'goals_1', 'shots_1', 'xG_1',
                                              'xA_1', 'assists_x_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model', BayesianRidge())]),
 'fwd_xg_model.pkl')

# Assists

## Def

In [ ]:
def_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence',
                 'creativity', 'threat','starts',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2',
            'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


def_xa_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'DEF')]
def_xa_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '2')]

def_xa_data = def_xa_data[def_xa_features]
def_xa_data_tar = def_xa_data_tar[def_xa_features]

def_xa_data.reset_index(drop=True, inplace=True)
def_xa_data.reset_index(drop=True, inplace=True)

def_xa_data.drop(columns=['position'], inplace=True)
def_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)

In [55]:
def_xa_model = setup(def_xa_data, target = 'xA')
def_xa_best = def_xa_model.compare_models()
def_xa_best
def_xa_model.evaluate_model(def_xa_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [32]:
def_xa_model.evaluate_model(def_xa_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [33]:
preds = def_xa_model.predict_model(def_xa_best, data=def_xa_data_tar)

preds.rename(columns={'prediction_label': 'xA_pred'}, inplace=True)

def_xa_preds = preds[['xA_pred']]
def_xa_preds

def_data_tar = pd.concat([def_data_tar, def_xa_preds], axis=1)
def_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xG_pred,xA_pred
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15,NaN,0.0,-0.391304,NaN,0.615,0.220,0.164,0.058990,0.057305
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,NaN,0.0,0.581669,NaN,0.732,0.173,0.095,0.048398,0.052691
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.23,NaN,0.0,0.791684,NaN,0.732,0.173,0.095,0.014783,0.051283
464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.28,1.06,0.0,-0.857143,NaN,0.732,0.173,0.095,0.049177,0.058501
531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.06,NaN,0.0,-0.991079,NaN,0.732,0.173,0.095,0.037493,0.051040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.40,NaN,0.0,-0.284188,NaN,0.624,0.212,0.164,0.050750,0.056092
9566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,NaN,0.0,0.739250,NaN,0.615,0.220,0.164,0.051292,0.058739
9684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.04,NaN,0.0,-0.600945,NaN,0.441,0.263,0.296,0.071043,0.060093
9704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,0.053381,NaN,0.615,0.220,0.164,0.060491,0.037845
9737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.03,NaN,0.0,-0.330801,NaN,0.615,0.220,0.164,0.061854,0.053070

In [56]:
save_model(def_xa_best, model_name='def_xa_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat', 'starts',
                                              'expected_assists_1',
                                              'expected_goal_involvements_1',
                                              'ict_index_1', 'influence_1',
                                              'creativity_1', 'threat_1',
                                              'minutes_1..._cards_1',
                                              'yellow_cards_1', 'starts_1',
                                              'team_a_score_1', 'team_h_score_1',
                                              'total_points_1', 'shots_1',
                                              'xA_1', 'assists_x_1',
                                              'assists_y_1', 'key_passes_1',
                                              'xGChain_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model', OrthogonalMatchingPursuit())]),
 'def_xa_model.pkl')

## Mid

In [83]:
mid_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


mid_xa_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'MID')]
mid_xa_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '3')]

mid_xa_data = mid_xa_data[mid_xa_features]
mid_xa_data_tar = mid_xa_data_tar[mid_xa_features]

mid_xa_data.reset_index(drop=True, inplace=True)
mid_xa_data.reset_index(drop=True, inplace=True)

mid_xa_data.drop(columns=['position'], inplace=True)
mid_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)

In [84]:
mid_xa_model = setup(mid_xa_data, target = 'xA')
mid_xa_best = mid_xa_model.compare_models()
mid_xa_best
mid_xa_model.evaluate_model(mid_xa_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [85]:
preds = mid_xa_model.predict_model(mid_xa_best, data=mid_xa_data_tar)

preds.rename(columns={'prediction_label': 'xA_pred'}, inplace=True)

mid_xa_preds = preds[['xA_pred']]
mid_xa_preds

mid_data_tar = pd.concat([mid_data_tar, mid_xa_preds], axis=1)
mid_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGChain_5,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xA_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.50,0.30,2.02,0.0,-0.375000,NaN,0.615,0.220,0.164,0.107377
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,0.14,NaN,0.0,-0.305057,NaN,0.615,0.220,0.164,0.120347
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.26,0.02,NaN,0.0,-0.909705,NaN,0.615,0.220,0.164,0.125533
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.11,NaN,0.0,-0.109684,NaN,0.615,0.220,0.164,0.106982
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.57,0.45,NaN,0.0,-0.103448,NaN,0.732,0.173,0.095,0.110549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.12,0.01,NaN,0.0,-0.762236,NaN,0.615,0.220,0.164,0.116197
9797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.65,0.10,NaN,0.0,0.063236,NaN,0.615,0.220,0.164,0.136772
9863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.07,0.05,NaN,0.0,-0.759494,NaN,0.615,0.220,0.164,0.101517
9927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,0.12,NaN,0.0,-0.600000,NaN,0.615,0.220,0.164,0.115156
9960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.41,0.17,NaN,0.0,-0.770103,NaN,0.615,0.220,0.164,0.126960

In [86]:
save_model(mid_xa_best, model_name='mid_xa_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'expected_assists_1',
                                              'expected_goal_involvements_1',
                                              'ict_index_1', 'influence_1',
                                              'creativity_1', 'threat_1',
                                              'minutes_1', 'red_ca...
                                              'yellow_cards_1', 'starts_1',
                                              'team_a_score_1', 'team_h_score_1',
                                              'total_points_1', 'shots_1',
                                              'xA_1', 'assists_x_1',
                                              'assists_y_1', 'key_passes_1',
                                              'xGChain_1', 'xGBuildup_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model',
                  GradientBoostingRegressor(random_state=2560))]),
 'mid_xa_model.pkl')

## For

In [94]:
f_xa_features = [ 'position',  'xA', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'percenatge_net_transfers', 'ict_index', 'influence', 'creativity', 'threat',

            'expected_assists_1', 'expected_goal_involvements_1', 'ict_index_1', 'influence_1', 'creativity_1', 'threat_1', 'minutes_1',
            'red_cards_1', 'yellow_cards_1', 'starts_1', 'team_a_score_1', 'team_h_score_1', 'total_points_1',  'shots_1','xA_1', 'assists_x_1', 'assists_y_1',
            'key_passes_1', 'xGChain_1', 'xGBuildup_1',  'xP_1',

            'expected_assists_2', 'expected_goal_involvements_2', 'ict_index_2', 'influence_2', 'creativity_2', 'threat_2', 'minutes_2',
            'red_cards_2', 'yellow_cards_2', 'starts_2', 'team_a_score_2', 'team_h_score_2', 'total_points_2', 'shots_2', 'xA_2', 'assists_x_2', 'assists_y_2',
            'key_passes_2', 'xGChain_2', 'xGBuildup_2',  'xP_2',

            'expected_assists_3', 'expected_goal_involvements_3', 'ict_index_3', 'influence_3', 'creativity_3', 'threat_3', 'minutes_3',
            'red_cards_3', 'yellow_cards_3', 'starts_3', 'team_a_score_3', 'team_h_score_3', 'total_points_3', 'shots_3', 'xA_3', 'assists_x_3', 'assists_y_3',
            'key_passes_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'expected_assists_4', 'expected_goal_involvements_4',  'ict_index_4', 'influence_4', 'creativity_4', 'threat_4', 'minutes_4',
            'red_cards_4', 'yellow_cards_4', 'starts_4', 'team_a_score_4', 'team_h_score_4', 'total_points_4', 'shots_4', 'xA_4', 'assists_x_4', 'assists_y_4',
            'key_passes_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'expected_assists_5', 'expected_goal_involvements_5', 'ict_index_5', 'influence_5', 'creativity_5', 'threat_5', 'minutes_5',
            'red_cards_5', 'yellow_cards_5', 'starts_5', 'team_a_score_5', 'team_h_score_5', 'total_points_5', 'shots_5',  'xA_5', 'assists_x_5', 'assists_y_5',
            'key_passes_5', 'xGChain_5', 'xGBuildup_5',  'xP_5'
]


fwd_xa_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'FWD')]
fwd_xa_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '4')]

fwd_xa_data = fwd_xa_data[f_xa_features]
fwd_xa_data_tar = fwd_xa_data_tar[f_xa_features]

fwd_xa_data.reset_index(drop=True, inplace=True)
fwd_xa_data.reset_index(drop=True, inplace=True)

fwd_xa_data.drop(columns=['position'], inplace=True)
fwd_xa_data_tar.drop(columns=['xA', 'position'], inplace=True)

In [95]:
fwd_xa_model = setup(fwd_xa_data, target = 'xA')
fwd_xa_best = fwd_xa_model.compare_models()
fwd_xa_best
fwd_xa_model.evaluate_model(fwd_xa_best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [39]:
preds = fwd_xa_model.predict_model(fwd_xa_best, data=fwd_xa_data_tar)

preds.rename(columns={'prediction_label': 'xA_pred'}, inplace=True)

fwd_xa_preds = preds[['xA_pred']]
fwd_xa_preds

fwd_data_tar = pd.concat([fwd_data_tar, fwd_xa_preds], axis=1)
fwd_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xGBuildup_5,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xG_pred,xA_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.30,2.02,0.0,-0.375000,NaN,0.615,0.220,0.164,0.080359,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,NaN,0.0,-0.305057,NaN,0.615,0.220,0.164,0.072392,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.02,NaN,0.0,-0.909705,NaN,0.615,0.220,0.164,0.109488,NaN
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,NaN,0.0,-0.109684,NaN,0.615,0.220,0.164,0.081126,NaN
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.45,NaN,0.0,-0.103448,NaN,0.732,0.173,0.095,0.065403,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.162303
8042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.208567
8566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166596
9431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166009
9623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.206243

In [96]:
save_model(fwd_xa_best, model_name='fwd_xa_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'expected_assists_1',
                                              'expected_goal_involvements_1',
                                              'ict_index_1', 'influence_1',
                                              'creativity_1', 'threat_1',
                                              'minutes_1', 'red_ca...
                                              'yellow_cards_1', 'starts_1',
                                              'team_a_score_1', 'team_h_score_1',
                                              'total_points_1', 'shots_1',
                                              'xA_1', 'assists_x_1',
                                              'assists_y_1', 'key_passes_1',
                                              'xGChain_1', 'xGBuildup_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model', OrthogonalMatchingPursuit())]),
 'fwd_xa_model.pkl')

# Saves

## GK

In [97]:
g_saves_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

            'saves',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



g_saves_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'GK')]
g_saves_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '1')]

g_saves_data = g_saves_data[g_saves_features]
g_saves_data_tar = g_saves_data_tar[g_saves_features]

g_saves_data.reset_index(drop=True, inplace=True)
g_saves_data.reset_index(drop=True, inplace=True)

g_saves_data.drop(columns=['position'], inplace=True)
g_saves_data_tar.drop(columns=['position', 'saves'], inplace=True)

g_saves_model = setup(g_saves_data, target = 'saves')
g_saves_best = g_saves_model.compare_models()
g_saves_best

BayesianRidge()

In [41]:
preds = g_saves_model.predict_model(g_saves_best, data=g_saves_data_tar)

preds.rename(columns={'prediction_label': 'xA_pred'}, inplace=True)

g_saves_preds = preds[['xA_pred']]
g_saves_preds

fwd_data_tar = pd.concat([fwd_data_tar, g_saves_preds], axis=1)
fwd_data_tar

,assists_x,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,...,xP_5,ownership_change,percenatge_net_transfers,pts_bps,whh,whd,wha,xG_pred,xA_pred,xA_pred
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.02,0.0,-0.375000,NaN,0.615,0.220,0.164,0.080359,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.305057,NaN,0.615,0.220,0.164,0.072392,NaN,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.909705,NaN,0.615,0.220,0.164,0.109488,NaN,NaN
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.109684,NaN,0.615,0.220,0.164,0.081126,NaN,NaN
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,-0.103448,NaN,0.732,0.173,0.095,0.065403,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.063735
8077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.061898
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.975925
9653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.182116
9829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.070789

In [98]:
save_model(g_saves_best, model_name='gk_saves_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1',
                                              'influence_...,
                                              'threat_1', 'minutes_1',
                                              'own_goals_1', 'penalties_saved_1',
                                              'yellow_cards_1', 'saves_1',
                                              'starts_1', 'team_a_score_1',
                                              'team_h_score_1', 'total_points_1',
                                              'xGChain_1', 'xGBuildup_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model', BayesianRidge())]),
 'gk_saves_model.pkl')

# Goals Conceded

## GK

In [99]:
g_xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3',  'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]

g_xgc_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'GK')]
g_xgc_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '1')]

g_xgc_data = g_xgc_data[g_xgc_features]
g_xgc_data_tar = g_xgc_data_tar[g_xgc_features]

g_xgc_data.reset_index(drop=True, inplace=True)
g_xgc_data.reset_index(drop=True, inplace=True)

g_xgc_data.drop(columns=['position'], inplace=True)
g_xgc_data_tar.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

g_xgc_model = setup(g_xgc_data, target = 'expected_goals_conceded')
g_xgc_best = g_xgc_model.compare_models()
g_xgc_best

GradientBoostingRegressor(random_state=2963)

In [43]:
preds = g_xgc_model.predict_model(g_xgc_best, data=g_xgc_data_tar)

preds.rename(columns={'prediction_label': 'xgc_pred'}, inplace=True)

g_xgc_preds = preds[['xgc_pred']]
g_xgc_preds

g_data_tar = pd.concat([g_xgc_data_tar, g_xgc_preds], axis=1)
g_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,xgc_pred
631,0.187,0.216,0.596,True,0.0,-0.243328,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,1.0,2.4,1.8,0.10,0.10,NaN,1.521625
719,0.732,0.173,0.095,True,0.0,0.136709,NaN,NaN,NaN,NaN,...,0.2,1.6,1.0,1.6,1.6,1.4,0.11,0.11,NaN,1.383917
811,0.615,0.220,0.164,True,0.0,0.361856,NaN,NaN,NaN,NaN,...,0.0,2.4,1.0,0.6,1.0,3.8,0.13,0.13,NaN,1.383946
837,0.441,0.263,0.296,True,0.0,-0.758231,NaN,NaN,NaN,NaN,...,0.0,1.6,1.0,1.8,1.6,1.0,0.02,0.02,NaN,1.397248
1331,0.695,0.188,0.117,True,0.0,0.514311,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,0.2,1.2,5.2,0.05,0.05,NaN,1.328719
1680,0.624,0.212,0.164,False,0.0,0.042998,NaN,NaN,NaN,NaN,...,0.0,2.6,1.0,1.0,1.6,4.6,0.08,0.06,NaN,1.381881
1715,0.413,0.271,0.316,True,0.0,-0.193798,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,1.8,2.4,1.4,0.19,0.19,1.02,1.604890
2298,0.449,0.290,0.262,False,0.0,-0.696991,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,0.8,1.0,2.6,0.02,0.02,NaN,1.484005
2596,0.441,0.263,0.296,False,0.0,-0.149796,NaN,NaN,NaN,NaN,...,0.2,3.4,1.0,1.2,2.0,4.0,0.18,0.18,NaN,1.486844
3185,0.695,0.188,0.117,False,0.0,-0.550388,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,2.2,1.6,2.4,0.04,0.03,0.98,1.604397
3362,0.732,0.173,0.095,False,0.0,0.252174,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,1.2,1.0,3.0,0.01,0.01,NaN,1.575127
3516,0.732,0.173,0.095,False,0.0,-0.819196,NaN,NaN,NaN,NaN,...,0.2,2.6,1.0,1.8,0.6,1.6,0.18,0.18,0.82,1.603853
3640,0.703,0.187,0.110,True,0.0,-0.922349,NaN,NaN,NaN,NaN,...,0.0,2.2,1.0,1.4,1.8,3.8,0.16,0.16,NaN,1.326809
3923,0.703,0.187,0.110,True,0.0,0.636802,NaN,NaN,NaN,NaN,...,0.0,2.4,1.0,1.6,2.2,4.8,0.19,0.19,NaN,1.367751
4304,0.624,0.212,0.164,True,0.0,0.606642,NaN,NaN,NaN,NaN,...,0.0,2.6,1.0,0.6,0.6,5.4,0.11,0.11,NaN,1.385164
4524,0.624,0.212,0.164,True,0.0,-0.660465,NaN,NaN,NaN,NaN,...,0.2,2.6,1.0,1.6,2.6,2.4,0.42,0.42,2.26,1.522059
4995,0.542,0.243,0.215,False,0.0,-0.190563,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,1.2,1.0,4.8,0.03,0.03,NaN,1.441206
5249,0.542,0.243,0.215,True,0.0,-0.915803,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,1.8,2.2,1.6,0.00,0.00,2.68,1.509802
5530,0.542,0.243,0.215,True,0.0,0.736071,NaN,NaN,NaN,NaN,...,0.0,1.8,1.0,1.6,1.6,3.2,0.36,0.36,NaN,1.324516
6029,0.449,0.290,0.262,True,0.0,0.387800,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,1.0,1.2,5.2,0.03,0.02,NaN,1.423822
6299,0.187,0.216,0.596,True,0.0,-0.113924,NaN,NaN,NaN,NaN,...,0.0,4.8,1.0,2.4,0.8,2.4,0.10,0.10,0.50,1.822674
6332,0.187,0.216,0.596,False,0.0,0.647546,NaN,NaN,NaN,NaN,...,0.4,2.8,1.0,1.6,2.0,2.4,0.19,0.14,NaN,1.334969
6621,0.413,0.271,0.316,False,0.0,-0.750000,NaN,NaN,NaN,NaN,...,0.0,3.4,1.0,3.4,1.8,2.4,0.34,0.34,2.98,1.464749
6979,0.413,0.271,0.316,False,0.0,-0.441832,NaN,NaN,NaN,NaN,...,0.0,3.8,1.0,0.8,1.6,2.6,0.15,0.15,NaN,1.482776
7066,0.703,0.187,0.110,False,0.0,0.169436,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,0.8,1.2,3.2,0.07,0.07,NaN,1.440018
7186,0.703,0.187,0.110,False,0.0,-0.871358,NaN,NaN,NaN,NaN,...,0.0,4.6,1.0,1.4,1.0,2.4,0.09,0.09,1.80,1.689200
7621,0.413,0.271,0.316,True,0.0,-0.635932,NaN,NaN,NaN,NaN,...,0.2,2.0,1.0,1.4,1.0,2.8,0.01,0.01,NaN,1.341972
7797,0.695,0.188,0.117,False,0.0,-0.925816,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,2.0,0.8,2.4,0.16,0.16,2.22,1.562051
8077,0.695,0.188,0.117,True,0.0,-0.941410,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,0.4,2.8,3.0,0.23,0.23,NaN,1.387305
9468,0.695,0.188,0.117,False,0.0,-0.489726,NaN,NaN,NaN,NaN,...,0.2,3.6,1.0,2.0,1.6,1.8,0.22,0.22,NaN,1.544297
9653,0.441,0.263,0.296,True,0.0,-1.000000,NaN,NaN,NaN,NaN,...,0.0,4.0,1.0,1.0,1.2,3.8,0.10,0.10,1.14,1.653526
9829,0.615,0.220,0.164,False,0.0,-0.393388,NaN,NaN,NaN,NaN,...,0.0,3.8,1.0,1.0,0.8,4.0,0.04,0.04,NaN,1.551754

In [100]:
save_model(g_xgc_best, model_name='gk_xgc_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1', 'ict_index_1',
                                              'influence_1', 'creativity_1'...
                                              'own_goals_1', 'penalties_saved_1',
                                              'yellow_cards_1', 'saves_1',
                                              'starts_1', 'team_a_score_1',
                                              'team_h_score_1', 'total_points_1',
                                              'xGChain_1', 'xGBuildup_1', 'xP_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model',
                  GradientBoostingRegressor(random_state=2963))]),
 'gk_xgc_model.pkl')

## Def

In [71]:
def_xgc_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',

            'expected_goals_conceded',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3',  'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



def_xgc_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'DEF')]
def_xgc_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '2')]

def_xgc_data = def_xgc_data[def_xgc_features]
def_xgc_data_tar = def_xgc_data_tar[def_xgc_features]

def_xgc_data.reset_index(drop=True, inplace=True)
def_xgc_data.reset_index(drop=True, inplace=True)

def_xgc_data.drop(columns=['position'], inplace=True)
def_xgc_data_tar.drop(columns=['position', 'expected_goals_conceded'], inplace=True)

def_xgc_model = setup(def_xgc_data, target = 'expected_goals_conceded')
def_xgc_best = def_xgc_model.compare_models()
def_xgc_best

ExtraTreesRegressor(n_jobs=-1, random_state=1076)

In [72]:
preds = def_xgc_model.predict_model(def_xgc_best, data=def_xgc_data_tar)

preds.rename(columns={'prediction_label': 'xgc_pred'}, inplace=True)

def_xgc_preds = preds[['xgc_pred']]
def_xgc_preds

def_data_tar = pd.concat([def_xgc_data_tar, g_xgc_preds], axis=1)
def_data_tar

,whh,whd,wha,was_home,team_h_difficulty,team_a_difficulty,ownership_change,percenatge_net_transfers,ict_index,influence,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,xgc_pred
84,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.391304,NaN,NaN,...,0.0,0.0,1.0,1.8,0.8,2.6,0.18,0.15,NaN,NaN
356,0.732,0.173,0.095,True,2.0,3.0,0.0,0.581669,NaN,NaN,...,0.0,0.0,1.0,1.6,2.0,0.8,0.50,0.50,NaN,NaN
402,0.732,0.173,0.095,True,2.0,3.0,0.0,0.791684,NaN,NaN,...,0.0,0.0,1.0,1.6,1.6,2.6,0.23,0.23,NaN,NaN
464,0.732,0.173,0.095,True,2.0,3.0,0.0,-0.857143,NaN,NaN,...,0.2,0.0,0.8,1.4,1.8,1.2,0.31,0.28,1.06,NaN
531,0.732,0.173,0.095,True,2.0,3.0,0.0,-0.991079,NaN,NaN,...,0.0,0.0,1.0,1.0,3.0,3.8,0.17,0.06,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.562051
8077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.387305
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.544297
9653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.653526
9829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.551754

In [73]:

save_model(def_xgc_best, model_name='def_xgc_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1', 'ict_index_1',
                                              'influence_1', 'creativity_1'...
                                              'own_goals_1', 'penalties_saved_1',
                                              'yellow_cards_1', 'saves_1',
                                              'starts_1', 'team_a_score_1',
                                              'team_h_score_1', 'total_points_1',
                                              'xGChain_1', 'xGBuildup_1', 'xP_1', ...],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=[],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('trained_model',
                  ExtraTreesRegressor(n_jobs=-1, random_state=1076))]),
 'def_xgc_model.pkl')