In [1]:
import pandas as pd
from pycaret.classification import *

In [2]:
gw=32
data_22_23 = pd.read_csv('./data/joint/22-23/merged_player_data.csv',).dropna()
data_23_24 = pd.read_csv('./data/joint/23-24/merged_player_data.csv').dropna()
data_24_25 = pd.read_csv('./data/joint/24-25/merged_player_data.csv')
data_tar = data_24_25[data_24_25['event']==gw]
data_24_25_ = data_24_25[data_24_25['event'] != gw]

data = pd.concat([data_22_23, data_23_24, data_24_25_])

In [3]:
features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'ownership_change', 'percenatge_net_transfers',

            'clean_sheets', 'expected_assists', 'expected_goal_involvements', 'expected_goals', 'expected_goals_conceded', 'goals_conceded', 'goals_scored', 'ict_index',
            'influence', 'creativity', 'threat', 'minutes', 'own_goals', 'penalties_missed', 'penalties_saved', 'red_cards', 'yellow_cards', 'saves', 'starts',
            'team_a_score', 'team_h_score', 'total_points', 'goals', 'shots', 'xG', 'xA', 'assists_x', 'assists_y', 'key_passes', 'npg', 'npxG', 'xGChain',  'xGBuildup',  'xP',

            'clean_sheets_1', 'expected_assists_1', 'expected_goal_involvements_1', 'expected_goals_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_missed_1', 'penalties_saved_1', 'red_cards_1', 'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'goals_1', 'shots_1', 'xG_1', 'xA_1', 'assists_x_1', 'assists_y_1', 'key_passes_1', 'npg_1', 'npxG_1', 'xGChain_1',
            'xGBuildup_1',  'xP_1',

            'clean_sheets_2', 'expected_assists_2', 'expected_goal_involvements_2', 'expected_goals_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'goals_scored_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_missed_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'goals_2', 'shots_2', 'xG_2', 'xA_2', 'assists_x_2', 'assists_y_2', 'key_passes_2', 'npg_2', 'npxG_2', 'xGChain_2',
            'xGBuildup_2',  'xP_2',

            'clean_sheets_3', 'expected_assists_3', 'expected_goal_involvements_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'goals_scored_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_missed_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'goals_3', 'shots_3', 'xG_3', 'xA_3', 'assists_x_3', 'assists_y_3', 'key_passes_3', 'npg_3', 'npxG_3', 'xGChain_3',
            'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_assists_4', 'expected_goal_involvements_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'goals_scored_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_missed_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'goals_4', 'shots_4', 'xG_4', 'xA_4', 'assists_x_4', 'assists_y_4', 'key_passes_4', 'npg_4', 'npxG_4', 'xGChain_4',
            'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_assists_5', 'expected_goal_involvements_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'goals_scored_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_missed_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5', 'goals_5', 'shots_5', 'xG_5', 'xA_5', 'assists_x_5', 'assists_y_5', 'key_passes_5', 'npg_5', 'npxG_5', 'xGChain_5',
            'xGBuildup_5',  'xP_5'
                        ]

# Clean Sheets

## GK

In [37]:
g_cs_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty',  'ownership_change', 'percenatge_net_transfers',

            'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



g_cs_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'GK')]
g_cs_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '1')]

g_cs_data = g_cs_data[g_cs_features]
g_cs_data_tar = g_cs_data_tar[g_cs_features]

g_cs_data.reset_index(drop=True, inplace=True)
g_cs_data.reset_index(drop=True, inplace=True)

g_cs_data.drop(columns=['position'], inplace=True)
g_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)

g_cs_model = setup(g_cs_data, target = 'clean_sheets')
g_cs_best = g_cs_model.compare_models()
g_cs_best

QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [5]:
preds = g_cs_model.predict_model(g_cs_best, data=g_cs_data_tar)

preds.rename(columns={'prediction_label': 'cs_pred'}, inplace=True)

g_cs_preds = preds[['cs_pred']]
g_cs_preds

g_data_tar = pd.concat([g_cs_data_tar, g_cs_preds], axis=1)
g_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,cs_pred
631,0.187,0.216,0.596,True,0.0,-0.243328,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,1.0,2.4,1.8,0.10,0.10,NaN,0
719,0.732,0.173,0.095,True,0.0,0.136709,NaN,NaN,NaN,NaN,...,0.2,1.6,1.0,1.6,1.6,1.4,0.11,0.11,NaN,0
811,0.615,0.220,0.164,True,0.0,0.361856,NaN,NaN,NaN,NaN,...,0.0,2.4,1.0,0.6,1.0,3.8,0.13,0.13,NaN,0
837,0.441,0.263,0.296,True,0.0,-0.758231,NaN,NaN,NaN,NaN,...,0.0,1.6,1.0,1.8,1.6,1.0,0.02,0.02,NaN,0
1331,0.695,0.188,0.117,True,0.0,0.514311,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,0.2,1.2,5.2,0.05,0.05,NaN,0
1680,0.624,0.212,0.164,False,0.0,0.042998,NaN,NaN,NaN,NaN,...,0.0,2.6,1.0,1.0,1.6,4.6,0.08,0.06,NaN,0
1715,0.413,0.271,0.316,True,0.0,-0.193798,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,1.8,2.4,1.4,0.19,0.19,1.02,0
2298,0.449,0.290,0.262,False,0.0,-0.696991,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,0.8,1.0,2.6,0.02,0.02,NaN,0
2596,0.441,0.263,0.296,False,0.0,-0.149796,NaN,NaN,NaN,NaN,...,0.2,3.4,1.0,1.2,2.0,4.0,0.18,0.18,NaN,0
3185,0.695,0.188,0.117,False,0.0,-0.550388,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,2.2,1.6,2.4,0.04,0.03,0.98,0
3362,0.732,0.173,0.095,False,0.0,0.252174,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,1.2,1.0,3.0,0.01,0.01,NaN,0
3516,0.732,0.173,0.095,False,0.0,-0.819196,NaN,NaN,NaN,NaN,...,0.2,2.6,1.0,1.8,0.6,1.6,0.18,0.18,0.82,0
3640,0.703,0.187,0.110,True,0.0,-0.922349,NaN,NaN,NaN,NaN,...,0.0,2.2,1.0,1.4,1.8,3.8,0.16,0.16,NaN,0
3923,0.703,0.187,0.110,True,0.0,0.636802,NaN,NaN,NaN,NaN,...,0.0,2.4,1.0,1.6,2.2,4.8,0.19,0.19,NaN,0
4304,0.624,0.212,0.164,True,0.0,0.606642,NaN,NaN,NaN,NaN,...,0.0,2.6,1.0,0.6,0.6,5.4,0.11,0.11,NaN,0
4524,0.624,0.212,0.164,True,0.0,-0.660465,NaN,NaN,NaN,NaN,...,0.2,2.6,1.0,1.6,2.6,2.4,0.42,0.42,2.26,0
4995,0.542,0.243,0.215,False,0.0,-0.190563,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,1.2,1.0,4.8,0.03,0.03,NaN,0
5249,0.542,0.243,0.215,True,0.0,-0.915803,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,1.8,2.2,1.6,0.00,0.00,2.68,0
5530,0.542,0.243,0.215,True,0.0,0.736071,NaN,NaN,NaN,NaN,...,0.0,1.8,1.0,1.6,1.6,3.2,0.36,0.36,NaN,0
6029,0.449,0.290,0.262,True,0.0,0.387800,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,1.0,1.2,5.2,0.03,0.02,NaN,0
6299,0.187,0.216,0.596,True,0.0,-0.113924,NaN,NaN,NaN,NaN,...,0.0,4.8,1.0,2.4,0.8,2.4,0.10,0.10,0.50,0
6332,0.187,0.216,0.596,False,0.0,0.647546,NaN,NaN,NaN,NaN,...,0.4,2.8,1.0,1.6,2.0,2.4,0.19,0.14,NaN,0
6621,0.413,0.271,0.316,False,0.0,-0.750000,NaN,NaN,NaN,NaN,...,0.0,3.4,1.0,3.4,1.8,2.4,0.34,0.34,2.98,0
6979,0.413,0.271,0.316,False,0.0,-0.441832,NaN,NaN,NaN,NaN,...,0.0,3.8,1.0,0.8,1.6,2.6,0.15,0.15,NaN,0
7066,0.703,0.187,0.110,False,0.0,0.169436,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,0.8,1.2,3.2,0.07,0.07,NaN,0
7186,0.703,0.187,0.110,False,0.0,-0.871358,NaN,NaN,NaN,NaN,...,0.0,4.6,1.0,1.4,1.0,2.4,0.09,0.09,1.80,0
7621,0.413,0.271,0.316,True,0.0,-0.635932,NaN,NaN,NaN,NaN,...,0.2,2.0,1.0,1.4,1.0,2.8,0.01,0.01,NaN,0
7797,0.695,0.188,0.117,False,0.0,-0.925816,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,2.0,0.8,2.4,0.16,0.16,2.22,0
8077,0.695,0.188,0.117,True,0.0,-0.941410,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,0.4,2.8,3.0,0.23,0.23,NaN,0
9468,0.695,0.188,0.117,False,0.0,-0.489726,NaN,NaN,NaN,NaN,...,0.2,3.6,1.0,2.0,1.6,1.8,0.22,0.22,NaN,0
9653,0.441,0.263,0.296,True,0.0,-1.000000,NaN,NaN,NaN,NaN,...,0.0,4.0,1.0,1.0,1.2,3.8,0.10,0.10,1.14,0
9829,0.615,0.220,0.164,False,0.0,-0.393388,NaN,NaN,NaN,NaN,...,0.0,3.8,1.0,1.0,0.8,4.0,0.04,0.04,NaN,0

In [38]:
save_model(g_cs_best, model_name='gk_cs_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1...
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  TransformerWrapper(exclude=None, include=[],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('trained_model',
                  QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                                                store_covariance=False,
                                                tol=0.0001))],
          verbose=False),
 'gk_cs_model.pkl')

## Def

In [ ]:
d_cs_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
                 'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



def_cs_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'DEF')]
def_cs_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '2')]

def_cs_data = def_cs_data[d_cs_features]
def_cs_data_tar = def_cs_data_tar[d_cs_features]

def_cs_data.reset_index(drop=True, inplace=True)
def_cs_data.reset_index(drop=True, inplace=True)

def_cs_data.drop(columns=['position'], inplace=True)
def_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)


def_cs_model = setup(def_cs_data, target = 'clean_sheets')
def_cs_best = def_cs_model.compare_models()
def_cs_best

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=8430, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)

In [9]:
preds = def_cs_model.predict_model(def_cs_best, data=def_cs_data_tar)

preds.rename(columns={'prediction_label': 'cs_pred'}, inplace=True)

def_cs_preds = preds[['cs_pred']]
def_cs_preds

def_data_tar = pd.concat([def_cs_data_tar, def_cs_preds], axis=1)
def_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,cs_pred
84,0.615,0.220,0.164,False,0.0,-0.391304,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.8,0.8,2.6,0.18,0.15,NaN,0
356,0.732,0.173,0.095,True,0.0,0.581669,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,2.0,0.8,0.50,0.50,NaN,1
402,0.732,0.173,0.095,True,0.0,0.791684,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,1.6,2.6,0.23,0.23,NaN,1
464,0.732,0.173,0.095,True,0.0,-0.857143,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.4,1.8,1.2,0.31,0.28,1.06,0
531,0.732,0.173,0.095,True,0.0,-0.991079,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,3.0,3.8,0.17,0.06,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9385,0.624,0.212,0.164,True,0.0,-0.284188,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.4,2.8,0.40,0.40,NaN,0
9566,0.615,0.220,0.164,True,0.0,0.739250,NaN,NaN,NaN,NaN,...,0.0,0.0,0.6,1.6,1.6,2.6,0.12,0.09,NaN,0
9684,0.441,0.263,0.296,True,0.0,-0.600945,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,2.0,1.0,0.6,0.04,0.04,NaN,0
9704,0.615,0.220,0.164,False,0.0,0.053381,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.0,0.8,2.4,0.04,0.02,NaN,0
9737,0.615,0.220,0.164,False,0.0,-0.330801,NaN,NaN,NaN,NaN,...,0.4,0.0,1.0,1.0,0.8,2.4,0.04,0.03,NaN,0

In [40]:

save_model(def_cs_best, model_name='def_cs_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1...
                  LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                 colsample_bytree=1.0, importance_type='split',
                                 learning_rate=0.1, max_depth=-1,
                                 min_child_samples=20, min_child_weight=0.001,
                                 min_split_gain=0.0, n_estimators=100, n_jobs=-1,
                                 num_leaves=31, objective=None,
                                 random_state=8430, reg_alpha=0.0,
                                 reg_lambda=0.0, subsample=1.0,
                                 subsample_for_bin=200000, subsample_freq=0))],
          verbose=False),
 'def_cs_model.pkl')

## Mid

In [ ]:
mid_cs_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
                 'clean_sheets',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



mid_cs_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'DEF')]
mid_cs_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '3')]

mid_cs_data = mid_cs_data[mid_cs_features]
mid_cs_data_tar = mid_cs_data_tar[mid_cs_features]

mid_cs_data.reset_index(drop=True, inplace=True)
mid_cs_data.reset_index(drop=True, inplace=True)

mid_cs_data.drop(columns=['position'], inplace=True)
mid_cs_data_tar.drop(columns=['position', 'clean_sheets'], inplace=True)


mid_cs_model = setup(mid_cs_data, target = 'clean_sheets')
mid_cs_best = mid_cs_model.compare_models()
mid_cs_best

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=-1,
              num_parallel_tree=None, objective='binary:logistic', ...)

In [11]:
preds = mid_cs_model.predict_model(mid_cs_best, data=mid_cs_data_tar)

preds.rename(columns={'prediction_label': 'cs_pred'}, inplace=True)

mid_cs_preds = preds[['cs_pred']]
mid_cs_preds

mid_data_tar = pd.concat([mid_cs_data_tar, mid_cs_preds], axis=1)
mid_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,cs_pred
12,0.615,0.220,0.164,True,0.0,-0.375000,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.8,1.4,2.4,0.50,0.30,2.02,0
49,0.615,0.220,0.164,False,0.0,-0.305057,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,0.6,4.6,0.20,0.14,NaN,0
141,0.615,0.220,0.164,False,0.0,-0.909705,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,0.8,2.4,0.26,0.02,NaN,0
229,0.615,0.220,0.164,False,0.0,-0.109684,NaN,NaN,NaN,NaN,...,0.2,0.0,0.6,1.6,0.8,1.6,0.11,0.11,NaN,0
282,0.732,0.173,0.095,True,0.0,-0.103448,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.6,1.6,1.6,0.57,0.45,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9770,0.615,0.220,0.164,False,0.0,-0.762236,NaN,NaN,NaN,NaN,...,0.0,0.0,0.8,1.0,0.8,2.0,0.12,0.01,NaN,0
9797,0.615,0.220,0.164,True,0.0,0.063236,NaN,NaN,NaN,NaN,...,0.0,0.0,0.6,0.8,2.0,3.0,0.65,0.10,NaN,0
9863,0.615,0.220,0.164,False,0.0,-0.759494,NaN,NaN,NaN,NaN,...,0.0,0.0,0.8,1.0,0.8,1.2,0.07,0.05,NaN,0
9927,0.615,0.220,0.164,False,0.0,-0.600000,NaN,NaN,NaN,NaN,...,0.2,0.0,1.0,1.0,0.8,2.0,0.13,0.12,NaN,0
9960,0.615,0.220,0.164,False,0.0,-0.770103,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,0.8,4.8,0.41,0.17,NaN,0

In [29]:

save_model(mid_cs_best, model_name='mid_cs_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1...
                                importance_type=None,
                                interaction_constraints=None, learning_rate=None,
                                max_bin=None, max_cat_threshold=None,
                                max_cat_to_onehot=None, max_delta_step=None,
                                max_depth=None, max_leaves=None,
                                min_child_weight=None, missing=nan,
                                monotone_constraints=None, multi_strategy=None,
                                n_estimators=None, n_jobs=-1,
                                num_parallel_tree=None,
                                objective='binary:logistic', ...))],
          verbose=False),
 'mid_cs_model.pkl')

# Yellow cards

## GK

In [ ]:
g_y_features = [ 'position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',

                'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



g_y_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'GK')]
g_y_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '1')]

g_y_data = g_y_data[g_y_features]
g_y_data_tar = g_y_data_tar[g_y_features]

g_y_data.reset_index(drop=True, inplace=True)
g_y_data.reset_index(drop=True, inplace=True)

g_y_data.drop(columns=['position'], inplace=True)
g_y_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)


g_y_model = setup(g_y_data, target = 'yellow_cards')
g_y_best = g_y_model.compare_models()
g_y_best

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=7738, solver='auto',
                tol=0.0001)

In [13]:
preds = g_y_model.predict_model(g_y_best, data=g_y_data_tar)

preds.rename(columns={'prediction_label': 'y_pred'}, inplace=True)

g_y_preds = preds[['y_pred']]
g_y_preds

g_data_tar = pd.concat([g_y_data_tar, g_y_preds], axis=1)
g_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,y_pred
631,0.187,0.216,0.596,True,0.0,-0.243328,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,1.0,2.4,1.8,0.10,0.10,NaN,0
719,0.732,0.173,0.095,True,0.0,0.136709,NaN,NaN,NaN,NaN,...,0.2,1.6,1.0,1.6,1.6,1.4,0.11,0.11,NaN,0
811,0.615,0.220,0.164,True,0.0,0.361856,NaN,NaN,NaN,NaN,...,0.0,2.4,1.0,0.6,1.0,3.8,0.13,0.13,NaN,0
837,0.441,0.263,0.296,True,0.0,-0.758231,NaN,NaN,NaN,NaN,...,0.0,1.6,1.0,1.8,1.6,1.0,0.02,0.02,NaN,0
1331,0.695,0.188,0.117,True,0.0,0.514311,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,0.2,1.2,5.2,0.05,0.05,NaN,0
1680,0.624,0.212,0.164,False,0.0,0.042998,NaN,NaN,NaN,NaN,...,0.0,2.6,1.0,1.0,1.6,4.6,0.08,0.06,NaN,0
1715,0.413,0.271,0.316,True,0.0,-0.193798,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,1.8,2.4,1.4,0.19,0.19,1.02,0
2298,0.449,0.290,0.262,False,0.0,-0.696991,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,0.8,1.0,2.6,0.02,0.02,NaN,0
2596,0.441,0.263,0.296,False,0.0,-0.149796,NaN,NaN,NaN,NaN,...,0.2,3.4,1.0,1.2,2.0,4.0,0.18,0.18,NaN,0
3185,0.695,0.188,0.117,False,0.0,-0.550388,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,2.2,1.6,2.4,0.04,0.03,0.98,0
3362,0.732,0.173,0.095,False,0.0,0.252174,NaN,NaN,NaN,NaN,...,0.0,3.0,1.0,1.2,1.0,3.0,0.01,0.01,NaN,0
3516,0.732,0.173,0.095,False,0.0,-0.819196,NaN,NaN,NaN,NaN,...,0.2,2.6,1.0,1.8,0.6,1.6,0.18,0.18,0.82,0
3640,0.703,0.187,0.110,True,0.0,-0.922349,NaN,NaN,NaN,NaN,...,0.0,2.2,1.0,1.4,1.8,3.8,0.16,0.16,NaN,0
3923,0.703,0.187,0.110,True,0.0,0.636802,NaN,NaN,NaN,NaN,...,0.0,2.4,1.0,1.6,2.2,4.8,0.19,0.19,NaN,0
4304,0.624,0.212,0.164,True,0.0,0.606642,NaN,NaN,NaN,NaN,...,0.0,2.6,1.0,0.6,0.6,5.4,0.11,0.11,NaN,0
4524,0.624,0.212,0.164,True,0.0,-0.660465,NaN,NaN,NaN,NaN,...,0.2,2.6,1.0,1.6,2.6,2.4,0.42,0.42,2.26,0
4995,0.542,0.243,0.215,False,0.0,-0.190563,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,1.2,1.0,4.8,0.03,0.03,NaN,0
5249,0.542,0.243,0.215,True,0.0,-0.915803,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,1.8,2.2,1.6,0.00,0.00,2.68,0
5530,0.542,0.243,0.215,True,0.0,0.736071,NaN,NaN,NaN,NaN,...,0.0,1.8,1.0,1.6,1.6,3.2,0.36,0.36,NaN,0
6029,0.449,0.290,0.262,True,0.0,0.387800,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,1.0,1.2,5.2,0.03,0.02,NaN,0
6299,0.187,0.216,0.596,True,0.0,-0.113924,NaN,NaN,NaN,NaN,...,0.0,4.8,1.0,2.4,0.8,2.4,0.10,0.10,0.50,0
6332,0.187,0.216,0.596,False,0.0,0.647546,NaN,NaN,NaN,NaN,...,0.4,2.8,1.0,1.6,2.0,2.4,0.19,0.14,NaN,0
6621,0.413,0.271,0.316,False,0.0,-0.750000,NaN,NaN,NaN,NaN,...,0.0,3.4,1.0,3.4,1.8,2.4,0.34,0.34,2.98,0
6979,0.413,0.271,0.316,False,0.0,-0.441832,NaN,NaN,NaN,NaN,...,0.0,3.8,1.0,0.8,1.6,2.6,0.15,0.15,NaN,0
7066,0.703,0.187,0.110,False,0.0,0.169436,NaN,NaN,NaN,NaN,...,0.0,2.8,1.0,0.8,1.2,3.2,0.07,0.07,NaN,0
7186,0.703,0.187,0.110,False,0.0,-0.871358,NaN,NaN,NaN,NaN,...,0.0,4.6,1.0,1.4,1.0,2.4,0.09,0.09,1.80,0
7621,0.413,0.271,0.316,True,0.0,-0.635932,NaN,NaN,NaN,NaN,...,0.2,2.0,1.0,1.4,1.0,2.8,0.01,0.01,NaN,0
7797,0.695,0.188,0.117,False,0.0,-0.925816,NaN,NaN,NaN,NaN,...,0.0,3.6,1.0,2.0,0.8,2.4,0.16,0.16,2.22,0
8077,0.695,0.188,0.117,True,0.0,-0.941410,NaN,NaN,NaN,NaN,...,0.0,3.2,1.0,0.4,2.8,3.0,0.23,0.23,NaN,0
9468,0.695,0.188,0.117,False,0.0,-0.489726,NaN,NaN,NaN,NaN,...,0.2,3.6,1.0,2.0,1.6,1.8,0.22,0.22,NaN,0
9653,0.441,0.263,0.296,True,0.0,-1.000000,NaN,NaN,NaN,NaN,...,0.0,4.0,1.0,1.0,1.2,3.8,0.10,0.10,1.14,0
9829,0.615,0.220,0.164,False,0.0,-0.393388,NaN,NaN,NaN,NaN,...,0.0,3.8,1.0,1.0,0.8,4.0,0.04,0.04,NaN,0

In [ ]:
save_model(g_y_best, model_name='gk__model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1',
                                              'influence_1', 'creativity_1',
                                              'threat_1...
                  TransformerWrapper(exclude=None, include=[],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('trained_model',
                  RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                  fit_intercept=True, max_iter=None,
                                  positive=False, random_state=7738,
                                  solver='auto', tol=0.0001))],
          verbose=False),
 'gk_yc_model.pkl')

## Def

In [ ]:
d_y_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
            'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



def_y_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'DEF')]
def_y_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '2')]

def_y_data = def_y_data[d_y_features]
def_y_data_tar = def_y_data_tar[d_y_features]

def_y_data.reset_index(drop=True, inplace=True)
def_y_data.reset_index(drop=True, inplace=True)

def_y_data.drop(columns=['position'], inplace=True)
def_y_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)


def_y_model = setup(def_y_data, target = 'yellow_cards')
def_y_best = def_y_model.compare_models()
def_y_best

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=8002, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
preds = def_y_model.predict_model(def_y_best, data=def_y_data_tar)

preds.rename(columns={'prediction_label': 'y_pred'}, inplace=True)

def_y_preds = preds[['y_pred']]
def_y_preds

def_data_tar = pd.concat([def_y_data_tar, def_y_preds], axis=1)
def_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,y_pred
84,0.615,0.220,0.164,False,0.0,-0.391304,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.8,0.8,2.6,0.18,0.15,NaN,0
356,0.732,0.173,0.095,True,0.0,0.581669,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,2.0,0.8,0.50,0.50,NaN,0
402,0.732,0.173,0.095,True,0.0,0.791684,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,1.6,2.6,0.23,0.23,NaN,0
464,0.732,0.173,0.095,True,0.0,-0.857143,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.4,1.8,1.2,0.31,0.28,1.06,0
531,0.732,0.173,0.095,True,0.0,-0.991079,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,3.0,3.8,0.17,0.06,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9385,0.624,0.212,0.164,True,0.0,-0.284188,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,1.4,2.8,0.40,0.40,NaN,0
9566,0.615,0.220,0.164,True,0.0,0.739250,NaN,NaN,NaN,NaN,...,0.0,0.0,0.6,1.6,1.6,2.6,0.12,0.09,NaN,0
9684,0.441,0.263,0.296,True,0.0,-0.600945,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,2.0,1.0,0.6,0.04,0.04,NaN,0
9704,0.615,0.220,0.164,False,0.0,0.053381,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.0,0.8,2.4,0.04,0.02,NaN,0
9737,0.615,0.220,0.164,False,0.0,-0.330801,NaN,NaN,NaN,NaN,...,0.4,0.0,1.0,1.0,0.8,2.4,0.04,0.03,NaN,0

In [42]:
save_model(def_y_best, model_name='def_yc_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1...
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=8002,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 'def_yc_model.pkl')

## Mid

In [ ]:
mid_y_features = ['position', 'whh', 'whd', 'wha', 'was_home', 'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers',
            'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



mid_y_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'MID')]
mid_y_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '3')]

mid_y_data = mid_y_data[mid_y_features]
mid_y_data_tar = mid_y_data_tar[mid_y_features]

mid_y_data.reset_index(drop=True, inplace=True)
mid_y_data.reset_index(drop=True, inplace=True)

mid_y_data.drop(columns=['position'], inplace=True)
mid_y_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)


mid_y_model = setup(mid_y_data, target = 'yellow_cards')
mid_y_best = mid_y_model.compare_models()
mid_y_best

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=3431, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
preds = mid_y_model.predict_model(mid_y_best, data=mid_y_data_tar)

preds.rename(columns={'prediction_label': 'y_pred'}, inplace=True)

mid_y_preds = preds[['y_pred']]
mid_y_preds

mid_data_tar = pd.concat([mid_y_data_tar, mid_y_preds], axis=1)
mid_data_tar

,whh,whd,wha,was_home,team_h_difficulty,team_a_difficulty,ownership_change,percenatge_net_transfers,ict_index,influence,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,y_pred
12,0.615,0.220,0.164,True,2.0,4.0,0.0,-0.375000,NaN,NaN,...,0.0,0.0,1.0,1.8,1.4,2.4,0.50,0.30,2.02,0
49,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.305057,NaN,NaN,...,0.0,0.0,1.0,1.6,0.6,4.6,0.20,0.14,NaN,0
141,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.909705,NaN,NaN,...,0.0,0.0,1.0,1.0,0.8,2.4,0.26,0.02,NaN,0
229,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.109684,NaN,NaN,...,0.2,0.0,0.6,1.6,0.8,1.6,0.11,0.11,NaN,0
282,0.732,0.173,0.095,True,2.0,3.0,0.0,-0.103448,NaN,NaN,...,0.2,0.0,0.8,1.6,1.6,1.6,0.57,0.45,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9770,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.762236,NaN,NaN,...,0.0,0.0,0.8,1.0,0.8,2.0,0.12,0.01,NaN,0
9797,0.615,0.220,0.164,True,2.0,4.0,0.0,0.063236,NaN,NaN,...,0.0,0.0,0.6,0.8,2.0,3.0,0.65,0.10,NaN,0
9863,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.759494,NaN,NaN,...,0.0,0.0,0.8,1.0,0.8,1.2,0.07,0.05,NaN,0
9927,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.600000,NaN,NaN,...,0.2,0.0,1.0,1.0,0.8,2.0,0.13,0.12,NaN,0
9960,0.615,0.220,0.164,False,2.0,4.0,0.0,-0.770103,NaN,NaN,...,0.0,0.0,1.0,1.0,0.8,4.8,0.41,0.17,NaN,0

In [34]:
save_model(mid_y_best, model_name='mid_yc_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1...
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='most_frequent'))),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=3431,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 'mid_yc_model.pkl')

## FWD

In [35]:
fwd_y_features = [ 'position', 'whh', 'whd', 'wha', 'was_home',  'team_h_difficulty', 'team_a_difficulty', 'ownership_change', 'percenatge_net_transfers', 'yellow_cards',  'ict_index', 'influence', 'creativity', 'threat',

            'clean_sheets_1', 'expected_goals_conceded_1', 'goals_conceded_1', 'goals_scored_1', 'ict_index_1',
            'influence_1', 'creativity_1', 'threat_1', 'minutes_1', 'own_goals_1', 'penalties_saved_1',  'yellow_cards_1', 'saves_1', 'starts_1',
            'team_a_score_1', 'team_h_score_1', 'total_points_1', 'xGChain_1', 'xGBuildup_1', 'xP_1',

            'clean_sheets_2', 'expected_goals_conceded_2', 'goals_conceded_2', 'ict_index_2',
            'influence_2', 'creativity_2', 'threat_2', 'minutes_2', 'own_goals_2', 'penalties_saved_2', 'red_cards_2', 'yellow_cards_2', 'saves_2', 'starts_2',
            'team_a_score_2', 'team_h_score_2', 'total_points_2', 'xGChain_2', 'xGBuildup_2', 'xP_2',

            'clean_sheets_3', 'expected_goals_3', 'expected_goals_conceded_3', 'goals_conceded_3', 'ict_index_3',
            'influence_3', 'creativity_3', 'threat_3', 'minutes_3', 'own_goals_3', 'penalties_saved_3', 'red_cards_3', 'yellow_cards_3', 'saves_3', 'starts_3',
            'team_a_score_3', 'team_h_score_3', 'total_points_3', 'xGChain_3', 'xGBuildup_3',  'xP_3',

            'clean_sheets_4', 'expected_goals_4', 'expected_goals_conceded_4', 'goals_conceded_4', 'ict_index_4',
            'influence_4', 'creativity_4', 'threat_4', 'minutes_4', 'own_goals_4', 'penalties_saved_4', 'red_cards_4', 'yellow_cards_4', 'saves_4', 'starts_4',
            'team_a_score_4', 'team_h_score_4', 'total_points_4', 'xGChain_4', 'xGBuildup_4',  'xP_4',

            'clean_sheets_5', 'expected_goals_5', 'expected_goals_conceded_5', 'goals_conceded_5', 'ict_index_5',
            'influence_5', 'creativity_5', 'threat_5', 'minutes_5', 'own_goals_5', 'penalties_saved_5', 'red_cards_5', 'yellow_cards_5', 'saves_5', 'starts_5',
            'team_a_score_5', 'team_h_score_5', 'total_points_5',  'xGChain_5', 'xGBuildup_5',  'xP_5'
                        ]



fwd_y_data= data[(data['minutes_5'] >= 60) & (data['position'] == 'FWD')]
fwd_y_data_tar = data_tar[(data_tar['minutes_5'] >= 60) & (data_tar['position'] == '4')]

fwd_y_data = fwd_y_data[fwd_y_features]
fwd_y_data_tar = fwd_y_data_tar[fwd_y_features]

fwd_y_data.reset_index(drop=True, inplace=True)
fwd_y_data.reset_index(drop=True, inplace=True)

fwd_y_data.drop(columns=['position'], inplace=True)
fwd_y_data_tar.drop(columns=['position', 'yellow_cards'], inplace=True)


fwd_y_model = setup(fwd_y_data, target = 'yellow_cards')
fwd_y_best = fwd_y_model.compare_models()
fwd_y_best

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=6189, verbose=0,
                       warm_start=False)

In [19]:
preds = fwd_y_model.predict_model(fwd_y_best, data=fwd_y_data_tar)

preds.rename(columns={'prediction_label': 'y_pred'}, inplace=True)

fwd_y_preds = preds[['y_pred']]
fwd_y_preds

fwd_data_tar = pd.concat([fwd_y_data_tar, fwd_y_preds], axis=1)
fwd_data_tar

,whh,whd,wha,was_home,ownership_change,percenatge_net_transfers,ict_index,influence,creativity,threat,...,yellow_cards_5,saves_5,starts_5,team_a_score_5,team_h_score_5,total_points_5,xGChain_5,xGBuildup_5,xP_5,y_pred
203,0.615,0.220,0.164,False,0.0,-0.712407,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,0.8,5.2,0.43,0.00,NaN,0
491,0.732,0.173,0.095,True,0.0,-0.382093,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.6,1.6,4.2,0.62,0.43,NaN,0
1235,0.695,0.188,0.117,True,0.0,0.642444,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,0.6,1.8,2.0,0.37,0.06,NaN,0
1586,0.615,0.220,0.164,True,0.0,-0.859459,NaN,NaN,NaN,NaN,...,0.0,0.0,0.8,1.8,0.8,6.6,0.70,0.31,4.22,0
1801,0.624,0.212,0.164,False,0.0,0.946128,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.4,1.6,5.8,0.60,0.06,NaN,0
1969,0.449,0.290,0.262,False,0.0,-0.809178,NaN,NaN,NaN,NaN,...,0.2,0.0,1.0,0.8,1.0,1.8,0.35,0.01,NaN,0
2946,0.695,0.188,0.117,False,0.0,0.007063,NaN,NaN,NaN,NaN,...,0.2,0.0,1.0,2.0,1.6,4.4,0.43,0.16,NaN,0
3555,0.732,0.173,0.095,False,0.0,-0.503775,NaN,NaN,NaN,NaN,...,0.2,0.0,1.0,1.2,1.0,1.6,0.22,0.01,NaN,0
4423,0.624,0.212,0.164,True,0.0,-0.989972,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.6,2.2,5.4,0.47,0.06,5.58,0
5337,0.615,0.220,0.164,True,0.0,-0.914174,NaN,NaN,NaN,NaN,...,0.4,0.0,1.0,1.0,2.0,5.8,0.83,0.20,3.20,0
5366,0.542,0.243,0.215,True,0.0,0.434903,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,2.0,5.4,0.51,0.04,NaN,0
6064,0.449,0.290,0.262,True,0.0,-0.956071,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.6,1.8,4.0,0.18,0.03,NaN,0
7752,0.413,0.271,0.316,True,0.0,-0.025066,NaN,NaN,NaN,NaN,...,0.4,0.0,0.8,1.4,1.0,6.0,0.53,0.02,NaN,0
8042,0.187,0.216,0.596,False,0.0,0.353683,NaN,NaN,NaN,NaN,...,0.2,0.0,0.8,1.4,1.6,3.6,0.36,0.03,NaN,0
8566,0.441,0.263,0.296,True,0.0,0.671543,NaN,NaN,NaN,NaN,...,0.0,0.0,0.8,1.8,1.6,6.4,0.43,0.02,NaN,0
9431,0.624,0.212,0.164,True,0.0,0.592898,NaN,NaN,NaN,NaN,...,0.0,0.0,0.8,0.6,1.0,5.2,0.55,0.22,NaN,0
9623,0.413,0.271,0.316,False,0.0,-0.604102,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,0.8,2.0,1.6,0.61,0.33,NaN,0

In [36]:
save_model(fwd_y_best, model_name='fwd_yc_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['whh', 'whd', 'wha',
                                              'team_h_difficulty',
                                              'team_a_difficulty',
                                              'ownership_change',
                                              'percenatge_net_transfers',
                                              'ict_index', 'influence',
                                              'creativity', 'threat',
                                              'clean_sheets_1',
                                              'expected_goals_conceded_1',
                                              'goals_conceded_1',
                                              'goals_scored_1', 'ict_index_1...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='sqrt',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         monotonic_cst=None, n_estimators=100,
                                         n_jobs=-1, oob_score=False,
                                         random_state=6189, verbose=0,
                                         warm_start=False))],
          verbose=False),
 'fwd_yc_model.pkl')